// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

// BuildDependencies package dependencies
type BuildDependencies struct {
	// ECS dependency
	ECS BuildDependenciesECS `json:"ecs,omitempty" yaml:"ecs,omitempty"`
}

// BuildDependenciesECS ECS dependency
type BuildDependenciesECS struct {
	// Whether or not import common used dynamic templates and properties into the package
	ImportMappings *bool `json:"import_mappings,omitempty" yaml:"import_mappings,omitempty"`
	// Reference is the ECS version source reference. Values begin with "git@" (e.g. "git@v8.11.0").
	Reference string `json:"reference" yaml:"reference"`
}

type BuildManifest struct {
	FileMetadata `json:"-" yaml:"-"`
	// Package dependencies
	Dependencies BuildDependencies `json:"dependencies" yaml:"dependencies"`
}

// UnmarshalYAML implements yaml.Unmarshaler for BuildManifest.
// It captures the YAML node position for FileMetadata.
func (v *BuildManifest) UnmarshalYAML(node *yamlv3.Node) error {
	type plainBuildManifest BuildManifest
	x := (*plainBuildManifest)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}
