// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import (
	yamlv3 "gopkg.in/yaml.v3"
	"time"
)

type Changelog struct {
	FileMetadata `json:"-" yaml:"-"`
	// List of changes in package version.
	Changes []ChangelogEntry `json:"changes" yaml:"changes"`
	// Package version.
	Version string `json:"version" yaml:"version"`
	// Date is the approximate release date, populated via git blame when WithGitMetadata is used.
	Date *time.Time `json:"date,omitempty" yaml:"-"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Changelog.
// It captures the YAML node position for FileMetadata.
func (v *Changelog) UnmarshalYAML(node *yamlv3.Node) error {
	type plainChangelog Changelog
	x := (*plainChangelog)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

type ChangelogEntry struct {
	// Description of change.
	Description string `json:"description" yaml:"description"`
	// Link to issue or PR describing change in detail.
	Link string `json:"link" yaml:"link"`
	// Type of change.
	Type ChangelogEntryType `json:"type" yaml:"type"`
}

// ChangelogEntryType type of change.
type ChangelogEntryType string

// Enum values for ChangelogEntryType.
const (
	ChangelogEntryTypeBreakingChange ChangelogEntryType = "breaking-change"
	ChangelogEntryTypeBugfix         ChangelogEntryType = "bugfix"
	ChangelogEntryTypeEnhancement    ChangelogEntryType = "enhancement"
	ChangelogEntryTypeDeprecation    ChangelogEntryType = "deprecation"
)
