// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

// DataStreamElasticsearch elasticsearch asset definitions
type DataStreamElasticsearch struct {
	// When set to true, agents running this integration are granted data stream privileges for all
	// datasets of its type
	DynamicDataset *bool `json:"dynamic_dataset,omitempty" yaml:"dynamic_dataset,omitempty"`
	// When set to true, agents running this integration are granted data stream privileges for all
	// namespaces of its type
	DynamicNamespace *bool         `json:"dynamic_namespace,omitempty" yaml:"dynamic_namespace,omitempty"`
	IndexMode        IndexMode     `json:"index_mode,omitempty" yaml:"index_mode,omitempty"`
	IndexTemplate    IndexTemplate `json:"index_template,omitempty" yaml:"index_template,omitempty"`
	// Elasticsearch privilege requirements
	Privileges DataStreamElasticsearchPrivileges `json:"privileges,omitempty" yaml:"privileges,omitempty"`
	// Source mode to use. This configures how the document source (`_source`) is stored for this data
	// stream.
	//
	// If configured as `default`, this mode is not configured and it uses Elasticsearch defaults.
	//
	// If configured as `synthetic`, it enables [synthetic source], that doesn't store the source, but
	// tries to rebuild it from the indexed fields when queried.
	//
	// If no configured or set to `synthetic`, users may override the setting from Fleet UI.
	//
	// [synthetic source]: https://www.elastic.co/guide/en/elasticsearch/reference/8.4/mapping-source-field.html#synthetic-source
	SourceMode DataStreamSourceMode `json:"source_mode,omitempty" yaml:"source_mode,omitempty"`
}

// DataStreamElasticsearchPrivileges elasticsearch privilege requirements
type DataStreamElasticsearchPrivileges struct {
	// Elasticsearch index privilege requirements
	Indices []string `json:"indices,omitempty" yaml:"indices,omitempty"`
}

type DataStreamManifest struct {
	FileMetadata `json:"-" yaml:"-"`
	Agent        Agent `json:"agent,omitempty" yaml:"agent,omitempty"`
	// Optional categories that describe the type of data collected by this data stream. Used for
	// telemetry and categorization purposes. Skip if integration-level categories are appropriate.
	Categories []Category `json:"categories,omitempty" yaml:"categories,omitempty"`
	// Name of data set.
	Dataset string `json:"dataset,omitempty" yaml:"dataset,omitempty"`
	// If true, the index pattern in the ES template will contain the dataset as a prefix only
	DatasetIsPrefix *bool      `json:"dataset_is_prefix,omitempty" yaml:"dataset_is_prefix,omitempty"`
	Deprecated      Deprecated `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	// Elasticsearch asset definitions
	Elasticsearch DataStreamElasticsearch `json:"elasticsearch,omitempty" yaml:"elasticsearch,omitempty"`
	// Specifies if a data stream is hidden, resulting in dot prefixed system indices. To set the data
	// stream hidden without those dot prefixed indices, check
	// `elasticsearch.index_template.data_stream.hidden` flag.
	Hidden *bool `json:"hidden,omitempty" yaml:"hidden,omitempty"`
	// The name of an existing ILM (Index Lifecycle Management) policy
	ILMPolicy string `json:"ilm_policy,omitempty" yaml:"ilm_policy,omitempty"`
	// Stability of data stream.
	Release DataStreamRelease `json:"release,omitempty" yaml:"release,omitempty"`
	// Streams offered by data stream.
	Streams []DataStreamStream `json:"streams,omitempty" yaml:"streams,omitempty"`
	// Title of data stream. It should include the source of the data that is being collected, and the
	// kind of data collected such as logs or metrics. Words should be uppercased.
	Title string `json:"title" yaml:"title"`
	// Type of data stream
	Type DataStreamType `json:"type,omitempty" yaml:"type,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for DataStreamManifest.
// It captures the YAML node position for FileMetadata.
func (v *DataStreamManifest) UnmarshalYAML(node *yamlv3.Node) error {
	type plainDataStreamManifest DataStreamManifest
	x := (*plainDataStreamManifest)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// DataStreamRelease stability of data stream.
type DataStreamRelease string

// Enum values for DataStreamRelease.
const (
	DataStreamReleaseExperimental DataStreamRelease = "experimental"
	DataStreamReleaseBeta         DataStreamRelease = "beta"
)

// DataStreamSourceMode source mode to use. This configures how the document source (`_source`) is
// stored for this data stream.
//
// If configured as `default`, this mode is not configured and it uses Elasticsearch defaults.
//
// If configured as `synthetic`, it enables [synthetic source], that doesn't store the source, but
// tries to rebuild it from the indexed fields when queried.
//
// If no configured or set to `synthetic`, users may override the setting from Fleet UI.
//
// [synthetic source]: https://www.elastic.co/guide/en/elasticsearch/reference/8.4/mapping-source-field.html#synthetic-source
type DataStreamSourceMode string

// Enum values for DataStreamSourceMode.
const (
	DataStreamSourceModeDefault   DataStreamSourceMode = "default"
	DataStreamSourceModeSynthetic DataStreamSourceMode = "synthetic"
)

type DataStreamStream struct {
	// Description of the stream. It should describe what is being collected and with what collector,
	// following the structure "Collect X from Y with X".
	Description string `json:"description" yaml:"description"`
	// Is stream enabled?
	Enabled      *bool        `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	Input        string       `json:"input" yaml:"input"`
	RequiredVars RequiredVars `json:"required_vars,omitempty" yaml:"required_vars,omitempty"`
	// Path to Elasticsearch index template for stream.
	TemplatePath string `json:"template_path,omitempty" yaml:"template_path,omitempty"`
	// Title of the stream. It should include the source of the data that is being collected, and the
	// kind of data collected such as logs or metrics. Words should be uppercased.
	Title     string     `json:"title" yaml:"title"`
	VarGroups []VarGroup `json:"var_groups,omitempty" yaml:"var_groups,omitempty"`
	Vars      []Var      `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// DataStreamType type of data stream
type DataStreamType string

// Enum values for DataStreamType.
const (
	DataStreamTypeMetrics    DataStreamType = "metrics"
	DataStreamTypeLogs       DataStreamType = "logs"
	DataStreamTypeSynthetics DataStreamType = "synthetics"
	DataStreamTypeTraces     DataStreamType = "traces"
	DataStreamTypeProfiling  DataStreamType = "profiling"
)
