// Package pkgspec provides a typed Go data model for Elastic integration
// packages, generated from the [package-spec JSON schemas]. It covers
// manifests (integration, input, and content), data stream definitions,
// field schemas, ingest pipelines, policy templates, changelogs,
// transforms, and related types.
//
// Most types in this package are generated by cmd/generate and should not
// be edited by hand. Hand-written files include [Processor] (custom
// marshal/unmarshal), [StringOrStrings], [FlattenFields], and
// [ManifestType].
//
// Every entry-point type embeds [FileMetadata], which records the source
// file path, line, and column from YAML decoding. Use [AnnotateFileMetadata]
// to populate these annotations after reading a package.
//
// [package-spec JSON schemas]: https://github.com/andrewkroh/package-spec-schema
package pkgspec
