// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

// ElasticsearchIndexMode index mode to use. Index mode can be used to enable use case specific
// functionalities. This setting must be installed in the composable index template, not in the
// package component templates.
type ElasticsearchIndexMode string

// Enum values for ElasticsearchIndexMode.
const (
	ElasticsearchIndexModeTimeSeries ElasticsearchIndexMode = "time_series"
)

// ElasticsearchIndexTemplate index template definition
type ElasticsearchIndexTemplate struct {
	// DataStream data stream section of index template
	DataStream ElasticsearchIndexTemplateDataStream `json:"data_stream,omitempty" yaml:"data_stream,omitempty"`
	// IngestPipeline elasticsearch ingest pipeline settings
	IngestPipeline ElasticsearchIndexTemplateIngestPipeline `json:"ingest_pipeline,omitempty" yaml:"ingest_pipeline,omitempty"`
	// Mappings section of index template
	Mappings ElasticsearchIndexTemplateMappings `json:"mappings,omitempty" yaml:"mappings,omitempty"`
	// Settings section of index template
	Settings ElasticsearchIndexTemplateSettings `json:"settings,omitempty" yaml:"settings,omitempty"`
}

// ElasticsearchIndexTemplateDataStream data stream section of index template
type ElasticsearchIndexTemplateDataStream struct {
	// Hidden makes the data stream hidden
	Hidden *bool `json:"hidden,omitempty" yaml:"hidden,omitempty"`
}

// ElasticsearchIndexTemplateIngestPipeline elasticsearch ingest pipeline settings
type ElasticsearchIndexTemplateIngestPipeline struct {
	// Name ingest pipeline name
	Name string `json:"name" yaml:"name"`
}

// ElasticsearchIndexTemplateMappings mappings section of index template
type ElasticsearchIndexTemplateMappings struct {
	// DateDetection if true, new string fields will be checked to see if their contents match with
	// `dynamic_date_formats`. If they do, the field is dynamically added with type `date`. Set to false
	// to disable this feature.
	DateDetection *bool `json:"date_detection,omitempty" yaml:"date_detection,omitempty"`
	// Dynamic controls whether new fields can be added dynamically to the mapping.
	Dynamic any `json:"dynamic,omitempty" yaml:"dynamic,omitempty"`
	// DynamicDateFormats custom date formats to use for date detection.
	DynamicDateFormats []string `json:"dynamic_date_formats,omitempty" yaml:"dynamic_date_formats,omitempty"`
	// DynamicTemplates defines custom rules for dynamic field mapping.
	DynamicTemplates any `json:"dynamic_templates,omitempty" yaml:"dynamic_templates,omitempty"`
	// Subobjects turn the support for subobjects on or off in the mapping configuration for the data
	// stream. By default, it's set to `true`, enabling Elasticsearch to expands fields that contain
	// dots in their names to their corresponding object structure. Setting it to `false` restricts
	// objects from holding subobjects, enabling storing documents with dot-contained field names and
	// common prefixes. It is still possible to send documents that have objects to a data stream that
	// has set subobjects to `false`. Example when the subobjects mapping option is `false`: PUT
	// my-index-000001 { "mappings": { "subobjects": false } } PUT my-index-000001/_doc/metric_1 {
	// "time" : "100ms", "time.min" : "10ms", "time.max" : "900ms" } Before disabling subobjects,
	// consider the following implications: - Nested field types cannot be used in data streams. - The
	// subobjects mapping definition is immutable. - This setting depends on auto-flattening mappings,
	// which comes with limitations [^1] for integration and custom mappings in data streams without
	// subobjects. - Auto-flattening is available starting from version 8.14, integrations must be on at
	// least this version. For comprehensive details on subobjects, refer to the Elasticsearch
	// documentation [^2]. [^1]: Auto-flattening limitations are documented at:
	// https://www.elastic.co/guide/en/elasticsearch/reference/master/subobjects.html#_auto_flattening_o
	// bject_mappings [^2]: Elasticsearch documentation on subobjects:
	// https://www.elastic.co/guide/en/elasticsearch/reference/current/subobjects.html
	Subobjects *bool `json:"subobjects,omitempty" yaml:"subobjects,omitempty"`
}

type ElasticsearchIndexTemplateMappingsDynamicTemplateValue struct {
	Mapping          ElasticsearchIndexTemplateMappingsDynamicTemplateValueMapping `json:"mapping,omitempty" yaml:"mapping,omitempty"`
	MatchMappingType any                                                           `json:"match_mapping_type,omitempty" yaml:"match_mapping_type,omitempty"`
}

type ElasticsearchIndexTemplateMappingsDynamicTemplateValueMapping struct {
	DefaultMetric any       `json:"default_metric,omitempty" yaml:"default_metric,omitempty"`
	IgnoreAbove   int       `json:"ignore_above,omitempty" yaml:"ignore_above,omitempty"`
	Index         *bool     `json:"index,omitempty" yaml:"index,omitempty"`
	Metrics       any       `json:"metrics,omitempty" yaml:"metrics,omitempty"`
	ScalingFactor int       `json:"scaling_factor,omitempty" yaml:"scaling_factor,omitempty"`
	Type          FieldType `json:"type,omitempty" yaml:"type,omitempty"`
}

// ElasticsearchIndexTemplateSettings settings section of index template
type ElasticsearchIndexTemplateSettings struct {
	Analysis       IndexTemplateSettingAnalysis `json:"analysis,omitempty" yaml:"analysis,omitempty"`
	Index          IndexTemplateSettingIndex    `json:"index,omitempty" yaml:"index,omitempty"`
	NumberOfShards int                          `json:"number_of_shards,omitempty" yaml:"number_of_shards,omitempty"`
}

type IndexTemplateSettingAnalysis struct {
	// Analyzer definition of custom analyzer.
	Analyzer map[string]IndexTemplateSettingAnalysisAnalyzerValue `json:"analyzer,omitempty" yaml:"analyzer,omitempty"`
}

type IndexTemplateSettingAnalysisAnalyzerValue struct {
	Pattern string `json:"pattern,omitempty" yaml:"pattern,omitempty"`
	// Type of analyzer
	Type IndexTemplateSettingAnalysisAnalyzerValueType `json:"type,omitempty" yaml:"type,omitempty"`
}

// IndexTemplateSettingAnalysisAnalyzerValueType type of analyzer
type IndexTemplateSettingAnalysisAnalyzerValueType string

// Enum values for IndexTemplateSettingAnalysisAnalyzerValueType.
const (
	IndexTemplateSettingAnalysisAnalyzerValueTypePattern IndexTemplateSettingAnalysisAnalyzerValueType = "pattern"
)

type IndexTemplateSettingIndex struct {
	// Codec type of compression to use. The default is to use LZ4, `best_compression` uses DEFLATE,
	// with higher compression but lower ingestion performance.
	Codec   IndexTemplateSettingIndexCodec   `json:"codec,omitempty" yaml:"codec,omitempty"`
	Mapping IndexTemplateSettingIndexMapping `json:"mapping,omitempty" yaml:"mapping,omitempty"`
	Sort    IndexTemplateSettingIndexSort    `json:"sort,omitempty" yaml:"sort,omitempty"`
}

// IndexTemplateSettingIndexCodec type of compression to use. The default is to use LZ4,
// `best_compression` uses DEFLATE, with higher compression but lower ingestion performance.
type IndexTemplateSettingIndexCodec string

// Enum values for IndexTemplateSettingIndexCodec.
const (
	IndexTemplateSettingIndexCodecDefault         IndexTemplateSettingIndexCodec = "default"
	IndexTemplateSettingIndexCodecBestCompression IndexTemplateSettingIndexCodec = "best_compression"
)

type IndexTemplateSettingIndexMapping struct{}

type IndexTemplateSettingIndexSort struct {
	// Field is the field or fields used to sort documents.
	Field any `json:"field,omitempty" yaml:"field,omitempty"`
	// Order is the sort order to use for each field.
	Order any `json:"order,omitempty" yaml:"order,omitempty"`
}
