// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

// IngestPipeline represents an Elasticsearch ingest pipeline definition.
type IngestPipeline struct {
	FileMetadata `json:"-" yaml:"-"`
	// Description of the pipeline.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// OnFailure list of processors to apply in case of failure.
	OnFailure []*Processor `json:"on_failure,omitempty" yaml:"on_failure,omitempty"`
	// Processors list of processors that conform the pipeline.
	Processors []*Processor `json:"processors,omitempty" yaml:"processors,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for IngestPipeline.
// It captures the YAML node position for FileMetadata.
func (v *IngestPipeline) UnmarshalYAML(node *yamlv3.Node) error {
	type plainIngestPipeline IngestPipeline
	x := (*plainIngestPipeline)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}
