// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

type Lifecycle struct {
	FileMetadata `json:"-" yaml:"-"`
	// Every document collected will be stored at least during this time frame. Any time after this
	// duration the documents could be deleted.
	DataRetention string `json:"data_retention" yaml:"data_retention"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Lifecycle.
// It captures the YAML node position for FileMetadata.
func (v *Lifecycle) UnmarshalYAML(node *yamlv3.Node) error {
	type plainLifecycle Lifecycle
	x := (*plainLifecycle)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}
