// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import (
	"encoding/json"
	yamlv3 "gopkg.in/yaml.v3"
)

// AgentlessResourceRequests the computing resources that the Agentless deployment will be initially
// allocated.
type AgentlessResourceRequests struct {
	// The amount of CPUs that the Agentless deployment will be initially allocated.
	CPU string `json:"cpu,omitempty" yaml:"cpu,omitempty"`
	// The amount of memory that the Agentless deployment will be initially allocated.
	Memory string `json:"memory,omitempty" yaml:"memory,omitempty"`
}

// AgentlessResources the computing resources specifications for the Agentless deployment.
type AgentlessResources struct {
	// The computing resources that the Agentless deployment will be initially allocated.
	Requests AgentlessResourceRequests `json:"requests,omitempty" yaml:"requests,omitempty"`
}

type ConfigurationLink struct {
	// Link description
	Content string `json:"content,omitempty" yaml:"content,omitempty"`
	// Link title
	Title string `json:"title" yaml:"title"`
	// Type of link. `next_steps` for links to locations that can be relevant right after configuring
	// the policy. `action` for actions that can be performed while the policy is in use.
	Type ConfigurationLinkType `json:"type" yaml:"type"`
	// Link url. Format is `http://...` or `https://...` for external links, `kbn:/app/...` for links
	// internal to Kibana.
	URL string `json:"url" yaml:"url"`
}

// ConfigurationLinkType type of link. `next_steps` for links to locations that can be relevant
// right after configuring the policy. `action` for actions that can be performed while the policy
// is in use.
type ConfigurationLinkType string

// Enum values for ConfigurationLinkType.
const (
	ConfigurationLinkTypeAction   ConfigurationLinkType = "action"
	ConfigurationLinkTypeNextStep ConfigurationLinkType = "next_step"
)

// DeploymentModes options related to the deployment modes. The deployment mode refers to the mode
// used to deploy the Elastic Agents running this policy.
type DeploymentModes struct {
	// Options specific to the Agentless deployment mode. This mode is used in offerings where the
	// Elastic Agents running these policies are fully managed for the user.
	Agentless DeploymentModesAgentless `json:"agentless,omitempty" yaml:"agentless,omitempty"`
	// Options specific to the default deployment mode, where agents are normally managed by users,
	// explicitly enrolled to Fleet and visible in UIs.
	Default DeploymentModesDefault `json:"default,omitempty" yaml:"default,omitempty"`
}

// DeploymentModesAgentless options specific to the Agentless deployment mode. This mode is used in
// offerings where the Elastic Agents running these policies are fully managed for the user.
type DeploymentModesAgentless struct {
	// The division responsible for the integration. This is used to tag the agentless agent deployments
	// for monitoring.
	Division string `json:"division,omitempty" yaml:"division,omitempty"`
	// Indicates if the agentless deployment mode is available for this template policy. It is disabled
	// by default.
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	// On policy templates that support multiple deployment modes, this setting can be set to true to
	// use agentless mode by default.
	IsDefault *bool `json:"is_default,omitempty" yaml:"is_default,omitempty"`
	// The responsible organization of the integration. This is used to tag the agentless agent
	// deployments for monitoring.
	Organization string `json:"organization,omitempty" yaml:"organization,omitempty"`
	// The computing resources specifications for the Agentless deployment.
	Resources AgentlessResources `json:"resources,omitempty" yaml:"resources,omitempty"`
	// The team responsible for the integration. This is used to tag the agentless agent deployments for
	// monitoring.
	Team string `json:"team,omitempty" yaml:"team,omitempty"`
}

// DeploymentModesDefault options specific to the default deployment mode, where agents are normally
// managed by users, explicitly enrolled to Fleet and visible in UIs.
type DeploymentModesDefault struct {
	// Indicates if the default deployment mode is available for this template policy. It is enabled by
	// default.
	Enabled              *bool          `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	AdditionalProperties map[string]any `json:"-" yaml:",inline"`
}

// MarshalJSON implements json.Marshaler for DeploymentModesDefault.
// It merges AdditionalProperties into the flat JSON output.
func (v DeploymentModesDefault) MarshalJSON() ([]byte, error) {
	type plainDeploymentModesDefault DeploymentModesDefault
	data, err := json.Marshal(plainDeploymentModesDefault(v))
	if err != nil {
		return nil, err
	}
	if len(v.AdditionalProperties) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	for k, val := range v.AdditionalProperties {
		if _, exists := m[k]; !exists {
			m[k] = val
		}
	}
	return json.Marshal(m)
}

type InputPolicyTemplate struct {
	// List of links related to inputs and policy templates.
	ConfigurationLinks []ConfigurationLink `json:"configuration_links,omitempty" yaml:"configuration_links,omitempty"`
	// Options related to the deployment modes. The deployment mode refers to the mode used to deploy
	// the Elastic Agents running this policy.
	DeploymentModes DeploymentModes `json:"deployment_modes,omitempty" yaml:"deployment_modes,omitempty"`
	// Information on deprecation of a package or an individual feature.
	Deprecated Deprecated `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	// Longer description of policy template.
	Description string `json:"description" yaml:"description"`
	// When enabled, decides the transforms and index templates that need to be created depending on the
	// pipelines specified in the configuration. This field is only allowed when the input type is
	// 'otelcol'.
	DynamicSignalTypes *bool `json:"dynamic_signal_types,omitempty" yaml:"dynamic_signal_types,omitempty"`
	// Indicate if this package is capable of satisfying FIPS requirements. Set to false if it uses any
	// input that cannot be configured to use FIPS cryptography.
	FipsCompatible *bool `json:"fips_compatible,omitempty" yaml:"fips_compatible,omitempty"`
	// List of icons for by this package.
	Icons []Icon `json:"icons,omitempty" yaml:"icons,omitempty"`
	Input string `json:"input" yaml:"input"`
	// Name of policy template.
	Name string `json:"name" yaml:"name"`
	// List of screenshots of Kibana assets created by this package.
	Screenshots []Screenshot `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	// Path of the config template.
	TemplatePath string `json:"template_path,omitempty" yaml:"template_path,omitempty"`
	// Paths of the config templates. Templates are rendered and merged sequentially; later templates
	// override earlier ones for conflicting keys.
	TemplatePaths []string `json:"template_paths,omitempty" yaml:"template_paths,omitempty"`
	// Title of policy template.
	Title string `json:"title" yaml:"title"`
	// Type of data stream
	Type InputPolicyTemplateType `json:"type,omitempty" yaml:"type,omitempty"`
	// Input variables.
	Vars []Var `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// InputPolicyTemplateType type of data stream
type InputPolicyTemplateType string

// Enum values for InputPolicyTemplateType.
const (
	InputPolicyTemplateTypeMetrics    InputPolicyTemplateType = "metrics"
	InputPolicyTemplateTypeLogs       InputPolicyTemplateType = "logs"
	InputPolicyTemplateTypeSynthetics InputPolicyTemplateType = "synthetics"
	InputPolicyTemplateTypeTraces     InputPolicyTemplateType = "traces"
	InputPolicyTemplateTypeProfiles   InputPolicyTemplateType = "profiles"
)

type PolicyTemplate struct {
	FileMetadata `json:"-" yaml:"-"`
	// Categories to which this package belongs.
	Categories []Category `json:"categories,omitempty" yaml:"categories,omitempty"`
	// List of links related to inputs and policy templates.
	ConfigurationLinks []ConfigurationLink `json:"configuration_links,omitempty" yaml:"configuration_links,omitempty"`
	// List of data streams compatible with the policy template.
	DataStreams []string `json:"data_streams,omitempty" yaml:"data_streams,omitempty"`
	// Options related to the deployment modes. The deployment mode refers to the mode used to deploy
	// the Elastic Agents running this policy.
	DeploymentModes DeploymentModes `json:"deployment_modes,omitempty" yaml:"deployment_modes,omitempty"`
	// Information on deprecation of a package or an individual feature.
	Deprecated Deprecated `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	// Longer description of policy template.
	Description string `json:"description" yaml:"description"`
	// Indicate if this package is capable of satisfying FIPS requirements. Set to false if it uses any
	// input that cannot be configured to use FIPS cryptography.
	FipsCompatible *bool `json:"fips_compatible,omitempty" yaml:"fips_compatible,omitempty"`
	// List of icons for by this package.
	Icons []Icon `json:"icons,omitempty" yaml:"icons,omitempty"`
	// List of inputs supported by policy template.
	Inputs   []PolicyTemplateInput `json:"inputs,omitempty" yaml:"inputs,omitempty"`
	Multiple *bool                 `json:"multiple,omitempty" yaml:"multiple,omitempty"`
	// Name of policy template.
	Name string `json:"name" yaml:"name"`
	// List of screenshots of Kibana assets created by this package.
	Screenshots []Screenshot `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	// Title of policy template.
	Title string `json:"title" yaml:"title"`
	// Input variables.
	Vars []Var `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PolicyTemplate.
// It captures the YAML node position for FileMetadata.
func (v *PolicyTemplate) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPolicyTemplate PolicyTemplate
	x := (*plainPolicyTemplate)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

type PolicyTemplateInput struct {
	// List of deployment modes that this input is compatible with. If not specified, the input is
	// compatible with all deployment modes.
	DeploymentModes []PolicyTemplateInputDeploymentMode `json:"deployment_modes,omitempty" yaml:"deployment_modes,omitempty"`
	// Information on deprecation of a package or an individual feature.
	Deprecated Deprecated `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	// Longer description of input.
	Description string `json:"description" yaml:"description"`
	// When enabled, decides the transforms and index templates that need to be created depending on the
	// pipelines specified in the configuration. This field is only allowed when the input type is
	// 'otelcol'.
	DynamicSignalTypes *bool `json:"dynamic_signal_types,omitempty" yaml:"dynamic_signal_types,omitempty"`
	// HideInVarGroupOptions filters out specific var_group options for this input.
	HideInVarGroupOptions map[string][]string `json:"hide_in_var_group_options,omitempty" yaml:"hide_in_var_group_options,omitempty"`
	// Name of the input group
	InputGroup PolicyTemplateInputGroup `json:"input_group,omitempty" yaml:"input_group,omitempty"`
	// Previous input type to migrate configuration from. This allows Fleet to automatically migrate the
	// policy configuration when replacing one input implementation with an equivalent one. This field
	// should only be used for inputs that don't need agent's state persistence.
	MigrateFrom string `json:"migrate_from,omitempty" yaml:"migrate_from,omitempty"`
	// Can input be defined multiple times
	Multi *bool `json:"multi,omitempty" yaml:"multi,omitempty"`
	// Reference to an input package. When specified, configuration is inherited from the referenced
	// package. The package must be listed in the manifest's requires section.
	Package string `json:"package,omitempty" yaml:"package,omitempty"`
	// Required conditional variables for the package.
	RequiredVars RequiredVars `json:"required_vars,omitempty" yaml:"required_vars,omitempty"`
	// Path of the config template.
	TemplatePath string `json:"template_path,omitempty" yaml:"template_path,omitempty"`
	// Paths of the config templates. Templates are rendered and merged sequentially; later templates
	// override earlier ones for conflicting keys.
	TemplatePaths []string `json:"template_paths,omitempty" yaml:"template_paths,omitempty"`
	// Title of input.
	Title string `json:"title" yaml:"title"`
	// Type of input.
	Type string `json:"type,omitempty" yaml:"type,omitempty"`
	// Input variables.
	Vars []Var `json:"vars,omitempty" yaml:"vars,omitempty"`
}

type PolicyTemplateInputDeploymentMode string

// Enum values for PolicyTemplateInputDeploymentMode.
const (
	PolicyTemplateInputDeploymentModeDefault   PolicyTemplateInputDeploymentMode = "default"
	PolicyTemplateInputDeploymentModeAgentless PolicyTemplateInputDeploymentMode = "agentless"
)

// PolicyTemplateInputGroup name of the input group
type PolicyTemplateInputGroup string

// Enum values for PolicyTemplateInputGroup.
const (
	PolicyTemplateInputGroupLogs    PolicyTemplateInputGroup = "logs"
	PolicyTemplateInputGroupMetrics PolicyTemplateInputGroup = "metrics"
)
