// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

// RoutingRule defines a single routing rule within a RoutingRuleSet (technical preview).
type RoutingRule struct {
	// Conditionally execute the processor
	If string `json:"if" yaml:"if"`
	// Namespace is the field reference or static value for the namespace part of the data stream name.
	Namespace StringOrStrings `json:"namespace,omitempty" yaml:"namespace,omitempty"`
	// TargetDataset is the field reference or static value for the dataset part of the data stream
	// name.
	TargetDataset StringOrStrings `json:"target_dataset" yaml:"target_dataset"`
}

// RoutingRuleSet represents a set of routing rules for rerouting documents from a source dataset.
// Routing rules are a technical preview feature.
type RoutingRuleSet struct {
	FileMetadata `json:"-" yaml:"-"`
	// List of routing rules
	Rules []RoutingRule `json:"rules" yaml:"rules"`
	// Source dataset to be used by this reroute processsor. If applicable, documents from this dataset
	// will be routed according to the rules defined.
	SourceDataset string `json:"source_dataset" yaml:"source_dataset"`
}

// UnmarshalYAML implements yaml.Unmarshaler for RoutingRuleSet.
// It captures the YAML node position for FileMetadata.
func (v *RoutingRuleSet) UnmarshalYAML(node *yamlv3.Node) error {
	type plainRoutingRuleSet RoutingRuleSet
	x := (*plainRoutingRuleSet)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}
