// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

// AgentPreStartScript optional: Custom sh script to be executed before starting the Elastic Agent
// process (e.g. export environment variables)
type AgentPreStartScript struct {
	// Code to run before starting the Elastic Agent.
	Contents string `json:"contents" yaml:"contents"`
	// Programming language of the pre-start script. Currently, only "sh" is supported.
	Language AgentPreStartScriptLanguage `json:"language,omitempty" yaml:"language,omitempty"`
}

// AgentPreStartScriptLanguage programming language of the pre-start script. Currently, only "sh" is
// supported.
type AgentPreStartScriptLanguage string

// Enum values for AgentPreStartScriptLanguage.
const (
	AgentPreStartScriptLanguageSh AgentPreStartScriptLanguage = "sh"
)

// AgentProvisioningScript optional: Script to run to customize the system where Elastic Agent runs
// (e.g. installing new libraries/dependencies)
type AgentProvisioningScript struct {
	// Code to run as a provisioning script.
	Contents string `json:"contents" yaml:"contents"`
	// Programming language of the provisioning script.
	Language string `json:"language,omitempty" yaml:"language,omitempty"`
}

// InputTestConfig holds the package-level test configuration for input packages
// (_dev/test/config.yml).
type InputTestConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Configuration for policy tests
	Policy TestCategoryConfig `json:"policy,omitempty" yaml:"policy,omitempty"`
	// Configuration for system tests
	System TestCategoryConfig `json:"system,omitempty" yaml:"system,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for InputTestConfig.
// It captures the YAML node position for FileMetadata.
func (v *InputTestConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainInputTestConfig InputTestConfig
	x := (*plainInputTestConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// PipelineTestCommonConfig holds shared configuration for all pipeline tests in a data stream
// (test-common-config.yml).
type PipelineTestCommonConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Dynamic fields with regular expressions defining their variable values.
	DynamicFields map[string]any `json:"dynamic_fields,omitempty" yaml:"dynamic_fields,omitempty"`
	// Field definitions
	Fields map[string]any `json:"fields,omitempty" yaml:"fields,omitempty"`
	// Multi-line configuration
	Multiline map[string]any `json:"multiline,omitempty" yaml:"multiline,omitempty"`
	// NumericKeywordFields lists keyword type fields allowed to have a numeric value.
	NumericKeywordFields []string `json:"numeric_keyword_fields,omitempty" yaml:"numeric_keyword_fields,omitempty"`
	Skip                 TestSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
	// StringNumberFields lists numeric type fields allowed to have a string value if parseable as a
	// number.
	StringNumberFields []string `json:"string_number_fields,omitempty" yaml:"string_number_fields,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PipelineTestCommonConfig.
// It captures the YAML node position for FileMetadata.
func (v *PipelineTestCommonConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPipelineTestCommonConfig PipelineTestCommonConfig
	x := (*plainPipelineTestCommonConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// PipelineTestEvent holds the input events for a JSON pipeline test (test-*.json).
type PipelineTestEvent struct {
	FileMetadata `json:"-" yaml:"-"`
	// Given events
	Events []map[string]any `json:"events" yaml:"events"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PipelineTestEvent.
// It captures the YAML node position for FileMetadata.
func (v *PipelineTestEvent) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPipelineTestEvent PipelineTestEvent
	x := (*plainPipelineTestEvent)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// PipelineTestExpected holds the expected output for a pipeline test (test-*-expected.json).
type PipelineTestExpected struct {
	FileMetadata `json:"-" yaml:"-"`
	// Expected test result
	Expected []any `json:"expected" yaml:"expected"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PipelineTestExpected.
// It captures the YAML node position for FileMetadata.
func (v *PipelineTestExpected) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPipelineTestExpected PipelineTestExpected
	x := (*plainPipelineTestExpected)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// PipelineTestJSONConfig holds per-case configuration for a JSON pipeline test
// (test-*.json-config.yml).
type PipelineTestJSONConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Dynamic fields with regular expressions defining their variable values.
	DynamicFields map[string]any `json:"dynamic_fields,omitempty" yaml:"dynamic_fields,omitempty"`
	// Field definitions
	Fields map[string]any `json:"fields,omitempty" yaml:"fields,omitempty"`
	// NumericKeywordFields lists keyword type fields allowed to have a numeric value.
	NumericKeywordFields []string `json:"numeric_keyword_fields,omitempty" yaml:"numeric_keyword_fields,omitempty"`
	Skip                 TestSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
	// StringNumberFields lists numeric type fields allowed to have a string value if parseable as a
	// number.
	StringNumberFields []string `json:"string_number_fields,omitempty" yaml:"string_number_fields,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PipelineTestJSONConfig.
// It captures the YAML node position for FileMetadata.
func (v *PipelineTestJSONConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPipelineTestJSONConfig PipelineTestJSONConfig
	x := (*plainPipelineTestJSONConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// PipelineTestRawConfig holds per-case configuration for a raw/log pipeline test
// (test-*.log-config.yml).
type PipelineTestRawConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Dynamic fields with regular expressions defining their variable values.
	DynamicFields map[string]any `json:"dynamic_fields,omitempty" yaml:"dynamic_fields,omitempty"`
	// Field definitions
	Fields map[string]any `json:"fields,omitempty" yaml:"fields,omitempty"`
	// Multi-line configuration
	Multiline map[string]any `json:"multiline,omitempty" yaml:"multiline,omitempty"`
	// NumericKeywordFields lists keyword type fields allowed to have a numeric value.
	NumericKeywordFields []string `json:"numeric_keyword_fields,omitempty" yaml:"numeric_keyword_fields,omitempty"`
	Skip                 TestSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
	// StringNumberFields lists numeric type fields allowed to have a string value if parseable as a
	// number.
	StringNumberFields []string `json:"string_number_fields,omitempty" yaml:"string_number_fields,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PipelineTestRawConfig.
// It captures the YAML node position for FileMetadata.
func (v *PipelineTestRawConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPipelineTestRawConfig PipelineTestRawConfig
	x := (*plainPipelineTestRawConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// PolicyTestConfig holds configuration for a policy test case (test-*.yml).
type PolicyTestConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Configuration for the data stream.
	DataStream *PolicyTestDataStream `json:"data_stream,omitempty" yaml:"data_stream,omitempty"`
	// The input of the package to test.
	Input string   `json:"input,omitempty" yaml:"input,omitempty"`
	Skip  TestSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
	// Variables used to configure settings defined in the package manifest.
	Vars TestVars `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for PolicyTestConfig.
// It captures the YAML node position for FileMetadata.
func (v *PolicyTestConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainPolicyTestConfig PolicyTestConfig
	x := (*plainPolicyTestConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

type PolicyTestDataStream struct {
	// Variables used to configure settings defined in the data stream manifest.
	Vars *TestVars `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// StaticTestConfig holds configuration for a static test case (test-*-config.yml).
type StaticTestConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	Skip         TestSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for StaticTestConfig.
// It captures the YAML node position for FileMetadata.
func (v *StaticTestConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainStaticTestConfig StaticTestConfig
	x := (*plainStaticTestConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// SystemTestAgent configuration overrides for the Elastic Agent
type SystemTestAgent struct {
	// Elastic Agent image to be used for testing. Setting `default` will be used the same Elastic Agent
	// image as the stack. Setting `systemd` will use the image containing all the binaries for running
	// Beats (collectors) based in an OS compatible with systemd. Setting `complete` will use the
	// "complete" image, that includes all supported collectors plus a web browser and the required
	// runtime for synthetic testing.
	BaseImage SystemTestAgentBaseImage `json:"base_image,omitempty" yaml:"base_image,omitempty"`
	// Linux Capabilities that must been enabled in the system to run the Elastic Agent process
	LinuxCapabilities []SystemTestAgentLinuxCapability `json:"linux_capabilities,omitempty" yaml:"linux_capabilities,omitempty"`
	// Control access to PID namespaces. When set to `host`, the Elastic Agent will have access to the
	// PID namespace of the host.
	PidMode SystemTestAgentPidMode `json:"pid_mode,omitempty" yaml:"pid_mode,omitempty"`
	// List of ports to be exposed to access to the Elastic Agent
	Ports []string `json:"ports,omitempty" yaml:"ports,omitempty"`
	// Optional: Custom sh script to be executed before starting the Elastic Agent process (e.g. export
	// environment variables)
	PreStartScript AgentPreStartScript `json:"pre_start_script,omitempty" yaml:"pre_start_script,omitempty"`
	// Optional: Script to run to customize the system where Elastic Agent runs (e.g. installing new
	// libraries/dependencies)
	ProvisioningScript AgentProvisioningScript `json:"provisioning_script,omitempty" yaml:"provisioning_script,omitempty"`
	// Runtime to run the Elastic Agent process
	Runtime SystemTestAgentRuntime `json:"runtime,omitempty" yaml:"runtime,omitempty"`
	// User that runs the Elastic Agent process
	User string `json:"user,omitempty" yaml:"user,omitempty"`
}

// SystemTestAgentBaseImage elastic Agent image to be used for testing. Setting `default` will be
// used the same Elastic Agent image as the stack. Setting `systemd` will use the image containing
// all the binaries for running Beats (collectors) based in an OS compatible with systemd. Setting
// `complete` will use the "complete" image, that includes all supported collectors plus a web
// browser and the required runtime for synthetic testing.
type SystemTestAgentBaseImage string

// Enum values for SystemTestAgentBaseImage.
const (
	SystemTestAgentBaseImageDefault  SystemTestAgentBaseImage = "default"
	SystemTestAgentBaseImageComplete SystemTestAgentBaseImage = "complete"
	SystemTestAgentBaseImageSystemd  SystemTestAgentBaseImage = "systemd"
)

// SystemTestAgentLinuxCapability capability name
type SystemTestAgentLinuxCapability string

// Enum values for SystemTestAgentLinuxCapability.
const (
	SystemTestAgentLinuxCapabilityAuditControl      SystemTestAgentLinuxCapability = "AUDIT_CONTROL"
	SystemTestAgentLinuxCapabilityAuditRead         SystemTestAgentLinuxCapability = "AUDIT_READ"
	SystemTestAgentLinuxCapabilityAuditWrite        SystemTestAgentLinuxCapability = "AUDIT_WRITE"
	SystemTestAgentLinuxCapabilityBlockSuspend      SystemTestAgentLinuxCapability = "BLOCK_SUSPEND"
	SystemTestAgentLinuxCapabilityBpf               SystemTestAgentLinuxCapability = "BPF"
	SystemTestAgentLinuxCapabilityCheckpointRestore SystemTestAgentLinuxCapability = "CHECKPOINT_RESTORE"
	SystemTestAgentLinuxCapabilityChown             SystemTestAgentLinuxCapability = "CHOWN"
	SystemTestAgentLinuxCapabilityDacOverride       SystemTestAgentLinuxCapability = "DAC_OVERRIDE"
	SystemTestAgentLinuxCapabilityDacReadSearch     SystemTestAgentLinuxCapability = "DAC_READ_SEARCH"
	SystemTestAgentLinuxCapabilityFowner            SystemTestAgentLinuxCapability = "FOWNER"
	SystemTestAgentLinuxCapabilityFsetid            SystemTestAgentLinuxCapability = "FSETID"
	SystemTestAgentLinuxCapabilityIpcLock           SystemTestAgentLinuxCapability = "IPC_LOCK"
	SystemTestAgentLinuxCapabilityIpcOwner          SystemTestAgentLinuxCapability = "IPC_OWNER"
	SystemTestAgentLinuxCapabilityKill              SystemTestAgentLinuxCapability = "KILL"
	SystemTestAgentLinuxCapabilityLease             SystemTestAgentLinuxCapability = "LEASE"
	SystemTestAgentLinuxCapabilityLinuxImmutable    SystemTestAgentLinuxCapability = "LINUX_IMMUTABLE"
	SystemTestAgentLinuxCapabilityMacAdmin          SystemTestAgentLinuxCapability = "MAC_ADMIN"
	SystemTestAgentLinuxCapabilityMacOverride       SystemTestAgentLinuxCapability = "MAC_OVERRIDE"
	SystemTestAgentLinuxCapabilityMknod             SystemTestAgentLinuxCapability = "MKNOD"
	SystemTestAgentLinuxCapabilityNetAdmin          SystemTestAgentLinuxCapability = "NET_ADMIN"
	SystemTestAgentLinuxCapabilityNetBindService    SystemTestAgentLinuxCapability = "NET_BIND_SERVICE"
	SystemTestAgentLinuxCapabilityNetBroadcast      SystemTestAgentLinuxCapability = "NET_BROADCAST"
	SystemTestAgentLinuxCapabilityNetRaw            SystemTestAgentLinuxCapability = "NET_RAW"
	SystemTestAgentLinuxCapabilityPerform           SystemTestAgentLinuxCapability = "PERFORM"
	SystemTestAgentLinuxCapabilitySetfcap           SystemTestAgentLinuxCapability = "SETFCAP"
	SystemTestAgentLinuxCapabilitySetgid            SystemTestAgentLinuxCapability = "SETGID"
	SystemTestAgentLinuxCapabilitySetpcap           SystemTestAgentLinuxCapability = "SETPCAP"
	SystemTestAgentLinuxCapabilitySetuid            SystemTestAgentLinuxCapability = "SETUID"
	SystemTestAgentLinuxCapabilitySysAdmin          SystemTestAgentLinuxCapability = "SYS_ADMIN"
	SystemTestAgentLinuxCapabilitySysBoot           SystemTestAgentLinuxCapability = "SYS_BOOT"
	SystemTestAgentLinuxCapabilitySysChroot         SystemTestAgentLinuxCapability = "SYS_CHROOT"
	SystemTestAgentLinuxCapabilitySysModule         SystemTestAgentLinuxCapability = "SYS_MODULE"
	SystemTestAgentLinuxCapabilitySysNice           SystemTestAgentLinuxCapability = "SYS_NICE"
	SystemTestAgentLinuxCapabilitySysPacct          SystemTestAgentLinuxCapability = "SYS_PACCT"
	SystemTestAgentLinuxCapabilitySysPtrace         SystemTestAgentLinuxCapability = "SYS_PTRACE"
	SystemTestAgentLinuxCapabilitySysRawio          SystemTestAgentLinuxCapability = "SYS_RAWIO"
	SystemTestAgentLinuxCapabilitySysResource       SystemTestAgentLinuxCapability = "SYS_RESOURCE"
	SystemTestAgentLinuxCapabilitySysTime           SystemTestAgentLinuxCapability = "SYS_TIME"
	SystemTestAgentLinuxCapabilitySysTtyConfig      SystemTestAgentLinuxCapability = "SYS_TTY_CONFIG"
	SystemTestAgentLinuxCapabilitySyslog            SystemTestAgentLinuxCapability = "SYSLOG"
	SystemTestAgentLinuxCapabilityWakeAlarm         SystemTestAgentLinuxCapability = "WAKE_ALARM"
)

// SystemTestAgentPidMode control access to PID namespaces. When set to `host`, the Elastic Agent
// will have access to the PID namespace of the host.
type SystemTestAgentPidMode string

// Enum values for SystemTestAgentPidMode.
const (
	SystemTestAgentPidModeHost SystemTestAgentPidMode = "host"
)

// SystemTestAgentRuntime runtime to run the Elastic Agent process
type SystemTestAgentRuntime string

// Enum values for SystemTestAgentRuntime.
const (
	SystemTestAgentRuntimeDocker SystemTestAgentRuntime = "docker"
)

// SystemTestConfig holds configuration for a system test case (test-*-config.yml).
type SystemTestConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Configuration overrides for the Elastic Agent
	Agent      SystemTestAgent       `json:"agent,omitempty" yaml:"agent,omitempty"`
	DataStream *SystemTestDataStream `json:"data_stream,omitempty" yaml:"data_stream,omitempty"`
	Skip       TestSkip              `json:"skip,omitempty" yaml:"skip,omitempty"`
	// If listed here, elastic-package system tests will not fail if values for the specified field
	// names can't be indexed for any incoming documents. This should only be used if the failure is
	// related to the test environment and wouldn't happen in production. Mitigate the issue via mapping
	// or pipeline changes otherwise.
	SkipIgnoredFields []string `json:"skip_ignored_fields,omitempty" yaml:"skip_ignored_fields,omitempty"`
	// Variables used to configure settings defined in the package manifest.
	Vars TestVars `json:"vars,omitempty" yaml:"vars,omitempty"`
	// Timeout for waiting for metrics data during a system test.
	WaitForDataTimeout string `json:"wait_for_data_timeout,omitempty" yaml:"wait_for_data_timeout,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for SystemTestConfig.
// It captures the YAML node position for FileMetadata.
func (v *SystemTestConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainSystemTestConfig SystemTestConfig
	x := (*plainSystemTestConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

type SystemTestDataStream struct {
	// Variables used to configure settings defined in the data stream manifest.
	Vars TestVars `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// TestCategoryConfig controls parallelism and skip for a test category.
type TestCategoryConfig struct {
	// Tests defined can be run in parallel (default true).
	Parallel *bool    `json:"parallel,omitempty" yaml:"parallel,omitempty"`
	Skip     TestSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
}

// TestConfig holds the package-level test configuration for integration packages
// (_dev/test/config.yml).
type TestConfig struct {
	FileMetadata `json:"-" yaml:"-"`
	// Configuration for asset tests
	Asset TestCategoryConfig `json:"asset,omitempty" yaml:"asset,omitempty"`
	// Configuration for pipeline tests
	Pipeline TestCategoryConfig `json:"pipeline,omitempty" yaml:"pipeline,omitempty"`
	// Configuration for policy tests
	Policy TestCategoryConfig `json:"policy,omitempty" yaml:"policy,omitempty"`
	// Configuration for static tests
	Static TestCategoryConfig `json:"static,omitempty" yaml:"static,omitempty"`
	// Configuration for system tests
	System TestCategoryConfig `json:"system,omitempty" yaml:"system,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for TestConfig.
// It captures the YAML node position for FileMetadata.
func (v *TestConfig) UnmarshalYAML(node *yamlv3.Node) error {
	type plainTestConfig TestConfig
	x := (*plainTestConfig)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// TestSkip describes why a test should be skipped, with a reason and tracking link.
type TestSkip struct {
	// Link to issue with more details about skipped test or to track re-enabling skipped test.
	Link string `json:"link" yaml:"link"`
	// Short explanation for why test has been skipped.
	Reason string `json:"reason" yaml:"reason"`
}

// TestVars holds variables defined for a test case.
type TestVars struct {
	DataStreamDataset string `json:"data_stream.dataset,omitempty" yaml:"data_stream.dataset,omitempty"`
}
