// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

// Deployer name of the service deployer to setup for this system benchmark.
type Deployer string

// Enum values for Deployer.
const (
	DeployerDocker Deployer = "docker"
	DeployerTf     Deployer = "tf"
	DeployerK8s    Deployer = "k8s"
)

// DeploymentModesAgentlessRelease the maturity level of the agentless deployment mode for this
// policy template. If not defined, Kibana will provide a default value based on agentless platform
// maturity. Packages where agentless is the only deployment mode, should defer to the package's
// top-level `version`. Only evaluated in Kibana 9.5.0 or later.
type DeploymentModesAgentlessRelease string

// Enum values for DeploymentModesAgentlessRelease.
const (
	DeploymentModesAgentlessReleaseBeta DeploymentModesAgentlessRelease = "beta"
	DeploymentModesAgentlessReleaseGa   DeploymentModesAgentlessRelease = "ga"
)

// PackageDependency A package dependency with name and version.
type PackageDependency struct {
	// Name of the required package.
	Package string `json:"package" yaml:"package"`
	// Version of the required package. For input packages, it is recommended to use specific versions
	// (e.g., "1.0.0") for consistency. For content packages, version constraints (e.g., "^1.0.0") can
	// be used to allow compatible updates.
	Version string `json:"version" yaml:"version"`
}

// PolicyAPIFormat tests can create policies using the Fleet APIs with different formats. The
// "legacy" format requires to send variables with hints about their type, and defaults are not
// managed automatically.
//
// The newer, "simplified" format has better format support for variables and don't allow to include
// hints, it also uses defaults automatically, and requires explicit enablement or disablement of
// inputs and streams.
//
// In most cases tests should not set this value. The main use case is to set it to "legacy" for
// cases that cannot be fully supported with the newer "simplified" format.
type PolicyAPIFormat string

// Enum values for PolicyAPIFormat.
const (
	PolicyAPIFormatLegacy     PolicyAPIFormat = "legacy"
	PolicyAPIFormatSimplified PolicyAPIFormat = "simplified"
)

type ProviderPermission struct {
	// Human-readable description of why these permissions are needed.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Individual permission grants required by this integration unit.
	Permissions []ProviderPermissionPermission `json:"permissions,omitempty" yaml:"permissions,omitempty"`
	// Identifier of the provider these permissions apply to.
	Provider string `json:"provider" yaml:"provider"`
	// Pre-defined roles or managed policies to attach alongside inline permissions.
	Roles []ProviderPermissionRole `json:"roles,omitempty" yaml:"roles,omitempty"`
}

type ProviderPermissionPermission struct {
	// Human-readable description of why this permission is needed.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Provider-specific permission or action name.
	Name string `json:"name" yaml:"name"`
}

type ProviderPermissionRole struct {
	// Human-readable description of this role.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Provider-specific identifier for this role or managed policy.
	ID string `json:"id,omitempty" yaml:"id,omitempty"`
	// Display name of the role or managed policy.
	Name string `json:"name" yaml:"name"`
}

// Requires dependencies that this package requires to function properly.
type Requires struct {
	// List of required content packages.
	Content []PackageDependency `json:"content,omitempty" yaml:"content,omitempty"`
	// List of required input packages.
	Input []PackageDependency `json:"input,omitempty" yaml:"input,omitempty"`
}

type Section struct {
	// Optional help text displayed below the section header.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Unique identifier for this section.
	Name string `json:"name" yaml:"name"`
	// Display title for this section header in the Fleet UI.
	Title string `json:"title" yaml:"title"`
}

type SystemTestConfigSample struct {
	// Condition to filter documents used for the sample event.
	Condition SystemTestConfigSampleCondition `json:"condition,omitempty" yaml:"condition,omitempty"`
	// Name identifying the sample event file to use. Corresponds to the suffix in
	// `sample_event_<name>.json`.
	Name string `json:"name" yaml:"name"`
}

// SystemTestConfigSampleCondition condition to filter documents used for the sample event.
type SystemTestConfigSampleCondition struct {
	// Field name to check in the document.
	Key string `json:"key" yaml:"key"`
	// Expected value of the field.
	Value string `json:"value,omitempty" yaml:"value,omitempty"`
}

// VarMigrateFrom declares that this variable was previously named differently or defined at a
// different scope. Fleet carries the old value over when upgrading a policy. At least one of `name`
// or `scope` must be set. Both may be set together when the variable was both renamed and moved
// between scopes.
type VarMigrateFrom struct {
	// Previous name of the variable. Use when the variable was renamed between package versions.
	// Combine with `scope` if the variable was also moved to a different scope.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
	// The scope where this variable previously lived. Use when the variable moved between input-level
	// and stream-level within the same input type.
	Scope VarMigrateFromScope `json:"scope,omitempty" yaml:"scope,omitempty"`
	// The source stream to pull the old value from. May be written as the data stream folder name (e.g.
	// `logs`) or the fully-qualified dataset (e.g. `mypackage.logs`); both forms are accepted. Required
	// when `scope` is "stream" and the source input has more than one stream. May be omitted when the
	// source input has exactly one stream. Has no effect when `scope` is "input".
	Stream string `json:"stream,omitempty" yaml:"stream,omitempty"`
}

// VarMigrateFromScope the scope where this variable previously lived. Use when the variable moved
// between input-level and stream-level within the same input type.
type VarMigrateFromScope string

// Enum values for VarMigrateFromScope.
const (
	VarMigrateFromScopeInput  VarMigrateFromScope = "input"
	VarMigrateFromScopeStream VarMigrateFromScope = "stream"
)
