// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

// Deployer name of the service deployer to setup for this system benchmark.
type Deployer string

// Enum values for Deployer.
const (
	DeployerDocker Deployer = "docker"
	DeployerTf     Deployer = "tf"
	DeployerK8s    Deployer = "k8s"
)

// DeploymentModesAgentlessRelease the maturity level of the agentless deployment mode for this
// policy template. If not defined, Kibana will provide a default value based on agentless platform
// maturity. Packages where agentless is the only deployment mode, should defer to the package's
// top-level `version`. Only evaluated in Kibana 9.5.0 or later.
type DeploymentModesAgentlessRelease string

// Enum values for DeploymentModesAgentlessRelease.
const (
	DeploymentModesAgentlessReleaseBeta DeploymentModesAgentlessRelease = "beta"
	DeploymentModesAgentlessReleaseGa   DeploymentModesAgentlessRelease = "ga"
)

// PackageDependency A package dependency with name and version.
type PackageDependency struct {
	// Name of the required package.
	Package string `json:"package" yaml:"package"`
	// Version of the required package. For input packages, it is recommended to use specific versions
	// (e.g., "1.0.0") for consistency. For content packages, version constraints (e.g., "^1.0.0") can
	// be used to allow compatible updates.
	Version string `json:"version" yaml:"version"`
}

// PolicyAPIFormat tests can create policies using the Fleet APIs with different formats. The
// "legacy" format requires to send variables with hints about their type, and defaults are not
// managed automatically.
//
// The newer, "simplified" format has better format support for variables and don't allow to include
// hints, it also uses defaults automatically, and requires explicit enablement or disablement of
// inputs and streams.
//
// In most cases tests should not set this value. The main use case is to set it to "legacy" for
// cases that cannot be fully supported with the newer "simplified" format.
type PolicyAPIFormat string

// Enum values for PolicyAPIFormat.
const (
	PolicyAPIFormatLegacy     PolicyAPIFormat = "legacy"
	PolicyAPIFormatSimplified PolicyAPIFormat = "simplified"
)

// Requires dependencies that this package requires to function properly.
type Requires struct {
	// List of required content packages.
	Content []PackageDependency `json:"content,omitempty" yaml:"content,omitempty"`
	// List of required input packages.
	Input []PackageDependency `json:"input,omitempty" yaml:"input,omitempty"`
}

type Section struct {
	// Optional help text displayed below the section header.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Unique identifier for this section.
	Name string `json:"name" yaml:"name"`
	// Display title for this section header in the Fleet UI.
	Title string `json:"title" yaml:"title"`
}

type SystemTestConfigSample struct {
	// Condition to filter documents used for the sample event.
	Condition SystemTestConfigSampleCondition `json:"condition,omitempty" yaml:"condition,omitempty"`
	// Name identifying the sample event file to use. Corresponds to the suffix in
	// `sample_event_<name>.json`.
	Name string `json:"name" yaml:"name"`
}

// SystemTestConfigSampleCondition condition to filter documents used for the sample event.
type SystemTestConfigSampleCondition struct {
	// Field name to check in the document.
	Key string `json:"key" yaml:"key"`
	// Expected value of the field.
	Value string `json:"value,omitempty" yaml:"value,omitempty"`
}
