// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

// Deployer name of the service deployer to setup for this system benchmark.
type Deployer string

// Enum values for Deployer.
const (
	DeployerDocker Deployer = "docker"
	DeployerTf     Deployer = "tf"
	DeployerK8s    Deployer = "k8s"
)

// PackageDependency A package dependency with name and version.
type PackageDependency struct {
	// Name of the required package.
	Package string `json:"package" yaml:"package"`
	// Version of the required package. For input packages, it is recommended to use specific versions
	// (e.g., "1.0.0") for consistency. For content packages, version constraints (e.g., "^1.0.0") can
	// be used to allow compatible updates.
	Version string `json:"version" yaml:"version"`
}

// PolicyAPIFormat tests can create policies using the Fleet APIs with different formats. The
// "legacy" format requires to send variables with hints about their type, and defaults are not
// managed automatically.
//
// The newer, "simplified" format has better format support for variables and don't allow to include
// hints, it also uses defaults automatically, and requires explicit enablement or disablement of
// inputs and streams.
//
// In most cases tests should not set this value. The main use case is to set it to "legacy" for
// cases that cannot be fully supported with the newer "simplified" format.
type PolicyAPIFormat string

// Enum values for PolicyAPIFormat.
const (
	PolicyAPIFormatLegacy     PolicyAPIFormat = "legacy"
	PolicyAPIFormatSimplified PolicyAPIFormat = "simplified"
)

// Requires dependencies that this package requires to function properly.
type Requires struct {
	// List of required content packages.
	Content []PackageDependency `json:"content,omitempty" yaml:"content,omitempty"`
	// List of required input packages.
	Input []PackageDependency `json:"input,omitempty" yaml:"input,omitempty"`
}
