// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import yamlv3 "gopkg.in/yaml.v3"

type Validation struct {
	FileMetadata `json:"-" yaml:"-"`
	// DocsStructureEnforced rules to manage the documentation structure
	DocsStructureEnforced ValidationDocsStructure `json:"docs_structure_enforced,omitempty" yaml:"docs_structure_enforced,omitempty"`
	// Errors rules to manage the validation results
	Errors ValidationErrors `json:"errors,omitempty" yaml:"errors,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Validation.
// It captures the YAML node position for FileMetadata.
func (v *Validation) UnmarshalYAML(node *yamlv3.Node) error {
	type plainValidation Validation
	x := (*plainValidation)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// ValidationDocsStructure rules to manage the documentation structure
type ValidationDocsStructure struct {
	// Enabled whether the documentation structure is enforced
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	// Skip list of sections to skip in the documentation validation
	Skip []ValidationDocsStructureSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
	// Version of the documentation structure
	Version int `json:"version,omitempty" yaml:"version,omitempty"`
}

type ValidationDocsStructureSkip struct {
	Reason string `json:"reason,omitempty" yaml:"reason,omitempty"`
	Title  string `json:"title,omitempty" yaml:"title,omitempty"`
}

// ValidationErrors rules to manage the validation results
type ValidationErrors struct {
	// ExcludeChecks list of validation codes that will be skipped
	ExcludeChecks []string `json:"exclude_checks,omitempty" yaml:"exclude_checks,omitempty"`
}
