// Code generated by cmd/generate; DO NOT EDIT.

package pkgspec

import (
	"encoding/json"
	yamlv3 "gopkg.in/yaml.v3"
)

type Validation struct {
	FileMetadata `json:"-" yaml:"-"`
	// Rules to manage the documentation structure
	DocsStructureEnforced ValidationDocsStructure `json:"docs_structure_enforced,omitempty" yaml:"docs_structure_enforced,omitempty"`
	// Rules to manage the validation results
	Errors ValidationErrors `json:"errors,omitempty" yaml:"errors,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Validation.
// It captures the YAML node position for FileMetadata.
func (v *Validation) UnmarshalYAML(node *yamlv3.Node) error {
	type plainValidation Validation
	x := (*plainValidation)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// ValidationDocsStructure rules to manage the documentation structure
type ValidationDocsStructure struct {
	// Whether the documentation structure is enforced
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	// List of sections to skip in the documentation validation
	Skip []ValidationDocsStructureSkip `json:"skip,omitempty" yaml:"skip,omitempty"`
	// Version of the documentation structure
	Version int `json:"version,omitempty" yaml:"version,omitempty"`
}

type ValidationDocsStructureSkip struct {
	Reason               string         `json:"reason,omitempty" yaml:"reason,omitempty"`
	Title                string         `json:"title,omitempty" yaml:"title,omitempty"`
	AdditionalProperties map[string]any `json:"-" yaml:",inline"`
}

// MarshalJSON implements json.Marshaler for ValidationDocsStructureSkip.
// It merges AdditionalProperties into the flat JSON output.
func (v ValidationDocsStructureSkip) MarshalJSON() ([]byte, error) {
	type plainValidationDocsStructureSkip ValidationDocsStructureSkip
	data, err := json.Marshal(plainValidationDocsStructureSkip(v))
	if err != nil {
		return nil, err
	}
	if len(v.AdditionalProperties) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	for k, val := range v.AdditionalProperties {
		if _, exists := m[k]; !exists {
			m[k] = val
		}
	}
	return json.Marshal(m)
}

// ValidationErrors rules to manage the validation results
type ValidationErrors struct {
	// List of validation codes that will be skipped
	ExcludeChecks []string `json:"exclude_checks,omitempty" yaml:"exclude_checks,omitempty"`
}
