// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type BuildManifest struct {
	ID                            int64
	PackagesID                    int64
	FilePath                      sql.NullString
	FileLine                      sql.NullInt64
	FileColumn                    sql.NullInt64
	DependenciesEcsImportMappings sql.NullBool
	DependenciesEcsReference      string
}

type Changelog struct {
	ID         int64
	PackagesID int64
	FilePath   sql.NullString
	FileLine   sql.NullInt64
	FileColumn sql.NullInt64
	Version    string
	Date       sql.NullString
}

type ChangelogEntry struct {
	ID           int64
	ChangelogsID int64
	FilePath     sql.NullString
	FileLine     sql.NullInt64
	FileColumn   sql.NullInt64
	Description  string
	Link         string
	Type         string
}

type DataStream struct {
	ID                            int64
	PackagesID                    int64
	DirName                       string
	FilePath                      sql.NullString
	FileLine                      sql.NullInt64
	FileColumn                    sql.NullInt64
	Dataset                       sql.NullString
	DatasetIsPrefix               sql.NullBool
	ElasticsearchDynamicDataset   sql.NullBool
	ElasticsearchDynamicNamespace sql.NullBool
	ElasticsearchIndexMode        sql.NullString
	ElasticsearchIndexTemplate    interface{}
	ElasticsearchPrivileges       interface{}
	ElasticsearchSourceMode       sql.NullString
	Hidden                        sql.NullBool
	IlmPolicy                     sql.NullString
	Release                       sql.NullString
	Title                         string
	Type                          sql.NullString
}

type DataStreamField struct {
	ID           int64
	DataStreamID int64
	FieldID      int64
}

type Deprecation struct {
	ID                       int64
	DataStreamsID            sql.NullInt64
	Description              string
	PackagesID               sql.NullInt64
	PolicyTemplateInputsID   sql.NullInt64
	PolicyTemplatesID        sql.NullInt64
	ReplacedByDataStream     sql.NullString
	ReplacedByInput          sql.NullString
	ReplacedByPackage        sql.NullString
	ReplacedByPolicyTemplate sql.NullString
	ReplacedByVariable       sql.NullString
	Since                    string
	VarsID                   sql.NullInt64
}

type DiscoveryField struct {
	ID         int64
	Name       string
	PackagesID int64
}

type Doc struct {
	ID          int64
	Content     sql.NullString
	ContentType string
	FilePath    string
	PackagesID  int64
}

type Field struct {
	ID                    int64
	FilePath              sql.NullString
	FileLine              sql.NullInt64
	FileColumn            sql.NullInt64
	Analyzer              sql.NullString
	CopyTo                sql.NullString
	DateFormat            sql.NullString
	DefaultMetric         interface{}
	Description           sql.NullString
	Dimension             sql.NullBool
	DocValues             sql.NullBool
	Dynamic               interface{}
	Enabled               sql.NullBool
	Example               interface{}
	ExpectedValues        interface{}
	External              sql.NullString
	IgnoreAbove           sql.NullInt64
	IgnoreMalformed       sql.NullBool
	IncludeInParent       sql.NullBool
	IncludeInRoot         sql.NullBool
	Index                 sql.NullBool
	InferenceID           sql.NullString
	MetricType            sql.NullString
	Metrics               interface{}
	MultiFields           interface{}
	Name                  string
	Normalize             interface{}
	Normalizer            sql.NullString
	NullValue             interface{}
	ObjectType            sql.NullString
	ObjectTypeMappingType sql.NullString
	Path                  sql.NullString
	Pattern               sql.NullString
	Runtime               interface{}
	ScalingFactor         sql.NullInt64
	SearchAnalyzer        sql.NullString
	Store                 sql.NullBool
	Subobjects            sql.NullBool
	Type                  sql.NullString
	Unit                  sql.NullString
	Value                 sql.NullString
	JsonPointer           sql.NullString
}

type Image struct {
	ID         int64
	ByteSize   int64
	Height     sql.NullInt64
	PackagesID int64
	Sha256     string
	Src        string
	Width      sql.NullInt64
}

type IngestPipeline struct {
	ID            int64
	DataStreamsID int64
	FileName      string
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	Description   sql.NullString
}

type IngestProcessor struct {
	ID                int64
	IngestPipelinesID int64
	Attributes        interface{}
	JsonPointer       string
	Ordinal           int64
	Type              string
	FilePath          sql.NullString
	FileLine          sql.NullInt64
	FileColumn        sql.NullInt64
}

type Package struct {
	ID                             int64
	AgentPrivilegesRoot            sql.NullBool
	ConditionsElasticSubscription  sql.NullString
	ConditionsKibanaVersion        sql.NullString
	DirName                        string
	ElasticsearchPrivilegesCluster interface{}
	PolicyTemplatesBehavior        sql.NullString
	FilePath                       sql.NullString
	FileLine                       sql.NullInt64
	FileColumn                     sql.NullInt64
	Description                    string
	FormatVersion                  string
	Name                           string
	OwnerGithub                    string
	OwnerType                      string
	SourceLicense                  sql.NullString
	Title                          string
	Type                           string
	Version                        string
}

type PackageCategory struct {
	ID        int64
	Category  string
	PackageID int64
}

type PackageField struct {
	ID        int64
	FieldID   int64
	PackageID int64
}

type PackageIcon struct {
	ID         int64
	PackagesID int64
	DarkMode   sql.NullBool
	Size       sql.NullString
	Src        string
	Title      sql.NullString
	Type       sql.NullString
}

type PackageScreenshot struct {
	ID         int64
	PackagesID int64
	Size       sql.NullString
	Src        string
	Title      string
	Type       sql.NullString
}

type PackageVar struct {
	ID        int64
	PackageID int64
	VarID     int64
}

type PipelineTest struct {
	ID                   int64
	ConfigPath           sql.NullString
	DataStreamsID        int64
	DynamicFields        interface{}
	EventPath            string
	ExpectedPath         sql.NullString
	Fields               interface{}
	Format               string
	Multiline            interface{}
	Name                 string
	NumericKeywordFields interface{}
	SkipLink             sql.NullString
	SkipReason           sql.NullString
	StringNumberFields   interface{}
}

type PolicyTemplate struct {
	ID                                              int64
	PackagesID                                      int64
	FilePath                                        sql.NullString
	FileLine                                        sql.NullInt64
	FileColumn                                      sql.NullInt64
	ConfigurationLinks                              interface{}
	DataStreams                                     interface{}
	DeploymentModesAgentlessDivision                sql.NullString
	DeploymentModesAgentlessEnabled                 sql.NullBool
	DeploymentModesAgentlessIsDefault               sql.NullBool
	DeploymentModesAgentlessOrganization            sql.NullString
	DeploymentModesAgentlessResourcesRequestsCpu    sql.NullString
	DeploymentModesAgentlessResourcesRequestsMemory sql.NullString
	DeploymentModesAgentlessTeam                    sql.NullString
	DeploymentModesDefaultEnabled                   sql.NullBool
	Description                                     string
	FipsCompatible                                  sql.NullBool
	Multiple                                        sql.NullBool
	Name                                            string
	Title                                           string
}

type PolicyTemplateCategory struct {
	ID               int64
	Category         string
	PolicyTemplateID int64
}

type PolicyTemplateIcon struct {
	ID                int64
	PolicyTemplatesID int64
	DarkMode          sql.NullBool
	Size              sql.NullString
	Src               string
	Title             sql.NullString
	Type              sql.NullString
}

type PolicyTemplateInput struct {
	ID                    int64
	PolicyTemplatesID     int64
	DeploymentModes       interface{}
	Description           string
	HideInVarGroupOptions interface{}
	InputGroup            sql.NullString
	Multi                 sql.NullBool
	TemplatePath          sql.NullString
	Title                 string
	Type                  string
}

type PolicyTemplateInputVar struct {
	ID                    int64
	PolicyTemplateInputID int64
	VarID                 int64
}

type PolicyTemplateScreenshot struct {
	ID                int64
	PolicyTemplatesID int64
	Size              sql.NullString
	Src               string
	Title             string
	Type              sql.NullString
}

type PolicyTemplateVar struct {
	ID               int64
	PolicyTemplateID int64
	VarID            int64
}

type PolicyTest struct {
	ID            int64
	CaseName      string
	DataStreamsID sql.NullInt64
	PackagesID    sql.NullInt64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	DataStream    interface{}
	Input         sql.NullString
	SkipLink      string
	SkipReason    string
	Vars          interface{}
}

type RoutingRule struct {
	ID            int64
	DataStreamsID int64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	If            string
	Namespace     interface{}
	TargetDataset interface{}
}

type SampleEvent struct {
	ID            int64
	DataStreamsID int64
	Event         interface{}
}

type StaticTest struct {
	ID            int64
	CaseName      string
	DataStreamsID int64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	SkipLink      string
	SkipReason    string
}

type Stream struct {
	ID            int64
	DataStreamsID int64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	Description   string
	Enabled       sql.NullBool
	Input         string
	TemplatePath  sql.NullString
	Title         string
}

type StreamVar struct {
	ID       int64
	StreamID int64
	VarID    int64
}

type SystemTest struct {
	ID                              int64
	CaseName                        string
	DataStreamsID                   sql.NullInt64
	PackagesID                      sql.NullInt64
	FilePath                        sql.NullString
	FileLine                        sql.NullInt64
	FileColumn                      sql.NullInt64
	AgentBaseImage                  sql.NullString
	AgentLinuxCapabilities          interface{}
	AgentPidMode                    sql.NullString
	AgentPorts                      interface{}
	AgentPreStartScriptContents     string
	AgentPreStartScriptLanguage     sql.NullString
	AgentProvisioningScriptContents string
	AgentProvisioningScriptLanguage sql.NullString
	AgentRuntime                    sql.NullString
	AgentUser                       sql.NullString
	DataStream                      interface{}
	SkipLink                        string
	SkipReason                      string
	SkipIgnoredFields               interface{}
	Vars                            interface{}
	WaitForDataTimeout              sql.NullString
}

type Tag struct {
	ID         int64
	PackagesID int64
	FilePath   sql.NullString
	FileLine   sql.NullInt64
	FileColumn sql.NullInt64
	AssetIds   interface{}
	AssetTypes interface{}
	Text       sql.NullString
}

type Transform struct {
	ID                               int64
	PackagesID                       int64
	DirName                          string
	ManifestDestinationIndexTemplate interface{}
	ManifestStart                    sql.NullBool
	FilePath                         sql.NullString
	FileLine                         sql.NullInt64
	FileColumn                       sql.NullInt64
	Meta                             interface{}
	Description                      sql.NullString
	Dest                             interface{}
	Frequency                        sql.NullString
	Latest                           interface{}
	Pivot                            interface{}
	RetentionPolicy                  interface{}
	Settings                         interface{}
	Source                           interface{}
	Sync                             interface{}
}

type TransformField struct {
	ID          int64
	FieldID     int64
	TransformID int64
}

type Var struct {
	ID                    int64
	FilePath              sql.NullString
	FileLine              sql.NullInt64
	FileColumn            sql.NullInt64
	Default               interface{}
	Description           sql.NullString
	HideInDeploymentModes interface{}
	MaxDuration           sql.NullString
	MinDuration           sql.NullString
	Multi                 sql.NullBool
	Name                  string
	Options               interface{}
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	Title                 sql.NullString
	Type                  string
	UrlAllowedSchemes     interface{}
}
