// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const insertBuildManifests = `-- name: InsertBuildManifests :one
INSERT INTO build_manifests (
  packages_id,
  file_path,
  file_line,
  file_column,
  dependencies_ecs_import_mappings,
  dependencies_ecs_reference
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertBuildManifestsParams struct {
	PackagesID                    int64
	FilePath                      sql.NullString
	FileLine                      sql.NullInt64
	FileColumn                    sql.NullInt64
	DependenciesEcsImportMappings sql.NullBool
	DependenciesEcsReference      string
}

func (q *Queries) InsertBuildManifests(ctx context.Context, arg InsertBuildManifestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBuildManifests,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.DependenciesEcsImportMappings,
		arg.DependenciesEcsReference,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelogEntries = `-- name: InsertChangelogEntries :one
INSERT INTO changelog_entries (
  changelogs_id,
  file_path,
  file_line,
  file_column,
  description,
  link,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertChangelogEntriesParams struct {
	ChangelogsID int64
	FilePath     sql.NullString
	FileLine     sql.NullInt64
	FileColumn   sql.NullInt64
	Description  string
	Link         string
	Type         string
}

func (q *Queries) InsertChangelogEntries(ctx context.Context, arg InsertChangelogEntriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelogEntries,
		arg.ChangelogsID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Description,
		arg.Link,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelogs = `-- name: InsertChangelogs :one
INSERT INTO changelogs (
  packages_id,
  file_path,
  file_line,
  file_column,
  version,
  date
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertChangelogsParams struct {
	PackagesID int64
	FilePath   sql.NullString
	FileLine   sql.NullInt64
	FileColumn sql.NullInt64
	Version    string
	Date       sql.NullString
}

func (q *Queries) InsertChangelogs(ctx context.Context, arg InsertChangelogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelogs,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Version,
		arg.Date,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreamFields = `-- name: InsertDataStreamFields :one
INSERT INTO data_stream_fields (
  data_stream_id,
  field_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertDataStreamFieldsParams struct {
	DataStreamID int64
	FieldID      int64
}

func (q *Queries) InsertDataStreamFields(ctx context.Context, arg InsertDataStreamFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStreamFields, arg.DataStreamID, arg.FieldID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreams = `-- name: InsertDataStreams :one
INSERT INTO data_streams (
  packages_id,
  dir_name,
  file_path,
  file_line,
  file_column,
  dataset,
  dataset_is_prefix,
  elasticsearch_dynamic_dataset,
  elasticsearch_dynamic_namespace,
  elasticsearch_index_mode,
  elasticsearch_index_template,
  elasticsearch_privileges,
  elasticsearch_source_mode,
  hidden,
  ilm_policy,
  "release",
  title,
  type,
  github_owner
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertDataStreamsParams struct {
	PackagesID                    int64
	DirName                       string
	FilePath                      sql.NullString
	FileLine                      sql.NullInt64
	FileColumn                    sql.NullInt64
	Dataset                       sql.NullString
	DatasetIsPrefix               sql.NullBool
	ElasticsearchDynamicDataset   sql.NullBool
	ElasticsearchDynamicNamespace sql.NullBool
	ElasticsearchIndexMode        sql.NullString
	ElasticsearchIndexTemplate    interface{}
	ElasticsearchPrivileges       interface{}
	ElasticsearchSourceMode       sql.NullString
	Hidden                        sql.NullBool
	IlmPolicy                     sql.NullString
	Release                       sql.NullString
	Title                         string
	Type                          sql.NullString
	GithubOwner                   sql.NullString
}

func (q *Queries) InsertDataStreams(ctx context.Context, arg InsertDataStreamsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStreams,
		arg.PackagesID,
		arg.DirName,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Dataset,
		arg.DatasetIsPrefix,
		arg.ElasticsearchDynamicDataset,
		arg.ElasticsearchDynamicNamespace,
		arg.ElasticsearchIndexMode,
		arg.ElasticsearchIndexTemplate,
		arg.ElasticsearchPrivileges,
		arg.ElasticsearchSourceMode,
		arg.Hidden,
		arg.IlmPolicy,
		arg.Release,
		arg.Title,
		arg.Type,
		arg.GithubOwner,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDeprecations = `-- name: InsertDeprecations :one
INSERT INTO deprecations (
  data_streams_id,
  description,
  packages_id,
  policy_template_inputs_id,
  policy_templates_id,
  replaced_by_data_stream,
  replaced_by_input,
  replaced_by_package,
  replaced_by_policy_template,
  replaced_by_variable,
  since,
  vars_id
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertDeprecationsParams struct {
	DataStreamsID            sql.NullInt64
	Description              string
	PackagesID               sql.NullInt64
	PolicyTemplateInputsID   sql.NullInt64
	PolicyTemplatesID        sql.NullInt64
	ReplacedByDataStream     sql.NullString
	ReplacedByInput          sql.NullString
	ReplacedByPackage        sql.NullString
	ReplacedByPolicyTemplate sql.NullString
	ReplacedByVariable       sql.NullString
	Since                    string
	VarsID                   sql.NullInt64
}

func (q *Queries) InsertDeprecations(ctx context.Context, arg InsertDeprecationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDeprecations,
		arg.DataStreamsID,
		arg.Description,
		arg.PackagesID,
		arg.PolicyTemplateInputsID,
		arg.PolicyTemplatesID,
		arg.ReplacedByDataStream,
		arg.ReplacedByInput,
		arg.ReplacedByPackage,
		arg.ReplacedByPolicyTemplate,
		arg.ReplacedByVariable,
		arg.Since,
		arg.VarsID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDiscoveryFields = `-- name: InsertDiscoveryFields :one
INSERT INTO discovery_fields (
  name,
  packages_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertDiscoveryFieldsParams struct {
	Name       string
	PackagesID int64
}

func (q *Queries) InsertDiscoveryFields(ctx context.Context, arg InsertDiscoveryFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDiscoveryFields, arg.Name, arg.PackagesID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDocs = `-- name: InsertDocs :one
INSERT INTO docs (
  content,
  content_type,
  file_path,
  packages_id
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertDocsParams struct {
	Content     sql.NullString
	ContentType string
	FilePath    string
	PackagesID  int64
}

func (q *Queries) InsertDocs(ctx context.Context, arg InsertDocsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDocs,
		arg.Content,
		arg.ContentType,
		arg.FilePath,
		arg.PackagesID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFields = `-- name: InsertFields :one
INSERT INTO fields (
  file_path,
  file_line,
  file_column,
  analyzer,
  copy_to,
  date_format,
  default_metric,
  description,
  dimension,
  doc_values,
  dynamic,
  enabled,
  example,
  expected_values,
  external,
  ignore_above,
  ignore_malformed,
  include_in_parent,
  include_in_root,
  "index",
  inference_id,
  metric_type,
  metrics,
  multi_fields,
  name,
  normalize,
  normalizer,
  null_value,
  object_type,
  object_type_mapping_type,
  path,
  pattern,
  runtime,
  scaling_factor,
  search_analyzer,
  store,
  subobjects,
  type,
  unit,
  value,
  json_pointer
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertFieldsParams struct {
	FilePath              sql.NullString
	FileLine              sql.NullInt64
	FileColumn            sql.NullInt64
	Analyzer              sql.NullString
	CopyTo                sql.NullString
	DateFormat            sql.NullString
	DefaultMetric         interface{}
	Description           sql.NullString
	Dimension             sql.NullBool
	DocValues             sql.NullBool
	Dynamic               interface{}
	Enabled               sql.NullBool
	Example               interface{}
	ExpectedValues        interface{}
	External              sql.NullString
	IgnoreAbove           sql.NullInt64
	IgnoreMalformed       sql.NullBool
	IncludeInParent       sql.NullBool
	IncludeInRoot         sql.NullBool
	Index                 sql.NullBool
	InferenceID           sql.NullString
	MetricType            sql.NullString
	Metrics               interface{}
	MultiFields           interface{}
	Name                  string
	Normalize             interface{}
	Normalizer            sql.NullString
	NullValue             interface{}
	ObjectType            sql.NullString
	ObjectTypeMappingType sql.NullString
	Path                  sql.NullString
	Pattern               sql.NullString
	Runtime               interface{}
	ScalingFactor         sql.NullInt64
	SearchAnalyzer        sql.NullString
	Store                 sql.NullBool
	Subobjects            sql.NullBool
	Type                  sql.NullString
	Unit                  sql.NullString
	Value                 sql.NullString
	JsonPointer           sql.NullString
}

func (q *Queries) InsertFields(ctx context.Context, arg InsertFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFields,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Analyzer,
		arg.CopyTo,
		arg.DateFormat,
		arg.DefaultMetric,
		arg.Description,
		arg.Dimension,
		arg.DocValues,
		arg.Dynamic,
		arg.Enabled,
		arg.Example,
		arg.ExpectedValues,
		arg.External,
		arg.IgnoreAbove,
		arg.IgnoreMalformed,
		arg.IncludeInParent,
		arg.IncludeInRoot,
		arg.Index,
		arg.InferenceID,
		arg.MetricType,
		arg.Metrics,
		arg.MultiFields,
		arg.Name,
		arg.Normalize,
		arg.Normalizer,
		arg.NullValue,
		arg.ObjectType,
		arg.ObjectTypeMappingType,
		arg.Path,
		arg.Pattern,
		arg.Runtime,
		arg.ScalingFactor,
		arg.SearchAnalyzer,
		arg.Store,
		arg.Subobjects,
		arg.Type,
		arg.Unit,
		arg.Value,
		arg.JsonPointer,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImages = `-- name: InsertImages :one
INSERT INTO images (
  byte_size,
  height,
  packages_id,
  sha256,
  src,
  width
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertImagesParams struct {
	ByteSize   int64
	Height     sql.NullInt64
	PackagesID int64
	Sha256     string
	Src        string
	Width      sql.NullInt64
}

func (q *Queries) InsertImages(ctx context.Context, arg InsertImagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertImages,
		arg.ByteSize,
		arg.Height,
		arg.PackagesID,
		arg.Sha256,
		arg.Src,
		arg.Width,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestPipelines = `-- name: InsertIngestPipelines :one
INSERT INTO ingest_pipelines (
  data_streams_id,
  file_name,
  file_path,
  file_line,
  file_column,
  description
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertIngestPipelinesParams struct {
	DataStreamsID int64
	FileName      string
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	Description   sql.NullString
}

func (q *Queries) InsertIngestPipelines(ctx context.Context, arg InsertIngestPipelinesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestPipelines,
		arg.DataStreamsID,
		arg.FileName,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestProcessors = `-- name: InsertIngestProcessors :one
INSERT INTO ingest_processors (
  ingest_pipelines_id,
  attributes,
  json_pointer,
  ordinal,
  type,
  file_path,
  file_line,
  file_column
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertIngestProcessorsParams struct {
	IngestPipelinesID int64
	Attributes        interface{}
	JsonPointer       string
	Ordinal           int64
	Type              string
	FilePath          sql.NullString
	FileLine          sql.NullInt64
	FileColumn        sql.NullInt64
}

func (q *Queries) InsertIngestProcessors(ctx context.Context, arg InsertIngestProcessorsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestProcessors,
		arg.IngestPipelinesID,
		arg.Attributes,
		arg.JsonPointer,
		arg.Ordinal,
		arg.Type,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertKibanaReferences = `-- name: InsertKibanaReferences :one
INSERT INTO kibana_references (
  kibana_saved_objects_id,
  ref_id,
  ref_name,
  ref_type
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertKibanaReferencesParams struct {
	KibanaSavedObjectsID int64
	RefID                string
	RefName              string
	RefType              string
}

func (q *Queries) InsertKibanaReferences(ctx context.Context, arg InsertKibanaReferencesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertKibanaReferences,
		arg.KibanaSavedObjectsID,
		arg.RefID,
		arg.RefName,
		arg.RefType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertKibanaSavedObjects = `-- name: InsertKibanaSavedObjects :one
INSERT INTO kibana_saved_objects (
  asset_type,
  core_migration_version,
  description,
  file_path,
  managed,
  object_id,
  object_type,
  packages_id,
  reference_count,
  title,
  type_migration_version
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertKibanaSavedObjectsParams struct {
	AssetType            string
	CoreMigrationVersion sql.NullString
	Description          sql.NullString
	FilePath             string
	Managed              sql.NullBool
	ObjectID             string
	ObjectType           sql.NullString
	PackagesID           int64
	ReferenceCount       int64
	Title                sql.NullString
	TypeMigrationVersion sql.NullString
}

func (q *Queries) InsertKibanaSavedObjects(ctx context.Context, arg InsertKibanaSavedObjectsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertKibanaSavedObjects,
		arg.AssetType,
		arg.CoreMigrationVersion,
		arg.Description,
		arg.FilePath,
		arg.Managed,
		arg.ObjectID,
		arg.ObjectType,
		arg.PackagesID,
		arg.ReferenceCount,
		arg.Title,
		arg.TypeMigrationVersion,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageCategories = `-- name: InsertPackageCategories :one
INSERT INTO package_categories (
  category,
  package_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageCategoriesParams struct {
	Category  string
	PackageID int64
}

func (q *Queries) InsertPackageCategories(ctx context.Context, arg InsertPackageCategoriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageCategories, arg.Category, arg.PackageID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageFields = `-- name: InsertPackageFields :one
INSERT INTO package_fields (
  field_id,
  package_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageFieldsParams struct {
	FieldID   int64
	PackageID int64
}

func (q *Queries) InsertPackageFields(ctx context.Context, arg InsertPackageFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageFields, arg.FieldID, arg.PackageID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageIcons = `-- name: InsertPackageIcons :one
INSERT INTO package_icons (
  packages_id,
  dark_mode,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackageIconsParams struct {
	PackagesID int64
	DarkMode   sql.NullBool
	Size       sql.NullString
	Src        string
	Title      sql.NullString
	Type       sql.NullString
}

func (q *Queries) InsertPackageIcons(ctx context.Context, arg InsertPackageIconsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageIcons,
		arg.PackagesID,
		arg.DarkMode,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageScreenshots = `-- name: InsertPackageScreenshots :one
INSERT INTO package_screenshots (
  packages_id,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackageScreenshotsParams struct {
	PackagesID int64
	Size       sql.NullString
	Src        string
	Title      string
	Type       sql.NullString
}

func (q *Queries) InsertPackageScreenshots(ctx context.Context, arg InsertPackageScreenshotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageScreenshots,
		arg.PackagesID,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageVars = `-- name: InsertPackageVars :one
INSERT INTO package_vars (
  package_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageVarsParams struct {
	PackageID int64
	VarID     int64
}

func (q *Queries) InsertPackageVars(ctx context.Context, arg InsertPackageVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageVars, arg.PackageID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackages = `-- name: InsertPackages :one
INSERT INTO packages (
  agent_privileges_root,
  commit_id,
  conditions_elastic_subscription,
  conditions_kibana_version,
  dir_name,
  elasticsearch_privileges_cluster,
  policy_templates_behavior,
  file_path,
  file_line,
  file_column,
  description,
  format_version,
  name,
  owner_github,
  owner_type,
  source_license,
  title,
  type,
  version
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackagesParams struct {
	AgentPrivilegesRoot            sql.NullBool
	CommitID                       sql.NullString
	ConditionsElasticSubscription  sql.NullString
	ConditionsKibanaVersion        sql.NullString
	DirName                        string
	ElasticsearchPrivilegesCluster interface{}
	PolicyTemplatesBehavior        sql.NullString
	FilePath                       sql.NullString
	FileLine                       sql.NullInt64
	FileColumn                     sql.NullInt64
	Description                    string
	FormatVersion                  string
	Name                           string
	OwnerGithub                    string
	OwnerType                      string
	SourceLicense                  sql.NullString
	Title                          string
	Type                           string
	Version                        string
}

func (q *Queries) InsertPackages(ctx context.Context, arg InsertPackagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackages,
		arg.AgentPrivilegesRoot,
		arg.CommitID,
		arg.ConditionsElasticSubscription,
		arg.ConditionsKibanaVersion,
		arg.DirName,
		arg.ElasticsearchPrivilegesCluster,
		arg.PolicyTemplatesBehavior,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Description,
		arg.FormatVersion,
		arg.Name,
		arg.OwnerGithub,
		arg.OwnerType,
		arg.SourceLicense,
		arg.Title,
		arg.Type,
		arg.Version,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPipelineTests = `-- name: InsertPipelineTests :one
INSERT INTO pipeline_tests (
  config_path,
  data_streams_id,
  dynamic_fields,
  event_path,
  expected_path,
  fields,
  format,
  multiline,
  name,
  numeric_keyword_fields,
  skip_link,
  skip_reason,
  string_number_fields
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPipelineTestsParams struct {
	ConfigPath           sql.NullString
	DataStreamsID        int64
	DynamicFields        interface{}
	EventPath            string
	ExpectedPath         sql.NullString
	Fields               interface{}
	Format               string
	Multiline            interface{}
	Name                 string
	NumericKeywordFields interface{}
	SkipLink             sql.NullString
	SkipReason           sql.NullString
	StringNumberFields   interface{}
}

func (q *Queries) InsertPipelineTests(ctx context.Context, arg InsertPipelineTestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPipelineTests,
		arg.ConfigPath,
		arg.DataStreamsID,
		arg.DynamicFields,
		arg.EventPath,
		arg.ExpectedPath,
		arg.Fields,
		arg.Format,
		arg.Multiline,
		arg.Name,
		arg.NumericKeywordFields,
		arg.SkipLink,
		arg.SkipReason,
		arg.StringNumberFields,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateCategories = `-- name: InsertPolicyTemplateCategories :one
INSERT INTO policy_template_categories (
  category,
  policy_template_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateCategoriesParams struct {
	Category         string
	PolicyTemplateID int64
}

func (q *Queries) InsertPolicyTemplateCategories(ctx context.Context, arg InsertPolicyTemplateCategoriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateCategories, arg.Category, arg.PolicyTemplateID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateIcons = `-- name: InsertPolicyTemplateIcons :one
INSERT INTO policy_template_icons (
  policy_templates_id,
  dark_mode,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateIconsParams struct {
	PolicyTemplatesID int64
	DarkMode          sql.NullBool
	Size              sql.NullString
	Src               string
	Title             sql.NullString
	Type              sql.NullString
}

func (q *Queries) InsertPolicyTemplateIcons(ctx context.Context, arg InsertPolicyTemplateIconsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateIcons,
		arg.PolicyTemplatesID,
		arg.DarkMode,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputVars = `-- name: InsertPolicyTemplateInputVars :one
INSERT INTO policy_template_input_vars (
  policy_template_input_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateInputVarsParams struct {
	PolicyTemplateInputID int64
	VarID                 int64
}

func (q *Queries) InsertPolicyTemplateInputVars(ctx context.Context, arg InsertPolicyTemplateInputVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInputVars, arg.PolicyTemplateInputID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputs = `-- name: InsertPolicyTemplateInputs :one
INSERT INTO policy_template_inputs (
  policy_templates_id,
  deployment_modes,
  description,
  hide_in_var_group_options,
  input_group,
  multi,
  template_path,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateInputsParams struct {
	PolicyTemplatesID     int64
	DeploymentModes       interface{}
	Description           string
	HideInVarGroupOptions interface{}
	InputGroup            sql.NullString
	Multi                 sql.NullBool
	TemplatePath          sql.NullString
	Title                 string
	Type                  string
}

func (q *Queries) InsertPolicyTemplateInputs(ctx context.Context, arg InsertPolicyTemplateInputsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInputs,
		arg.PolicyTemplatesID,
		arg.DeploymentModes,
		arg.Description,
		arg.HideInVarGroupOptions,
		arg.InputGroup,
		arg.Multi,
		arg.TemplatePath,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateScreenshots = `-- name: InsertPolicyTemplateScreenshots :one
INSERT INTO policy_template_screenshots (
  policy_templates_id,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateScreenshotsParams struct {
	PolicyTemplatesID int64
	Size              sql.NullString
	Src               string
	Title             string
	Type              sql.NullString
}

func (q *Queries) InsertPolicyTemplateScreenshots(ctx context.Context, arg InsertPolicyTemplateScreenshotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateScreenshots,
		arg.PolicyTemplatesID,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateVars = `-- name: InsertPolicyTemplateVars :one
INSERT INTO policy_template_vars (
  policy_template_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateVarsParams struct {
	PolicyTemplateID int64
	VarID            int64
}

func (q *Queries) InsertPolicyTemplateVars(ctx context.Context, arg InsertPolicyTemplateVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateVars, arg.PolicyTemplateID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplates = `-- name: InsertPolicyTemplates :one
INSERT INTO policy_templates (
  packages_id,
  dynamic_signal_types,
  input,
  policy_template_type,
  template_path,
  file_path,
  file_line,
  file_column,
  configuration_links,
  data_streams,
  deployment_modes_agentless_division,
  deployment_modes_agentless_enabled,
  deployment_modes_agentless_is_default,
  deployment_modes_agentless_organization,
  deployment_modes_agentless_resources_requests_cpu,
  deployment_modes_agentless_resources_requests_memory,
  deployment_modes_agentless_team,
  deployment_modes_default_enabled,
  description,
  fips_compatible,
  multiple,
  name,
  title
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplatesParams struct {
	PackagesID                                      int64
	DynamicSignalTypes                              sql.NullBool
	Input                                           sql.NullString
	PolicyTemplateType                              sql.NullString
	TemplatePath                                    sql.NullString
	FilePath                                        sql.NullString
	FileLine                                        sql.NullInt64
	FileColumn                                      sql.NullInt64
	ConfigurationLinks                              interface{}
	DataStreams                                     interface{}
	DeploymentModesAgentlessDivision                sql.NullString
	DeploymentModesAgentlessEnabled                 sql.NullBool
	DeploymentModesAgentlessIsDefault               sql.NullBool
	DeploymentModesAgentlessOrganization            sql.NullString
	DeploymentModesAgentlessResourcesRequestsCpu    sql.NullString
	DeploymentModesAgentlessResourcesRequestsMemory sql.NullString
	DeploymentModesAgentlessTeam                    sql.NullString
	DeploymentModesDefaultEnabled                   sql.NullBool
	Description                                     string
	FipsCompatible                                  sql.NullBool
	Multiple                                        sql.NullBool
	Name                                            string
	Title                                           string
}

func (q *Queries) InsertPolicyTemplates(ctx context.Context, arg InsertPolicyTemplatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplates,
		arg.PackagesID,
		arg.DynamicSignalTypes,
		arg.Input,
		arg.PolicyTemplateType,
		arg.TemplatePath,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.ConfigurationLinks,
		arg.DataStreams,
		arg.DeploymentModesAgentlessDivision,
		arg.DeploymentModesAgentlessEnabled,
		arg.DeploymentModesAgentlessIsDefault,
		arg.DeploymentModesAgentlessOrganization,
		arg.DeploymentModesAgentlessResourcesRequestsCpu,
		arg.DeploymentModesAgentlessResourcesRequestsMemory,
		arg.DeploymentModesAgentlessTeam,
		arg.DeploymentModesDefaultEnabled,
		arg.Description,
		arg.FipsCompatible,
		arg.Multiple,
		arg.Name,
		arg.Title,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTests = `-- name: InsertPolicyTests :one
INSERT INTO policy_tests (
  case_name,
  data_streams_id,
  packages_id,
  file_path,
  file_line,
  file_column,
  data_stream,
  input,
  skip_link,
  skip_reason,
  vars
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTestsParams struct {
	CaseName      string
	DataStreamsID sql.NullInt64
	PackagesID    sql.NullInt64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	DataStream    interface{}
	Input         sql.NullString
	SkipLink      string
	SkipReason    string
	Vars          interface{}
}

func (q *Queries) InsertPolicyTests(ctx context.Context, arg InsertPolicyTestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTests,
		arg.CaseName,
		arg.DataStreamsID,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.DataStream,
		arg.Input,
		arg.SkipLink,
		arg.SkipReason,
		arg.Vars,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRoutingRules = `-- name: InsertRoutingRules :one
INSERT INTO routing_rules (
  data_streams_id,
  file_path,
  file_line,
  file_column,
  "if",
  namespace,
  target_dataset
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertRoutingRulesParams struct {
	DataStreamsID int64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	If            string
	Namespace     interface{}
	TargetDataset interface{}
}

func (q *Queries) InsertRoutingRules(ctx context.Context, arg InsertRoutingRulesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRoutingRules,
		arg.DataStreamsID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.If,
		arg.Namespace,
		arg.TargetDataset,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSampleEvents = `-- name: InsertSampleEvents :one
INSERT INTO sample_events (
  data_streams_id,
  event
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertSampleEventsParams struct {
	DataStreamsID int64
	Event         interface{}
}

func (q *Queries) InsertSampleEvents(ctx context.Context, arg InsertSampleEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSampleEvents, arg.DataStreamsID, arg.Event)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStaticTests = `-- name: InsertStaticTests :one
INSERT INTO static_tests (
  case_name,
  data_streams_id,
  file_path,
  file_line,
  file_column,
  skip_link,
  skip_reason
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertStaticTestsParams struct {
	CaseName      string
	DataStreamsID int64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	SkipLink      string
	SkipReason    string
}

func (q *Queries) InsertStaticTests(ctx context.Context, arg InsertStaticTestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStaticTests,
		arg.CaseName,
		arg.DataStreamsID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.SkipLink,
		arg.SkipReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreamVars = `-- name: InsertStreamVars :one
INSERT INTO stream_vars (
  stream_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertStreamVarsParams struct {
	StreamID int64
	VarID    int64
}

func (q *Queries) InsertStreamVars(ctx context.Context, arg InsertStreamVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStreamVars, arg.StreamID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreams = `-- name: InsertStreams :one
INSERT INTO streams (
  data_streams_id,
  file_path,
  file_line,
  file_column,
  description,
  enabled,
  input,
  template_path,
  title
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertStreamsParams struct {
	DataStreamsID int64
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	Description   string
	Enabled       sql.NullBool
	Input         string
	TemplatePath  sql.NullString
	Title         string
}

func (q *Queries) InsertStreams(ctx context.Context, arg InsertStreamsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStreams,
		arg.DataStreamsID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Description,
		arg.Enabled,
		arg.Input,
		arg.TemplatePath,
		arg.Title,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSystemTests = `-- name: InsertSystemTests :one
INSERT INTO system_tests (
  case_name,
  data_streams_id,
  packages_id,
  file_path,
  file_line,
  file_column,
  agent_base_image,
  agent_linux_capabilities,
  agent_pid_mode,
  agent_ports,
  agent_pre_start_script_contents,
  agent_pre_start_script_language,
  agent_provisioning_script_contents,
  agent_provisioning_script_language,
  agent_runtime,
  agent_user,
  data_stream,
  skip_link,
  skip_reason,
  skip_ignored_fields,
  vars,
  wait_for_data_timeout
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertSystemTestsParams struct {
	CaseName                        string
	DataStreamsID                   sql.NullInt64
	PackagesID                      sql.NullInt64
	FilePath                        sql.NullString
	FileLine                        sql.NullInt64
	FileColumn                      sql.NullInt64
	AgentBaseImage                  sql.NullString
	AgentLinuxCapabilities          interface{}
	AgentPidMode                    sql.NullString
	AgentPorts                      interface{}
	AgentPreStartScriptContents     string
	AgentPreStartScriptLanguage     sql.NullString
	AgentProvisioningScriptContents string
	AgentProvisioningScriptLanguage sql.NullString
	AgentRuntime                    sql.NullString
	AgentUser                       sql.NullString
	DataStream                      interface{}
	SkipLink                        string
	SkipReason                      string
	SkipIgnoredFields               interface{}
	Vars                            interface{}
	WaitForDataTimeout              sql.NullString
}

func (q *Queries) InsertSystemTests(ctx context.Context, arg InsertSystemTestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSystemTests,
		arg.CaseName,
		arg.DataStreamsID,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.AgentBaseImage,
		arg.AgentLinuxCapabilities,
		arg.AgentPidMode,
		arg.AgentPorts,
		arg.AgentPreStartScriptContents,
		arg.AgentPreStartScriptLanguage,
		arg.AgentProvisioningScriptContents,
		arg.AgentProvisioningScriptLanguage,
		arg.AgentRuntime,
		arg.AgentUser,
		arg.DataStream,
		arg.SkipLink,
		arg.SkipReason,
		arg.SkipIgnoredFields,
		arg.Vars,
		arg.WaitForDataTimeout,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTags = `-- name: InsertTags :one
INSERT INTO tags (
  packages_id,
  file_path,
  file_line,
  file_column,
  asset_ids,
  asset_types,
  text
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertTagsParams struct {
	PackagesID int64
	FilePath   sql.NullString
	FileLine   sql.NullInt64
	FileColumn sql.NullInt64
	AssetIds   interface{}
	AssetTypes interface{}
	Text       sql.NullString
}

func (q *Queries) InsertTags(ctx context.Context, arg InsertTagsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTags,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.AssetIds,
		arg.AssetTypes,
		arg.Text,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransformFields = `-- name: InsertTransformFields :one
INSERT INTO transform_fields (
  field_id,
  transform_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertTransformFieldsParams struct {
	FieldID     int64
	TransformID int64
}

func (q *Queries) InsertTransformFields(ctx context.Context, arg InsertTransformFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransformFields, arg.FieldID, arg.TransformID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransforms = `-- name: InsertTransforms :one
INSERT INTO transforms (
  packages_id,
  dir_name,
  manifest_destination_index_template,
  manifest_start,
  file_path,
  file_line,
  file_column,
  meta,
  description,
  dest,
  frequency,
  latest,
  pivot,
  retention_policy,
  settings,
  source,
  sync
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertTransformsParams struct {
	PackagesID                       int64
	DirName                          string
	ManifestDestinationIndexTemplate interface{}
	ManifestStart                    sql.NullBool
	FilePath                         sql.NullString
	FileLine                         sql.NullInt64
	FileColumn                       sql.NullInt64
	Meta                             interface{}
	Description                      sql.NullString
	Dest                             interface{}
	Frequency                        sql.NullString
	Latest                           interface{}
	Pivot                            interface{}
	RetentionPolicy                  interface{}
	Settings                         interface{}
	Source                           interface{}
	Sync                             interface{}
}

func (q *Queries) InsertTransforms(ctx context.Context, arg InsertTransformsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransforms,
		arg.PackagesID,
		arg.DirName,
		arg.ManifestDestinationIndexTemplate,
		arg.ManifestStart,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Meta,
		arg.Description,
		arg.Dest,
		arg.Frequency,
		arg.Latest,
		arg.Pivot,
		arg.RetentionPolicy,
		arg.Settings,
		arg.Source,
		arg.Sync,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertVars = `-- name: InsertVars :one
INSERT INTO vars (
  file_path,
  file_line,
  file_column,
  "default",
  description,
  hide_in_deployment_modes,
  max_duration,
  min_duration,
  multi,
  name,
  options,
  required,
  secret,
  show_user,
  title,
  type,
  url_allowed_schemes
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertVarsParams struct {
	FilePath              sql.NullString
	FileLine              sql.NullInt64
	FileColumn            sql.NullInt64
	Default               interface{}
	Description           sql.NullString
	HideInDeploymentModes interface{}
	MaxDuration           sql.NullString
	MinDuration           sql.NullString
	Multi                 sql.NullBool
	Name                  string
	Options               interface{}
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	Title                 sql.NullString
	Type                  string
	UrlAllowedSchemes     interface{}
}

func (q *Queries) InsertVars(ctx context.Context, arg InsertVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertVars,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Default,
		arg.Description,
		arg.HideInDeploymentModes,
		arg.MaxDuration,
		arg.MinDuration,
		arg.Multi,
		arg.Name,
		arg.Options,
		arg.Required,
		arg.Secret,
		arg.ShowUser,
		arg.Title,
		arg.Type,
		arg.UrlAllowedSchemes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
