// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

import (
	yamlv3 "gopkg.in/yaml.v3"
	"time"
)

type Changelog struct {
	FileMetadata `json:"-" yaml:"-"`
	Changes      []ChangelogChange `json:"changes,omitempty" yaml:"changes,omitempty"`
	Version      string            `json:"version,omitempty" yaml:"version,omitempty"`
	Date         *time.Time        `json:"date,omitempty" yaml:"-"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Changelog.
// It captures the YAML node position for FileMetadata.
func (v *Changelog) UnmarshalYAML(node *yamlv3.Node) error {
	type plainChangelog Changelog
	x := (*plainChangelog)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

type ChangelogChange struct {
	Description string              `json:"description,omitempty" yaml:"description,omitempty"`
	Link        string              `json:"link,omitempty" yaml:"link,omitempty"`
	Type        ChangelogChangeType `json:"type,omitempty" yaml:"type,omitempty"`
}

// ChangelogChangeType type of change.
type ChangelogChangeType string

// Enum values for ChangelogChangeType.
const (
	ChangelogChangeTypeBreakingChange ChangelogChangeType = "breaking-change"
	ChangelogChangeTypeBugfix         ChangelogChangeType = "bugfix"
	ChangelogChangeTypeEnhancement    ChangelogChangeType = "enhancement"
	ChangelogChangeTypeDeprecation    ChangelogChangeType = "deprecation"
)
