// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

import yamlv3 "gopkg.in/yaml.v3"

type DataStreamManifest struct {
	FileMetadata    `json:"-" yaml:"-"`
	Agent           Agent                           `json:"agent,omitempty" yaml:"agent,omitempty"`
	Categories      []Category                      `json:"categories,omitempty" yaml:"categories,omitempty"`
	Dataset         string                          `json:"dataset,omitempty" yaml:"dataset,omitempty"`
	DatasetIsPrefix *bool                           `json:"dataset_is_prefix,omitempty" yaml:"dataset_is_prefix,omitempty"`
	Deprecated      Deprecated                      `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Elasticsearch   DataStreamManifestElasticsearch `json:"elasticsearch,omitempty" yaml:"elasticsearch,omitempty"`
	Hidden          *bool                           `json:"hidden,omitempty" yaml:"hidden,omitempty"`
	ILMPolicy       string                          `json:"ilm_policy,omitempty" yaml:"ilm_policy,omitempty"`
	Release         DataStreamManifestRelease       `json:"release,omitempty" yaml:"release,omitempty"`
	Streams         []DataStreamManifestStream      `json:"streams,omitempty" yaml:"streams,omitempty"`
	Title           string                          `json:"title,omitempty" yaml:"title,omitempty"`
	Type            DataStreamManifestType          `json:"type,omitempty" yaml:"type,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for DataStreamManifest.
// It captures the YAML node position for FileMetadata.
func (v *DataStreamManifest) UnmarshalYAML(node *yamlv3.Node) error {
	type plainDataStreamManifest DataStreamManifest
	x := (*plainDataStreamManifest)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// DataStreamManifestElasticsearch elasticsearch asset definitions
type DataStreamManifestElasticsearch struct {
	DynamicDataset   *bool                                     `json:"dynamic_dataset,omitempty" yaml:"dynamic_dataset,omitempty"`
	DynamicNamespace *bool                                     `json:"dynamic_namespace,omitempty" yaml:"dynamic_namespace,omitempty"`
	IndexMode        ElasticsearchIndexMode                    `json:"index_mode,omitempty" yaml:"index_mode,omitempty"`
	IndexTemplate    ElasticsearchIndexTemplate                `json:"index_template,omitempty" yaml:"index_template,omitempty"`
	Privileges       DataStreamManifestElasticsearchPrivileges `json:"privileges,omitempty" yaml:"privileges,omitempty"`
	SourceMode       DataStreamManifestElasticsearchSourceMode `json:"source_mode,omitempty" yaml:"source_mode,omitempty"`
}

// DataStreamManifestElasticsearchPrivileges elasticsearch privilege requirements
type DataStreamManifestElasticsearchPrivileges struct {
	Indices []string `json:"indices,omitempty" yaml:"indices,omitempty"`
}

/*
DataStreamManifestElasticsearchSourceMode source mode to use. This configures how the document source (`_source`) is stored
for this data stream.
If configured as `default`, this mode is not configured and it uses Elasticsearch defaults.
If configured as `synthetic`, it enables [synthetic source](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/mapping-source-field.html#synthetic-source),
that doesn't store the source, but tries to rebuild it from the indexed fields when queried.
If no configured or set to `synthetic`, users may override the setting from Fleet UI.
*/
type DataStreamManifestElasticsearchSourceMode string

// Enum values for DataStreamManifestElasticsearchSourceMode.
const (
	DataStreamManifestElasticsearchSourceModeDefault   DataStreamManifestElasticsearchSourceMode = "default"
	DataStreamManifestElasticsearchSourceModeSynthetic DataStreamManifestElasticsearchSourceMode = "synthetic"
)

// DataStreamManifestRelease stability of data stream.
type DataStreamManifestRelease string

// Enum values for DataStreamManifestRelease.
const (
	DataStreamManifestReleaseExperimental DataStreamManifestRelease = "experimental"
	DataStreamManifestReleaseBeta         DataStreamManifestRelease = "beta"
)

type DataStreamManifestStream struct {
	Description  string       `json:"description,omitempty" yaml:"description,omitempty"`
	Enabled      *bool        `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	Input        string       `json:"input,omitempty" yaml:"input,omitempty"`
	RequiredVars RequiredVars `json:"required_vars,omitempty" yaml:"required_vars,omitempty"`
	TemplatePath string       `json:"template_path,omitempty" yaml:"template_path,omitempty"`
	Title        string       `json:"title,omitempty" yaml:"title,omitempty"`
	VarGroups    []VarGroup   `json:"var_groups,omitempty" yaml:"var_groups,omitempty"`
	Vars         []Var        `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// DataStreamManifestType type of data stream
type DataStreamManifestType string

// Enum values for DataStreamManifestType.
const (
	DataStreamManifestTypeMetrics    DataStreamManifestType = "metrics"
	DataStreamManifestTypeLogs       DataStreamManifestType = "logs"
	DataStreamManifestTypeSynthetics DataStreamManifestType = "synthetics"
	DataStreamManifestTypeTraces     DataStreamManifestType = "traces"
	DataStreamManifestTypeProfiling  DataStreamManifestType = "profiling"
)
