// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

/*
ElasticsearchIndexMode index mode to use. Index mode can be used to enable use case specific functionalities.
This setting must be installed in the composable index template, not in the package component templates.
*/
type ElasticsearchIndexMode string

// Enum values for ElasticsearchIndexMode.
const (
	ElasticsearchIndexModeTimeSeries ElasticsearchIndexMode = "time_series"
)

// ElasticsearchIndexTemplate index template definition
type ElasticsearchIndexTemplate struct {
	DataStream     ElasticsearchIndexTemplateDataStream     `json:"data_stream,omitempty" yaml:"data_stream,omitempty"`
	IngestPipeline ElasticsearchIndexTemplateIngestPipeline `json:"ingest_pipeline,omitempty" yaml:"ingest_pipeline,omitempty"`
	Mappings       ElasticsearchIndexTemplateMappings       `json:"mappings,omitempty" yaml:"mappings,omitempty"`
	Settings       ElasticsearchIndexTemplateSettings       `json:"settings,omitempty" yaml:"settings,omitempty"`
}

// ElasticsearchIndexTemplateDataStream data stream section of index template
type ElasticsearchIndexTemplateDataStream struct {
	Hidden *bool `json:"hidden,omitempty" yaml:"hidden,omitempty"`
}

// ElasticsearchIndexTemplateIngestPipeline elasticsearch ingest pipeline settings
type ElasticsearchIndexTemplateIngestPipeline struct {
	Name string `json:"name" yaml:"name"`
}

// ElasticsearchIndexTemplateMappings mappings section of index template
type ElasticsearchIndexTemplateMappings struct {
	DateDetection      *bool    `json:"date_detection,omitempty" yaml:"date_detection,omitempty"`
	Dynamic            any      `json:"dynamic,omitempty" yaml:"dynamic,omitempty"`
	DynamicDateFormats []string `json:"dynamic_date_formats,omitempty" yaml:"dynamic_date_formats,omitempty"`
	DynamicTemplates   any      `json:"dynamic_templates,omitempty" yaml:"dynamic_templates,omitempty"`
	Subobjects         *bool    `json:"subobjects,omitempty" yaml:"subobjects,omitempty"`
}

type ElasticsearchIndexTemplateMappingsDynamicTemplateValue struct {
	Mapping          ElasticsearchIndexTemplateMappingsDynamicTemplateValueMapping `json:"mapping,omitempty" yaml:"mapping,omitempty"`
	MatchMappingType any                                                           `json:"match_mapping_type,omitempty" yaml:"match_mapping_type,omitempty"`
}

type ElasticsearchIndexTemplateMappingsDynamicTemplateValueMapping struct {
	DefaultMetric any       `json:"default_metric,omitempty" yaml:"default_metric,omitempty"`
	IgnoreAbove   int       `json:"ignore_above,omitempty" yaml:"ignore_above,omitempty"`
	Index         *bool     `json:"index,omitempty" yaml:"index,omitempty"`
	Metrics       any       `json:"metrics,omitempty" yaml:"metrics,omitempty"`
	ScalingFactor int       `json:"scaling_factor,omitempty" yaml:"scaling_factor,omitempty"`
	Type          FieldType `json:"type,omitempty" yaml:"type,omitempty"`
}

// ElasticsearchIndexTemplateSettings settings section of index template
type ElasticsearchIndexTemplateSettings struct {
	Analysis       IndexTemplateSettingAnalysis `json:"analysis,omitempty" yaml:"analysis,omitempty"`
	Index          IndexTemplateSettingIndex    `json:"index,omitempty" yaml:"index,omitempty"`
	NumberOfShards int                          `json:"number_of_shards,omitempty" yaml:"number_of_shards,omitempty"`
}

type IndexTemplateSettingAnalysis struct {
	Analyzer map[string]IndexTemplateSettingAnalysisAnalyzerValue `json:"analyzer,omitempty" yaml:"analyzer,omitempty"`
}

type IndexTemplateSettingAnalysisAnalyzerValue struct {
	Pattern string                                        `json:"pattern,omitempty" yaml:"pattern,omitempty"`
	Type    IndexTemplateSettingAnalysisAnalyzerValueType `json:"type,omitempty" yaml:"type,omitempty"`
}

// IndexTemplateSettingAnalysisAnalyzerValueType type of analyzer
type IndexTemplateSettingAnalysisAnalyzerValueType string

// Enum values for IndexTemplateSettingAnalysisAnalyzerValueType.
const (
	IndexTemplateSettingAnalysisAnalyzerValueTypePattern IndexTemplateSettingAnalysisAnalyzerValueType = "pattern"
)

type IndexTemplateSettingIndex struct {
	Codec   IndexTemplateSettingIndexCodec   `json:"codec,omitempty" yaml:"codec,omitempty"`
	Mapping IndexTemplateSettingIndexMapping `json:"mapping,omitempty" yaml:"mapping,omitempty"`
	Sort    IndexTemplateSettingIndexSort    `json:"sort,omitempty" yaml:"sort,omitempty"`
}

// IndexTemplateSettingIndexCodec type of compression to use. The default is to use LZ4, `best_compression` uses DEFLATE, with higher compression but lower ingestion performance.
type IndexTemplateSettingIndexCodec string

// Enum values for IndexTemplateSettingIndexCodec.
const (
	IndexTemplateSettingIndexCodecDefault         IndexTemplateSettingIndexCodec = "default"
	IndexTemplateSettingIndexCodecBestCompression IndexTemplateSettingIndexCodec = "best_compression"
)

type IndexTemplateSettingIndexMapping struct{}

type IndexTemplateSettingIndexSort struct {
	Field any `json:"field,omitempty" yaml:"field,omitempty"`
	Order any `json:"order,omitempty" yaml:"order,omitempty"`
}
