// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

import yamlv3 "gopkg.in/yaml.v3"

type Tag struct {
	FileMetadata `json:"-" yaml:"-"`
	AssetIDs     []string       `json:"asset_ids,omitempty" yaml:"asset_ids,omitempty"`
	AssetTypes   []TagAssetType `json:"asset_types,omitempty" yaml:"asset_types,omitempty"`
	Text         string         `json:"text,omitempty" yaml:"text,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Tag.
// It captures the YAML node position for FileMetadata.
func (v *Tag) UnmarshalYAML(node *yamlv3.Node) error {
	type plainTag Tag
	x := (*plainTag)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

type TagAssetType string

// Enum values for TagAssetType.
const (
	TagAssetTypeDashboard            TagAssetType = "dashboard"
	TagAssetTypeVisualization        TagAssetType = "visualization"
	TagAssetTypeSearch               TagAssetType = "search"
	TagAssetTypeMap                  TagAssetType = "map"
	TagAssetTypeLens                 TagAssetType = "lens"
	TagAssetTypeIndexPattern         TagAssetType = "index_pattern"
	TagAssetTypeSecurityRule         TagAssetType = "security_rule"
	TagAssetTypeCspRuleTemplate      TagAssetType = "csp_rule_template"
	TagAssetTypeAlertingRuleTemplate TagAssetType = "alerting_rule_template"
	TagAssetTypeSloTemplate          TagAssetType = "slo_template"
	TagAssetTypeMlModule             TagAssetType = "ml_module"
	TagAssetTypeOsqueryPackAsset     TagAssetType = "osquery_pack_asset"
	TagAssetTypeOsquerySavedQuery    TagAssetType = "osquery_saved_query"
)
