// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

import yamlv3 "gopkg.in/yaml.v3"

type Lifecycle struct {
	FileMetadata  `json:"-" yaml:"-"`
	DataRetention string `json:"data_retention,omitempty" yaml:"data_retention,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for Lifecycle.
// It captures the YAML node position for FileMetadata.
func (v *Lifecycle) UnmarshalYAML(node *yamlv3.Node) error {
	type plainLifecycle Lifecycle
	x := (*plainLifecycle)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}
