// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

import yamlv3 "gopkg.in/yaml.v3"

// Agent declarations related to Agent configurations or requirements.
type Agent struct {
	Privileges AgentPrivileges `json:"privileges,omitempty" yaml:"privileges,omitempty"`
}

type AgentPrivileges struct {
	Root *bool `json:"root,omitempty" yaml:"root,omitempty"`
}

type Category string

// Enum values for Category.
const (
	CategoryAdvancedAnalyticsUeba    Category = "advanced_analytics_ueba"
	CategoryAnalyticsEngine          Category = "analytics_engine"
	CategoryApplicationObservability Category = "application_observability"
	CategoryAppSearch                Category = "app_search"
	CategoryAssetInventory           Category = "asset_inventory"
	CategoryAuditd                   Category = "auditd"
	CategoryAuthentication           Category = "authentication"
	CategoryAws                      Category = "aws"
	CategoryAzure                    Category = "azure"
	CategoryBigData                  Category = "big_data"
	CategoryCdnSecurity              Category = "cdn_security"
	CategoryCloud                    Category = "cloud"
	CategoryCloudsecurityCdr         Category = "cloudsecurity_cdr"
	CategoryConfigManagement         Category = "config_management"
	CategoryConnector                Category = "connector"
	CategoryConnectorClient          Category = "connector_client"
	CategoryConnectorPackage         Category = "connector_package"
	CategoryContainers               Category = "containers"
	CategoryContentSource            Category = "content_source"
	CategoryCrawler                  Category = "crawler"
	CategoryCredentialManagement     Category = "credential_management"
	CategoryCrm                      Category = "crm"
	CategoryCustom                   Category = "custom"
	CategoryCustomLogs               Category = "custom_logs"
	CategoryDatabaseSecurity         Category = "database_security"
	CategoryDatastore                Category = "datastore"
	CategoryDNSSecurity              Category = "dns_security"
	CategoryEdrXdr                   Category = "edr_xdr"
	CategoryElasticsearchSdk         Category = "elasticsearch_sdk"
	CategoryElasticStack             Category = "elastic_stack"
	CategoryEmailSecurity            Category = "email_security"
	CategoryEnterpriseSearch         Category = "enterprise_search"
	CategoryFirewallSecurity         Category = "firewall_security"
	CategoryGoogleCloud              Category = "google_cloud"
	CategoryIam                      Category = "iam"
	CategoryIDsIps                   Category = "ids_ips"
	CategoryInfrastructure           Category = "infrastructure"
	CategoryJavaObservability        Category = "java_observability"
	CategoryKubernetes               Category = "kubernetes"
	CategoryLanguageClient           Category = "language_client"
	CategoryLanguages                Category = "languages"
	CategoryLoadBalancer             Category = "load_balancer"
	CategoryMessageQueue             Category = "message_queue"
	CategoryMisconfigurationWorkflow Category = "misconfiguration_workflow"
	CategoryMonitoring               Category = "monitoring"
	CategoryNativeSearch             Category = "native_search"
	CategoryNetwork                  Category = "network"
	CategoryNetworkSecurity          Category = "network_security"
	CategoryNotification             Category = "notification"
	CategoryObservability            Category = "observability"
	CategoryOpentelemetry            Category = "opentelemetry"
	CategoryOSSystem                 Category = "os_system"
	CategoryProcessManager           Category = "process_manager"
	CategoryProductivity             Category = "productivity"
	CategoryProductivitySecurity     Category = "productivity_security"
	CategoryProxySecurity            Category = "proxy_security"
	CategorySdkSearch                Category = "sdk_search"
	CategorySecurity                 Category = "security"
	CategorySiem                     Category = "siem"
	CategoryStreamProcessing         Category = "stream_processing"
	CategorySupport                  Category = "support"
	CategoryThreatIntel              Category = "threat_intel"
	CategoryTicketing                Category = "ticketing"
	CategoryVersionControl           Category = "version_control"
	CategoryVirtualization           Category = "virtualization"
	CategoryVpnSecurity              Category = "vpn_security"
	CategoryVulnerabilityManagement  Category = "vulnerability_management"
	CategoryVulnerabilityWorkflow    Category = "vulnerability_workflow"
	CategoryWeb                      Category = "web"
	CategoryWebApplicationFirewall   Category = "web_application_firewall"
	CategoryWebsphere                Category = "websphere"
	CategoryWorkplaceSearch          Category = "workplace_search"
)

// Conditions under which this package can be installed.
type Conditions struct {
	Agent   ConditionsAgent   `json:"agent,omitempty" yaml:"agent,omitempty"`
	Elastic ConditionsElastic `json:"elastic,omitempty" yaml:"elastic,omitempty"`
	Kibana  ConditionsKibana  `json:"kibana,omitempty" yaml:"kibana,omitempty"`
}

// ConditionsAgent elastic Agent conditions
type ConditionsAgent struct {
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
}

// ConditionsElastic elastic conditions
type ConditionsElastic struct {
	Capabilities []ConditionsElasticCapability `json:"capabilities,omitempty" yaml:"capabilities,omitempty"`
	Subscription ConditionsElasticSubscription `json:"subscription,omitempty" yaml:"subscription,omitempty"`
}

type ConditionsElasticCapability string

// Enum values for ConditionsElasticCapability.
const (
	ConditionsElasticCapabilityApm              ConditionsElasticCapability = "apm"
	ConditionsElasticCapabilityEnterpriseSearch ConditionsElasticCapability = "enterprise_search"
	ConditionsElasticCapabilityObservability    ConditionsElasticCapability = "observability"
	ConditionsElasticCapabilitySecurity         ConditionsElasticCapability = "security"
	ConditionsElasticCapabilityServerlessSearch ConditionsElasticCapability = "serverless_search"
	ConditionsElasticCapabilityUptime           ConditionsElasticCapability = "uptime"
)

// ConditionsElasticSubscription the subscription required for this package.
type ConditionsElasticSubscription string

// Enum values for ConditionsElasticSubscription.
const (
	ConditionsElasticSubscriptionBasic      ConditionsElasticSubscription = "basic"
	ConditionsElasticSubscriptionGold       ConditionsElasticSubscription = "gold"
	ConditionsElasticSubscriptionPlatinum   ConditionsElasticSubscription = "platinum"
	ConditionsElasticSubscriptionEnterprise ConditionsElasticSubscription = "enterprise"
)

// ConditionsKibana kibana conditions
type ConditionsKibana struct {
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
}

type ContentManifest struct {
	FileMetadata  `json:"-" yaml:"-"`
	Categories    []Category                `json:"categories,omitempty" yaml:"categories,omitempty"`
	Conditions    ContentManifestConditions `json:"conditions,omitempty" yaml:"conditions,omitempty"`
	Deprecated    Deprecated                `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description   string                    `json:"description,omitempty" yaml:"description,omitempty"`
	Discovery     Discovery                 `json:"discovery,omitempty" yaml:"discovery,omitempty"`
	FormatVersion string                    `json:"format_version,omitempty" yaml:"format_version,omitempty"`
	Icons         []Icon                    `json:"icons,omitempty" yaml:"icons,omitempty"`
	Name          string                    `json:"name,omitempty" yaml:"name,omitempty"`
	Owner         Owner                     `json:"owner,omitempty" yaml:"owner,omitempty"`
	Screenshots   []Screenshot              `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	Source        Source                    `json:"source,omitempty" yaml:"source,omitempty"`
	Title         string                    `json:"title,omitempty" yaml:"title,omitempty"`
	Type          ContentManifestType       `json:"type,omitempty" yaml:"type,omitempty"`
	Version       string                    `json:"version,omitempty" yaml:"version,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for ContentManifest.
// It captures the YAML node position for FileMetadata.
func (v *ContentManifest) UnmarshalYAML(node *yamlv3.Node) error {
	type plainContentManifest ContentManifest
	x := (*plainContentManifest)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// ContentManifestConditions conditions under which this package can be installed.
type ContentManifestConditions struct {
	Elastic ConditionsElastic `json:"elastic,omitempty" yaml:"elastic,omitempty"`
	Kibana  ConditionsKibana  `json:"kibana,omitempty" yaml:"kibana,omitempty"`
}

// ContentManifestType the type of package.
type ContentManifestType string

// Enum values for ContentManifestType.
const (
	ContentManifestTypeContent ContentManifestType = "content"
)

// Deprecated information on deprecation of a package or an individual feature.
type Deprecated struct {
	Description string               `json:"description,omitempty" yaml:"description,omitempty"`
	ReplacedBy  DeprecatedReplacedBy `json:"replaced_by,omitempty" yaml:"replaced_by,omitempty"`
	Since       string               `json:"since,omitempty" yaml:"since,omitempty"`
}

type DeprecatedReplacedBy struct {
	DataStream     string `json:"data_stream,omitempty" yaml:"data_stream,omitempty"`
	Input          string `json:"input,omitempty" yaml:"input,omitempty"`
	Package        string `json:"package,omitempty" yaml:"package,omitempty"`
	PolicyTemplate string `json:"policy_template,omitempty" yaml:"policy_template,omitempty"`
	Variable       string `json:"variable,omitempty" yaml:"variable,omitempty"`
}

// Discovery description of the data this package can be used with. It can be used to discover the package from elements in the existing data.
type Discovery struct {
	Datasets []DiscoveryDataset `json:"datasets,omitempty" yaml:"datasets,omitempty"`
	Fields   []DiscoveryField   `json:"fields,omitempty" yaml:"fields,omitempty"`
}

type DiscoveryDataset struct {
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
}

type DiscoveryField struct {
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
}

type Icon struct {
	DarkMode *bool  `json:"dark_mode,omitempty" yaml:"dark_mode,omitempty"`
	Size     string `json:"size,omitempty" yaml:"size,omitempty"`
	Src      string `json:"src,omitempty" yaml:"src,omitempty"`
	Title    string `json:"title,omitempty" yaml:"title,omitempty"`
	Type     string `json:"type,omitempty" yaml:"type,omitempty"`
}

type InputManifest struct {
	FileMetadata    `json:"-" yaml:"-"`
	Agent           Agent                         `json:"agent,omitempty" yaml:"agent,omitempty"`
	Categories      []Category                    `json:"categories,omitempty" yaml:"categories,omitempty"`
	Conditions      Conditions                    `json:"conditions,omitempty" yaml:"conditions,omitempty"`
	Deprecated      Deprecated                    `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description     string                        `json:"description,omitempty" yaml:"description,omitempty"`
	Elasticsearch   InputManifestElasticsearch    `json:"elasticsearch,omitempty" yaml:"elasticsearch,omitempty"`
	FormatVersion   string                        `json:"format_version,omitempty" yaml:"format_version,omitempty"`
	Icons           []Icon                        `json:"icons,omitempty" yaml:"icons,omitempty"`
	Name            string                        `json:"name,omitempty" yaml:"name,omitempty"`
	Owner           Owner                         `json:"owner,omitempty" yaml:"owner,omitempty"`
	PolicyTemplates []InputManifestPolicyTemplate `json:"policy_templates,omitempty" yaml:"policy_templates,omitempty"`
	Screenshots     []Screenshot                  `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	Source          Source                        `json:"source,omitempty" yaml:"source,omitempty"`
	Title           string                        `json:"title,omitempty" yaml:"title,omitempty"`
	Type            InputManifestType             `json:"type,omitempty" yaml:"type,omitempty"`
	Vars            []Var                         `json:"vars,omitempty" yaml:"vars,omitempty"`
	Version         string                        `json:"version,omitempty" yaml:"version,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for InputManifest.
// It captures the YAML node position for FileMetadata.
func (v *InputManifest) UnmarshalYAML(node *yamlv3.Node) error {
	type plainInputManifest InputManifest
	x := (*plainInputManifest)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// InputManifestElasticsearch elasticsearch asset definitions
type InputManifestElasticsearch struct {
	IndexMode     ElasticsearchIndexMode     `json:"index_mode,omitempty" yaml:"index_mode,omitempty"`
	IndexTemplate ElasticsearchIndexTemplate `json:"index_template,omitempty" yaml:"index_template,omitempty"`
}

// InputManifestType the type of package.
type InputManifestType string

// Enum values for InputManifestType.
const (
	InputManifestTypeInput InputManifestType = "input"
)

type IntegrationManifest struct {
	FileMetadata            `json:"-" yaml:"-"`
	Agent                   Agent                               `json:"agent,omitempty" yaml:"agent,omitempty"`
	Categories              []Category                          `json:"categories,omitempty" yaml:"categories,omitempty"`
	Conditions              Conditions                          `json:"conditions,omitempty" yaml:"conditions,omitempty"`
	Deprecated              Deprecated                          `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description             string                              `json:"description,omitempty" yaml:"description,omitempty"`
	Elasticsearch           IntegrationManifestElasticsearch    `json:"elasticsearch,omitempty" yaml:"elasticsearch,omitempty"`
	FormatVersion           string                              `json:"format_version,omitempty" yaml:"format_version,omitempty"`
	Icons                   []Icon                              `json:"icons,omitempty" yaml:"icons,omitempty"`
	Name                    string                              `json:"name,omitempty" yaml:"name,omitempty"`
	Owner                   Owner                               `json:"owner,omitempty" yaml:"owner,omitempty"`
	PolicyTemplates         []IntegrationManifestPolicyTemplate `json:"policy_templates,omitempty" yaml:"policy_templates,omitempty"`
	PolicyTemplatesBehavior string                              `json:"policy_templates_behavior,omitempty" yaml:"policy_templates_behavior,omitempty"`
	Screenshots             []Screenshot                        `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	Source                  Source                              `json:"source,omitempty" yaml:"source,omitempty"`
	Title                   string                              `json:"title,omitempty" yaml:"title,omitempty"`
	Type                    IntegrationManifestType             `json:"type,omitempty" yaml:"type,omitempty"`
	VarGroups               []VarGroup                          `json:"var_groups,omitempty" yaml:"var_groups,omitempty"`
	Vars                    []Var                               `json:"vars,omitempty" yaml:"vars,omitempty"`
	Version                 string                              `json:"version,omitempty" yaml:"version,omitempty"`
}

// UnmarshalYAML implements yaml.Unmarshaler for IntegrationManifest.
// It captures the YAML node position for FileMetadata.
func (v *IntegrationManifest) UnmarshalYAML(node *yamlv3.Node) error {
	type plainIntegrationManifest IntegrationManifest
	x := (*plainIntegrationManifest)(v)
	if err := node.Decode(x); err != nil {
		return err
	}
	v.FileMetadata.line = node.Line
	v.FileMetadata.column = node.Column
	return nil
}

// IntegrationManifestElasticsearch elasticsearch requirements
type IntegrationManifestElasticsearch struct {
	Privileges IntegrationManifestElasticsearchPrivileges `json:"privileges,omitempty" yaml:"privileges,omitempty"`
}

// IntegrationManifestElasticsearchPrivileges elasticsearch privilege requirements
type IntegrationManifestElasticsearchPrivileges struct {
	Cluster []string `json:"cluster,omitempty" yaml:"cluster,omitempty"`
}

// IntegrationManifestType the type of package.
type IntegrationManifestType string

// Enum values for IntegrationManifestType.
const (
	IntegrationManifestTypeIntegration IntegrationManifestType = "integration"
)

type Owner struct {
	Github string    `json:"github,omitempty" yaml:"github,omitempty"`
	Type   OwnerType `json:"type,omitempty" yaml:"type,omitempty"`
}

// OwnerType describes who owns the package and the level of support that is provided. The 'elastic' value indicates that the package is built and maintained by Elastic. The 'partner' value indicates that the package is built and maintained by a partner vendor and may include involvement from Elastic. The 'community' value indicates the package is built and maintained by non-Elastic community members.
type OwnerType string

// Enum values for OwnerType.
const (
	OwnerTypeElastic   OwnerType = "elastic"
	OwnerTypePartner   OwnerType = "partner"
	OwnerTypeCommunity OwnerType = "community"
)

type Screenshot struct {
	Size  string `json:"size,omitempty" yaml:"size,omitempty"`
	Src   string `json:"src,omitempty" yaml:"src,omitempty"`
	Title string `json:"title,omitempty" yaml:"title,omitempty"`
	Type  string `json:"type,omitempty" yaml:"type,omitempty"`
}

// Source information about the source of the package.
type Source struct {
	License SourceLicense `json:"license,omitempty" yaml:"license,omitempty"`
}

// SourceLicense identifier of the license of the package, as specified in https://spdx.org/licenses/.
type SourceLicense string

// Enum values for SourceLicense.
const (
	SourceLicenseApache20  SourceLicense = "Apache-2.0"
	SourceLicenseElastic20 SourceLicense = "Elastic-2.0"
)
