// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

import "reflect"

// FileMetadata records the source file location from which a value was loaded.
type FileMetadata struct {
	file   string // file from which value was read.
	line   int    // line from which value was read.
	column int    // column from which value was read.
}

// FilePath returns the file path from which the value was loaded.
func (m FileMetadata) FilePath() string {
	return m.file
}

// Line returns the line number in the source file.
func (m FileMetadata) Line() int {
	return m.line
}

// Column returns the column number in the source file.
func (m FileMetadata) Column() int {
	return m.column
}

// annotateFileMetadata sets the file name on any types that contain FileMetadata.
func annotateFileMetadata(file string, v any) {
	fileAnnotator{name: file}.annotate(reflect.ValueOf(v))
}

type fileAnnotator struct {
	name string
}

func (a fileAnnotator) annotate(val reflect.Value) {
	if val.CanAddr() && val.CanSet() {
		if m, ok := val.Addr().Interface().(*FileMetadata); ok {
			m.file = a.name
			return
		}
	}

	switch val.Kind() {
	case reflect.Pointer:
		if !val.IsNil() {
			a.annotate(val.Elem())
		}
	case reflect.Struct:
		for i := 0; i < val.NumField(); i++ {
			a.annotate(val.Field(i))
		}
	case reflect.Slice:
		for i := 0; i < val.Len(); i++ {
			a.annotate(val.Index(i))
		}
	case reflect.Map:
		itr := val.MapRange()
		for itr.Next() {
			a.annotate(itr.Value())
		}
	}
}
