// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

type ConfigurationLink struct {
	Content string                `json:"content,omitempty" yaml:"content,omitempty"`
	Title   string                `json:"title" yaml:"title"`
	Type    ConfigurationLinkType `json:"type" yaml:"type"`
	URL     string                `json:"url" yaml:"url"`
}

// ConfigurationLinkType type of link. `next_steps` for links to locations that can be relevant right after configuring the policy. `action` for actions that can be performed while the policy is in use.
type ConfigurationLinkType string

// Enum values for ConfigurationLinkType.
const (
	ConfigurationLinkTypeAction   ConfigurationLinkType = "action"
	ConfigurationLinkTypeNextStep ConfigurationLinkType = "next_step"
)

// DeploymentModes options related to the deployment modes. The deployment mode refers to the mode used to deploy the Elastic Agents running this policy.
type DeploymentModes struct {
	Agentless DeploymentModesAgentless `json:"agentless,omitempty" yaml:"agentless,omitempty"`
	Default   DeploymentModesDefault   `json:"default,omitempty" yaml:"default,omitempty"`
}

// DeploymentModesAgentless options specific to the Agentless deployment mode. This mode is used in offerings where the Elastic Agents running these policies are fully managed for the user.
type DeploymentModesAgentless struct {
	Division     string                            `json:"division,omitempty" yaml:"division,omitempty"`
	Enabled      *bool                             `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	IsDefault    *bool                             `json:"is_default,omitempty" yaml:"is_default,omitempty"`
	Organization string                            `json:"organization,omitempty" yaml:"organization,omitempty"`
	Resources    DeploymentModesAgentlessResources `json:"resources,omitempty" yaml:"resources,omitempty"`
	Team         string                            `json:"team,omitempty" yaml:"team,omitempty"`
}

// DeploymentModesAgentlessResources the computing resources specifications for the Agentless deployment.
type DeploymentModesAgentlessResources struct {
	Requests DeploymentModesAgentlessResourcesRequests `json:"requests,omitempty" yaml:"requests,omitempty"`
}

// DeploymentModesAgentlessResourcesRequests the computing resources that the Agentless deployment will be initially allocated.
type DeploymentModesAgentlessResourcesRequests struct {
	CPU    string `json:"cpu,omitempty" yaml:"cpu,omitempty"`
	Memory string `json:"memory,omitempty" yaml:"memory,omitempty"`
}

// DeploymentModesDefault options specific to the default deployment mode, where agents are normally managed by users, explicitly enrolled to Fleet and visible in UIs.
type DeploymentModesDefault struct {
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

type InputManifestPolicyTemplate struct {
	ConfigurationLinks []ConfigurationLink             `json:"configuration_links,omitempty" yaml:"configuration_links,omitempty"`
	DeploymentModes    DeploymentModes                 `json:"deployment_modes,omitempty" yaml:"deployment_modes,omitempty"`
	Deprecated         Deprecated                      `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description        string                          `json:"description" yaml:"description"`
	DynamicSignalTypes *bool                           `json:"dynamic_signal_types,omitempty" yaml:"dynamic_signal_types,omitempty"`
	FipsCompatible     *bool                           `json:"fips_compatible,omitempty" yaml:"fips_compatible,omitempty"`
	Icons              []Icon                          `json:"icons,omitempty" yaml:"icons,omitempty"`
	Input              string                          `json:"input" yaml:"input"`
	Name               string                          `json:"name" yaml:"name"`
	Screenshots        []Screenshot                    `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	TemplatePath       string                          `json:"template_path" yaml:"template_path"`
	Title              string                          `json:"title" yaml:"title"`
	Type               InputManifestPolicyTemplateType `json:"type" yaml:"type"`
	Vars               []Var                           `json:"vars,omitempty" yaml:"vars,omitempty"`
}

// InputManifestPolicyTemplateType type of data stream
type InputManifestPolicyTemplateType string

// Enum values for InputManifestPolicyTemplateType.
const (
	InputManifestPolicyTemplateTypeMetrics    InputManifestPolicyTemplateType = "metrics"
	InputManifestPolicyTemplateTypeLogs       InputManifestPolicyTemplateType = "logs"
	InputManifestPolicyTemplateTypeSynthetics InputManifestPolicyTemplateType = "synthetics"
	InputManifestPolicyTemplateTypeTraces     InputManifestPolicyTemplateType = "traces"
)

type IntegrationManifestPolicyTemplate struct {
	Categories         []Category                               `json:"categories,omitempty" yaml:"categories,omitempty"`
	ConfigurationLinks []ConfigurationLink                      `json:"configuration_links,omitempty" yaml:"configuration_links,omitempty"`
	DataStreams        []string                                 `json:"data_streams,omitempty" yaml:"data_streams,omitempty"`
	DeploymentModes    DeploymentModes                          `json:"deployment_modes,omitempty" yaml:"deployment_modes,omitempty"`
	Deprecated         Deprecated                               `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description        string                                   `json:"description" yaml:"description"`
	FipsCompatible     *bool                                    `json:"fips_compatible,omitempty" yaml:"fips_compatible,omitempty"`
	Icons              []Icon                                   `json:"icons,omitempty" yaml:"icons,omitempty"`
	Inputs             []IntegrationManifestPolicyTemplateInput `json:"inputs,omitempty" yaml:"inputs,omitempty"`
	Multiple           *bool                                    `json:"multiple,omitempty" yaml:"multiple,omitempty"`
	Name               string                                   `json:"name" yaml:"name"`
	Screenshots        []Screenshot                             `json:"screenshots,omitempty" yaml:"screenshots,omitempty"`
	Title              string                                   `json:"title" yaml:"title"`
	Vars               []Var                                    `json:"vars,omitempty" yaml:"vars,omitempty"`
}

type IntegrationManifestPolicyTemplateInput struct {
	DeploymentModes       []IntegrationManifestPolicyTemplateInputDeploymentMode `json:"deployment_modes,omitempty" yaml:"deployment_modes,omitempty"`
	Deprecated            Deprecated                                             `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description           string                                                 `json:"description" yaml:"description"`
	HideInVarGroupOptions map[string][]string                                    `json:"hide_in_var_group_options,omitempty" yaml:"hide_in_var_group_options,omitempty"`
	InputGroup            IntegrationManifestPolicyTemplateInputInputGroup       `json:"input_group,omitempty" yaml:"input_group,omitempty"`
	Multi                 *bool                                                  `json:"multi,omitempty" yaml:"multi,omitempty"`
	RequiredVars          RequiredVars                                           `json:"required_vars,omitempty" yaml:"required_vars,omitempty"`
	TemplatePath          string                                                 `json:"template_path,omitempty" yaml:"template_path,omitempty"`
	Title                 string                                                 `json:"title" yaml:"title"`
	Type                  string                                                 `json:"type" yaml:"type"`
	Vars                  []Var                                                  `json:"vars,omitempty" yaml:"vars,omitempty"`
}

type IntegrationManifestPolicyTemplateInputDeploymentMode string

// Enum values for IntegrationManifestPolicyTemplateInputDeploymentMode.
const (
	IntegrationManifestPolicyTemplateInputDeploymentModeDefault   IntegrationManifestPolicyTemplateInputDeploymentMode = "default"
	IntegrationManifestPolicyTemplateInputDeploymentModeAgentless IntegrationManifestPolicyTemplateInputDeploymentMode = "agentless"
)

// IntegrationManifestPolicyTemplateInputInputGroup name of the input group
type IntegrationManifestPolicyTemplateInputInputGroup string

// Enum values for IntegrationManifestPolicyTemplateInputInputGroup.
const (
	IntegrationManifestPolicyTemplateInputInputGroupLogs    IntegrationManifestPolicyTemplateInputInputGroup = "logs"
	IntegrationManifestPolicyTemplateInputInputGroupMetrics IntegrationManifestPolicyTemplateInputInputGroup = "metrics"
)
