// Code generated by cmd/generate; DO NOT EDIT.

package packagespec

// RequiredVars required conditional variables for the package.
type RequiredVars struct{}

// Var represents an input variable definition for a package.
type Var struct {
	Default               any                       `json:"default,omitempty" yaml:"default,omitempty"`
	Deprecated            Deprecated                `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
	Description           string                    `json:"description,omitempty" yaml:"description,omitempty"`
	HideInDeploymentModes []VarHideInDeploymentMode `json:"hide_in_deployment_modes,omitempty" yaml:"hide_in_deployment_modes,omitempty"`
	MaxDuration           string                    `json:"max_duration,omitempty" yaml:"max_duration,omitempty"`
	MinDuration           string                    `json:"min_duration,omitempty" yaml:"min_duration,omitempty"`
	Multi                 *bool                     `json:"multi,omitempty" yaml:"multi,omitempty"`
	Name                  string                    `json:"name,omitempty" yaml:"name,omitempty"`
	Options               any                       `json:"options,omitempty" yaml:"options,omitempty"`
	Required              *bool                     `json:"required,omitempty" yaml:"required,omitempty"`
	Secret                *bool                     `json:"secret,omitempty" yaml:"secret,omitempty"`
	ShowUser              *bool                     `json:"show_user,omitempty" yaml:"show_user,omitempty"`
	Title                 string                    `json:"title,omitempty" yaml:"title,omitempty"`
	Type                  VarType                   `json:"type,omitempty" yaml:"type,omitempty"`
	URLAllowedSchemes     []string                  `json:"url_allowed_schemes,omitempty" yaml:"url_allowed_schemes,omitempty"`
}

type VarGroup struct {
	Description   string           `json:"description,omitempty" yaml:"description,omitempty"`
	Name          string           `json:"name,omitempty" yaml:"name,omitempty"`
	Options       []VarGroupOption `json:"options,omitempty" yaml:"options,omitempty"`
	Required      *bool            `json:"required,omitempty" yaml:"required,omitempty"`
	SelectorTitle string           `json:"selector_title,omitempty" yaml:"selector_title,omitempty"`
	Title         string           `json:"title,omitempty" yaml:"title,omitempty"`
}

type VarGroupOption struct {
	Description           string                               `json:"description,omitempty" yaml:"description,omitempty"`
	HideInDeploymentModes []VarGroupOptionHideInDeploymentMode `json:"hide_in_deployment_modes,omitempty" yaml:"hide_in_deployment_modes,omitempty"`
	Name                  string                               `json:"name,omitempty" yaml:"name,omitempty"`
	Title                 string                               `json:"title,omitempty" yaml:"title,omitempty"`
	Vars                  []string                             `json:"vars,omitempty" yaml:"vars,omitempty"`
}

type VarGroupOptionHideInDeploymentMode string

// Enum values for VarGroupOptionHideInDeploymentMode.
const (
	VarGroupOptionHideInDeploymentModeDefault   VarGroupOptionHideInDeploymentMode = "default"
	VarGroupOptionHideInDeploymentModeAgentless VarGroupOptionHideInDeploymentMode = "agentless"
)

type VarHideInDeploymentMode string

// Enum values for VarHideInDeploymentMode.
const (
	VarHideInDeploymentModeDefault   VarHideInDeploymentMode = "default"
	VarHideInDeploymentModeAgentless VarHideInDeploymentMode = "agentless"
)

/*
VarType data type of variable.
A duration type is a sequence of decimal numbers, each with a unit suffix, such as "60s", "1m" or "2h45m". Duration values must follow these rules: - Use time units of "ms", "s", "m", "h". - When using min_duration, default, and max_duration,

	they must satisfy: 0 <= min_duration <= default <= max_duration
*/
type VarType string

// Enum values for VarType.
const (
	VarTypeBool     VarType = "bool"
	VarTypeEmail    VarType = "email"
	VarTypeInteger  VarType = "integer"
	VarTypePassword VarType = "password"
	VarTypeSelect   VarType = "select"
	VarTypeText     VarType = "text"
	VarTypeTextarea VarType = "textarea"
	VarTypeTimeZone VarType = "time_zone"
	VarTypeURL      VarType = "url"
	VarTypeYAML     VarType = "yaml"
	VarTypeDuration VarType = "duration"
)
