// Code generated by cmd/gensql; DO NOT EDIT.

package pkgsql

import (
	"database/sql"
	"encoding/json"
	pkgspec "github.com/andrewkroh/go-package-spec/pkgspec"
	"time"
)

// toNullString converts a string to sql.NullString. Empty strings are NULL.
func toNullString(s string) sql.NullString {
	return sql.NullString{
		String: s,
		Valid:  s != "",
	}
}

// toNullInt64 converts an int to sql.NullInt64. Zero values are NULL.
func toNullInt64(i int) sql.NullInt64 {
	return sql.NullInt64{
		Int64: int64(i),
		Valid: i != 0,
	}
}

// toNullFloat64 converts a float64 to sql.NullFloat64. Zero values are NULL.
func toNullFloat64(f float64) sql.NullFloat64 {
	return sql.NullFloat64{
		Float64: f,
		Valid:   f != 0,
	}
}

// toNullBool converts a *bool to sql.NullBool.
func toNullBool(b *bool) sql.NullBool {
	if b == nil {
		return sql.NullBool{}
	}
	return sql.NullBool{
		Bool:  *b,
		Valid: true,
	}
}

// jsonString marshals a value to a JSON string. Returns empty string on error.
func jsonString(v any) string {
	if v == nil {
		return ""
	}
	data, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	return string(data)
}

// jsonNullString marshals a value to a sql.NullString JSON column.
func jsonNullString(v any) sql.NullString {
	if v == nil {
		return sql.NullString{}
	}
	data, err := json.Marshal(v)
	if err != nil {
		return sql.NullString{}
	}
	s := string(data)
	return sql.NullString{
		String: s,
		Valid:  s != "" && s != "null",
	}
}

// timeNullString converts a *time.Time to sql.NullString (RFC3339 format).
func timeNullString(t *time.Time) sql.NullString {
	if t == nil {
		return sql.NullString{}
	}
	return sql.NullString{
		String: t.Format(time.RFC3339),
		Valid:  true,
	}
}

// mapFieldsParams converts a FlatField to InsertFieldsParams.
func mapFieldsParams(v *pkgspec.FlatField) InsertFieldsParams {
	return InsertFieldsParams{
		Analyzer:              toNullString(v.Analyzer),
		CopyTo:                toNullString(v.CopyTo),
		DateFormat:            toNullString(v.DateFormat),
		DefaultMetric:         jsonNullString(v.DefaultMetric),
		Description:           toNullString(v.Description),
		Dimension:             toNullBool(v.Dimension),
		DocValues:             toNullBool(v.DocValues),
		Dynamic:               jsonNullString(v.Dynamic),
		Enabled:               toNullBool(v.Enabled),
		Example:               jsonNullString(v.Example),
		ExpectedValues:        jsonNullString(v.ExpectedValues),
		External:              toNullString(string(v.External)),
		FileColumn:            toNullInt64(v.Column()),
		FileLine:              toNullInt64(v.Line()),
		FilePath:              toNullString(v.FilePath()),
		IgnoreAbove:           toNullInt64(v.IgnoreAbove),
		IgnoreMalformed:       toNullBool(v.IgnoreMalformed),
		IncludeInParent:       toNullBool(v.IncludeInParent),
		IncludeInRoot:         toNullBool(v.IncludeInRoot),
		Index:                 toNullBool(v.Index),
		InferenceID:           toNullString(v.InferenceID),
		JsonPointer:           toNullString(v.JsonPointer),
		MetricType:            toNullString(string(v.MetricType)),
		Metrics:               jsonNullString(v.Metrics),
		MultiFields:           jsonNullString(v.MultiFields),
		Name:                  v.Name,
		Normalize:             jsonNullString(v.Normalize),
		Normalizer:            toNullString(v.Normalizer),
		NullValue:             jsonNullString(v.NullValue),
		ObjectType:            toNullString(string(v.ObjectType)),
		ObjectTypeMappingType: toNullString(string(v.ObjectTypeMappingType)),
		Path:                  toNullString(v.Path),
		Pattern:               toNullString(v.Pattern),
		Runtime:               jsonNullString(v.Runtime),
		ScalingFactor:         toNullInt64(v.ScalingFactor),
		SearchAnalyzer:        toNullString(v.SearchAnalyzer),
		Store:                 toNullBool(v.Store),
		Subobjects:            toNullBool(v.Subobjects),
		Type:                  toNullString(string(v.Type)),
		Unit:                  toNullString(string(v.Unit)),
		Value:                 toNullString(v.Value),
	}
}

// mapPackagesParams converts a Manifest to InsertPackagesParams.
func mapPackagesParams(v *pkgspec.Manifest, agentPrivilegesRoot sql.NullBool, elasticsearchPrivilegesCluster any, policyTemplatesBehavior sql.NullString, dirName string, conditionsKibanaVersion sql.NullString, conditionsElasticSubscription sql.NullString) InsertPackagesParams {
	return InsertPackagesParams{
		AgentPrivilegesRoot:            agentPrivilegesRoot,
		ConditionsElasticSubscription:  conditionsElasticSubscription,
		ConditionsKibanaVersion:        conditionsKibanaVersion,
		Deprecated:                     jsonNullString(v.Deprecated),
		Description:                    v.Description,
		DirName:                        dirName,
		ElasticsearchPrivilegesCluster: elasticsearchPrivilegesCluster,
		FileColumn:                     toNullInt64(v.Column()),
		FileLine:                       toNullInt64(v.Line()),
		FilePath:                       toNullString(v.FilePath()),
		FormatVersion:                  v.FormatVersion,
		Name:                           v.Name,
		OwnerGithub:                    v.Owner.Github,
		OwnerType:                      string(v.Owner.Type),
		PolicyTemplatesBehavior:        policyTemplatesBehavior,
		SourceLicense:                  toNullString(string(v.Source.License)),
		Title:                          v.Title,
		Type:                           string(v.Type),
		Version:                        v.Version,
	}
}

// mapBuildManifestsParams converts a BuildManifest to InsertBuildManifestsParams.
func mapBuildManifestsParams(v *pkgspec.BuildManifest, parentID int64) InsertBuildManifestsParams {
	return InsertBuildManifestsParams{
		DependenciesEcsImportMappings: toNullBool(v.Dependencies.ECS.ImportMappings),
		DependenciesEcsReference:      v.Dependencies.ECS.Reference,
		FileColumn:                    toNullInt64(v.Column()),
		FileLine:                      toNullInt64(v.Line()),
		FilePath:                      toNullString(v.FilePath()),
		PackagesID:                    parentID,
	}
}

// mapChangelogsParams converts a Changelog to InsertChangelogsParams.
func mapChangelogsParams(v *pkgspec.Changelog, parentID int64) InsertChangelogsParams {
	return InsertChangelogsParams{
		Date:       timeNullString(v.Date),
		FileColumn: toNullInt64(v.Column()),
		FileLine:   toNullInt64(v.Line()),
		FilePath:   toNullString(v.FilePath()),
		PackagesID: parentID,
		Version:    v.Version,
	}
}

// mapChangelogEntriesParams converts a ChangelogEntry to InsertChangelogEntriesParams.
func mapChangelogEntriesParams(v *pkgspec.ChangelogEntry, parentID int64) InsertChangelogEntriesParams {
	return InsertChangelogEntriesParams{
		ChangelogsID: parentID,
		Description:  v.Description,
		Link:         v.Link,
		Type:         string(v.Type),
	}
}

// mapDataStreamsParams converts a DataStreamManifest to InsertDataStreamsParams.
func mapDataStreamsParams(v *pkgspec.DataStreamManifest, parentID int64, dirName string) InsertDataStreamsParams {
	return InsertDataStreamsParams{
		Dataset:                       toNullString(v.Dataset),
		DatasetIsPrefix:               toNullBool(v.DatasetIsPrefix),
		Deprecated:                    jsonNullString(v.Deprecated),
		DirName:                       dirName,
		ElasticsearchDynamicDataset:   toNullBool(v.Elasticsearch.DynamicDataset),
		ElasticsearchDynamicNamespace: toNullBool(v.Elasticsearch.DynamicNamespace),
		ElasticsearchIndexMode:        toNullString(string(v.Elasticsearch.IndexMode)),
		ElasticsearchIndexTemplate:    jsonNullString(v.Elasticsearch.IndexTemplate),
		ElasticsearchPrivileges:       jsonNullString(v.Elasticsearch.Privileges),
		ElasticsearchSourceMode:       toNullString(string(v.Elasticsearch.SourceMode)),
		FileColumn:                    toNullInt64(v.Column()),
		FileLine:                      toNullInt64(v.Line()),
		FilePath:                      toNullString(v.FilePath()),
		Hidden:                        toNullBool(v.Hidden),
		IlmPolicy:                     toNullString(v.ILMPolicy),
		PackagesID:                    parentID,
		Release:                       toNullString(string(v.Release)),
		Title:                         v.Title,
		Type:                          toNullString(string(v.Type)),
	}
}

// mapIngestPipelinesParams converts a IngestPipeline to InsertIngestPipelinesParams.
func mapIngestPipelinesParams(v *pkgspec.IngestPipeline, parentID int64, fileName string) InsertIngestPipelinesParams {
	return InsertIngestPipelinesParams{
		DataStreamsID: parentID,
		Description:   toNullString(v.Description),
		FileColumn:    toNullInt64(v.Column()),
		FileLine:      toNullInt64(v.Line()),
		FileName:      fileName,
		FilePath:      toNullString(v.FilePath()),
	}
}

// mapPackageIconsParams converts a Icon to InsertPackageIconsParams.
func mapPackageIconsParams(v *pkgspec.Icon, parentID int64) InsertPackageIconsParams {
	return InsertPackageIconsParams{
		DarkMode:   toNullBool(v.DarkMode),
		PackagesID: parentID,
		Size:       toNullString(v.Size),
		Src:        v.Src,
		Title:      toNullString(v.Title),
		Type:       toNullString(v.Type),
	}
}

// mapPackageScreenshotsParams converts a Screenshot to InsertPackageScreenshotsParams.
func mapPackageScreenshotsParams(v *pkgspec.Screenshot, parentID int64) InsertPackageScreenshotsParams {
	return InsertPackageScreenshotsParams{
		PackagesID: parentID,
		Size:       toNullString(v.Size),
		Src:        v.Src,
		Title:      v.Title,
		Type:       toNullString(v.Type),
	}
}

// mapPolicyTemplatesParams converts a PolicyTemplate to InsertPolicyTemplatesParams.
func mapPolicyTemplatesParams(v *pkgspec.PolicyTemplate, parentID int64) InsertPolicyTemplatesParams {
	return InsertPolicyTemplatesParams{
		ConfigurationLinks:                              jsonNullString(v.ConfigurationLinks),
		DataStreams:                                     jsonNullString(v.DataStreams),
		DeploymentModesAgentlessDivision:                toNullString(v.DeploymentModes.Agentless.Division),
		DeploymentModesAgentlessEnabled:                 toNullBool(v.DeploymentModes.Agentless.Enabled),
		DeploymentModesAgentlessIsDefault:               toNullBool(v.DeploymentModes.Agentless.IsDefault),
		DeploymentModesAgentlessOrganization:            toNullString(v.DeploymentModes.Agentless.Organization),
		DeploymentModesAgentlessResourcesRequestsCpu:    toNullString(v.DeploymentModes.Agentless.Resources.Requests.CPU),
		DeploymentModesAgentlessResourcesRequestsMemory: toNullString(v.DeploymentModes.Agentless.Resources.Requests.Memory),
		DeploymentModesAgentlessTeam:                    toNullString(v.DeploymentModes.Agentless.Team),
		DeploymentModesDefaultEnabled:                   toNullBool(v.DeploymentModes.Default.Enabled),
		Deprecated:                                      jsonNullString(v.Deprecated),
		Description:                                     v.Description,
		FipsCompatible:                                  toNullBool(v.FipsCompatible),
		Multiple:                                        toNullBool(v.Multiple),
		Name:                                            v.Name,
		PackagesID:                                      parentID,
		Title:                                           v.Title,
	}
}

// mapPolicyTemplateIconsParams converts a Icon to InsertPolicyTemplateIconsParams.
func mapPolicyTemplateIconsParams(v *pkgspec.Icon, parentID int64) InsertPolicyTemplateIconsParams {
	return InsertPolicyTemplateIconsParams{
		DarkMode:          toNullBool(v.DarkMode),
		PolicyTemplatesID: parentID,
		Size:              toNullString(v.Size),
		Src:               v.Src,
		Title:             toNullString(v.Title),
		Type:              toNullString(v.Type),
	}
}

// mapPolicyTemplateInputsParams converts a PolicyTemplateInput to InsertPolicyTemplateInputsParams.
func mapPolicyTemplateInputsParams(v *pkgspec.PolicyTemplateInput, parentID int64) InsertPolicyTemplateInputsParams {
	return InsertPolicyTemplateInputsParams{
		DeploymentModes:       jsonNullString(v.DeploymentModes),
		Deprecated:            jsonNullString(v.Deprecated),
		Description:           v.Description,
		HideInVarGroupOptions: jsonNullString(v.HideInVarGroupOptions),
		InputGroup:            toNullString(string(v.InputGroup)),
		Multi:                 toNullBool(v.Multi),
		PolicyTemplatesID:     parentID,
		TemplatePath:          toNullString(v.TemplatePath),
		Title:                 v.Title,
		Type:                  v.Type,
	}
}

// mapPolicyTemplateScreenshotsParams converts a Screenshot to InsertPolicyTemplateScreenshotsParams.
func mapPolicyTemplateScreenshotsParams(v *pkgspec.Screenshot, parentID int64) InsertPolicyTemplateScreenshotsParams {
	return InsertPolicyTemplateScreenshotsParams{
		PolicyTemplatesID: parentID,
		Size:              toNullString(v.Size),
		Src:               v.Src,
		Title:             v.Title,
		Type:              toNullString(v.Type),
	}
}

// mapRoutingRulesParams converts a RoutingRule to InsertRoutingRulesParams.
func mapRoutingRulesParams(v *pkgspec.RoutingRule, parentID int64) InsertRoutingRulesParams {
	return InsertRoutingRulesParams{
		DataStreamsID: parentID,
		If:            v.If,
		Namespace:     jsonNullString(v.Namespace),
		TargetDataset: jsonNullString(v.TargetDataset),
	}
}

// mapStreamsParams converts a DataStreamStream to InsertStreamsParams.
func mapStreamsParams(v *pkgspec.DataStreamStream, parentID int64) InsertStreamsParams {
	return InsertStreamsParams{
		DataStreamsID: parentID,
		Description:   v.Description,
		Enabled:       toNullBool(v.Enabled),
		Input:         v.Input,
		TemplatePath:  toNullString(v.TemplatePath),
		Title:         v.Title,
	}
}

// mapTagsParams converts a Tag to InsertTagsParams.
func mapTagsParams(v *pkgspec.Tag, parentID int64) InsertTagsParams {
	return InsertTagsParams{
		AssetIds:   jsonNullString(v.AssetIDs),
		AssetTypes: jsonNullString(v.AssetTypes),
		FileColumn: toNullInt64(v.Column()),
		FileLine:   toNullInt64(v.Line()),
		FilePath:   toNullString(v.FilePath()),
		PackagesID: parentID,
		Text:       toNullString(v.Text),
	}
}

// mapTransformsParams converts a Transform to InsertTransformsParams.
func mapTransformsParams(v *pkgspec.Transform, parentID int64, dirName string, manifestStart sql.NullBool, manifestDestinationIndexTemplate any) InsertTransformsParams {
	return InsertTransformsParams{
		Description:                      toNullString(v.Description),
		Dest:                             jsonNullString(v.Dest),
		DirName:                          dirName,
		FileColumn:                       toNullInt64(v.Column()),
		FileLine:                         toNullInt64(v.Line()),
		FilePath:                         toNullString(v.FilePath()),
		Frequency:                        toNullString(v.Frequency),
		Latest:                           jsonNullString(v.Latest),
		ManifestDestinationIndexTemplate: manifestDestinationIndexTemplate,
		ManifestStart:                    manifestStart,
		Meta:                             jsonNullString(v.Meta),
		PackagesID:                       parentID,
		Pivot:                            jsonNullString(v.Pivot),
		RetentionPolicy:                  jsonNullString(v.RetentionPolicy),
		Settings:                         jsonNullString(v.Settings),
		Source:                           jsonNullString(v.Source),
		Sync:                             jsonNullString(v.Sync),
	}
}

// mapVarsParams converts a Var to InsertVarsParams.
func mapVarsParams(v *pkgspec.Var) InsertVarsParams {
	return InsertVarsParams{
		Default:               jsonNullString(v.Default),
		Description:           toNullString(v.Description),
		HideInDeploymentModes: jsonNullString(v.HideInDeploymentModes),
		MaxDuration:           toNullString(v.MaxDuration),
		MinDuration:           toNullString(v.MinDuration),
		Multi:                 toNullBool(v.Multi),
		Name:                  v.Name,
		Options:               jsonNullString(v.Options),
		Required:              toNullBool(v.Required),
		Secret:                toNullBool(v.Secret),
		ShowUser:              toNullBool(v.ShowUser),
		Title:                 toNullString(v.Title),
		Type:                  string(v.Type),
		UrlAllowedSchemes:     jsonNullString(v.URLAllowedSchemes),
	}
}
