// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pkgsql

import (
	"database/sql"
)

type BuildManifest struct {
	ID                            int64
	PackagesID                    int64
	DependenciesEcsImportMappings sql.NullBool
	DependenciesEcsReference      string
}

type Changelog struct {
	ID         int64
	PackagesID int64
	Version    string
	Date       sql.NullString
}

type ChangelogEntry struct {
	ID           int64
	ChangelogsID int64
	Description  string
	Link         string
	Type         string
}

type DataStream struct {
	ID                            int64
	PackagesID                    int64
	DirName                       string
	Dataset                       sql.NullString
	DatasetIsPrefix               sql.NullBool
	Deprecated                    sql.NullString
	ElasticsearchDynamicDataset   sql.NullBool
	ElasticsearchDynamicNamespace sql.NullBool
	ElasticsearchIndexMode        sql.NullString
	ElasticsearchIndexTemplate    sql.NullString
	ElasticsearchPrivileges       sql.NullString
	ElasticsearchSourceMode       sql.NullString
	Hidden                        sql.NullBool
	IlmPolicy                     sql.NullString
	Release                       sql.NullString
	Title                         string
	Type                          sql.NullString
}

type DataStreamField struct {
	ID           int64
	DataStreamID int64
	FieldID      int64
}

type Field struct {
	ID                    int64
	Analyzer              sql.NullString
	CopyTo                sql.NullString
	DateFormat            sql.NullString
	DefaultMetric         sql.NullString
	Description           sql.NullString
	Dimension             sql.NullBool
	DocValues             sql.NullBool
	Dynamic               sql.NullString
	Enabled               sql.NullBool
	Example               sql.NullString
	ExpectedValues        sql.NullString
	External              sql.NullString
	IgnoreAbove           sql.NullInt64
	IgnoreMalformed       sql.NullBool
	IncludeInParent       sql.NullBool
	IncludeInRoot         sql.NullBool
	Index                 sql.NullBool
	InferenceID           sql.NullString
	MetricType            sql.NullString
	Metrics               sql.NullString
	Name                  string
	Normalize             sql.NullString
	Normalizer            sql.NullString
	NullValue             sql.NullString
	ObjectType            sql.NullString
	ObjectTypeMappingType sql.NullString
	Path                  sql.NullString
	Pattern               sql.NullString
	Runtime               sql.NullString
	ScalingFactor         sql.NullInt64
	SearchAnalyzer        sql.NullString
	Store                 sql.NullBool
	Subobjects            sql.NullBool
	Type                  sql.NullString
	Unit                  sql.NullString
	Value                 sql.NullString
}

type IngestPipeline struct {
	ID            int64
	DataStreamsID int64
	FileName      string
	Description   sql.NullString
}

type IngestProcessor struct {
	ID                int64
	IngestPipelinesID int64
	JsonPointer       string
	Ordinal           int64
	Type              string
	Attributes        sql.NullString
}

type Package struct {
	ID            int64
	DirName       string
	Deprecated    sql.NullString
	Description   string
	FormatVersion string
	Name          string
	OwnerGithub   string
	OwnerType     string
	SourceLicense sql.NullString
	Title         string
	Type          string
	Version       string
}

type PackageCategory struct {
	ID        int64
	PackageID int64
	Category  string
}

type PackageField struct {
	ID        int64
	PackageID int64
	FieldID   int64
}

type PackageIcon struct {
	ID         int64
	PackagesID int64
	DarkMode   sql.NullBool
	Size       sql.NullString
	Src        string
	Title      sql.NullString
	Type       sql.NullString
}

type PackageScreenshot struct {
	ID         int64
	PackagesID int64
	Size       sql.NullString
	Src        string
	Title      string
	Type       sql.NullString
}

type PackageVar struct {
	ID        int64
	PackageID int64
	VarID     int64
}

type PolicyTemplate struct {
	ID                 int64
	PackagesID         int64
	ConfigurationLinks sql.NullString
	DataStreams        sql.NullString
	DeploymentModes    sql.NullString
	Deprecated         sql.NullString
	Description        string
	FipsCompatible     sql.NullBool
	Multiple           sql.NullBool
	Name               string
	Title              string
}

type PolicyTemplateCategory struct {
	ID               int64
	PolicyTemplateID int64
	Category         string
}

type PolicyTemplateInput struct {
	ID                    int64
	PolicyTemplatesID     int64
	DeploymentModes       sql.NullString
	Deprecated            sql.NullString
	Description           string
	HideInVarGroupOptions sql.NullString
	InputGroup            sql.NullString
	Multi                 sql.NullBool
	TemplatePath          sql.NullString
	Title                 string
	Type                  string
}

type PolicyTemplateInputVar struct {
	ID                    int64
	PolicyTemplateInputID int64
	VarID                 int64
}

type PolicyTemplateVar struct {
	ID               int64
	PolicyTemplateID int64
	VarID            int64
}

type RoutingRule struct {
	ID            int64
	DataStreamsID int64
	If            string
	Namespace     sql.NullString
	TargetDataset sql.NullString
}

type Stream struct {
	ID            int64
	DataStreamsID int64
	Description   string
	Enabled       sql.NullBool
	Input         string
	TemplatePath  sql.NullString
	Title         string
}

type StreamVar struct {
	ID       int64
	StreamID int64
	VarID    int64
}

type Tag struct {
	ID         int64
	PackagesID int64
	AssetIds   sql.NullString
	AssetTypes sql.NullString
	Text       sql.NullString
}

type Transform struct {
	ID              int64
	PackagesID      int64
	DirName         string
	Meta            sql.NullString
	Description     sql.NullString
	Dest            sql.NullString
	Frequency       sql.NullString
	Latest          sql.NullString
	Pivot           sql.NullString
	RetentionPolicy sql.NullString
	Settings        sql.NullString
	Source          sql.NullString
	Sync            sql.NullString
}

type Var struct {
	ID                    int64
	Default               sql.NullString
	Description           sql.NullString
	HideInDeploymentModes sql.NullString
	MaxDuration           sql.NullString
	MinDuration           sql.NullString
	Multi                 sql.NullBool
	Name                  string
	Options               sql.NullString
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	Title                 sql.NullString
	Type                  string
	UrlAllowedSchemes     sql.NullString
}
