// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package pkgsql

import (
	"context"
	"database/sql"
)

const insertBuildManifests = `-- name: InsertBuildManifests :one
INSERT INTO build_manifests (
  packages_id,
  dependencies_ecs_import_mappings,
  dependencies_ecs_reference
) VALUES (
  ?,
  ?,
  ?
) RETURNING id
`

type InsertBuildManifestsParams struct {
	PackagesID                    int64
	DependenciesEcsImportMappings sql.NullBool
	DependenciesEcsReference      string
}

func (q *Queries) InsertBuildManifests(ctx context.Context, arg InsertBuildManifestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBuildManifests, arg.PackagesID, arg.DependenciesEcsImportMappings, arg.DependenciesEcsReference)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelogEntries = `-- name: InsertChangelogEntries :one
INSERT INTO changelog_entries (
  changelogs_id,
  description,
  link,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertChangelogEntriesParams struct {
	ChangelogsID int64
	Description  string
	Link         string
	Type         string
}

func (q *Queries) InsertChangelogEntries(ctx context.Context, arg InsertChangelogEntriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelogEntries,
		arg.ChangelogsID,
		arg.Description,
		arg.Link,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelogs = `-- name: InsertChangelogs :one
INSERT INTO changelogs (
  packages_id,
  version,
  date
) VALUES (
  ?,
  ?,
  ?
) RETURNING id
`

type InsertChangelogsParams struct {
	PackagesID int64
	Version    string
	Date       sql.NullString
}

func (q *Queries) InsertChangelogs(ctx context.Context, arg InsertChangelogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelogs, arg.PackagesID, arg.Version, arg.Date)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreamFields = `-- name: InsertDataStreamFields :one
INSERT INTO data_stream_fields (
  data_stream_id,
  field_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertDataStreamFieldsParams struct {
	DataStreamID int64
	FieldID      int64
}

func (q *Queries) InsertDataStreamFields(ctx context.Context, arg InsertDataStreamFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStreamFields, arg.DataStreamID, arg.FieldID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreams = `-- name: InsertDataStreams :one
INSERT INTO data_streams (
  packages_id,
  dir_name,
  dataset,
  dataset_is_prefix,
  deprecated,
  elasticsearch_dynamic_dataset,
  elasticsearch_dynamic_namespace,
  elasticsearch_index_mode,
  elasticsearch_index_template,
  elasticsearch_privileges,
  elasticsearch_source_mode,
  hidden,
  ilm_policy,
  "release",
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertDataStreamsParams struct {
	PackagesID                    int64
	DirName                       string
	Dataset                       sql.NullString
	DatasetIsPrefix               sql.NullBool
	Deprecated                    sql.NullString
	ElasticsearchDynamicDataset   sql.NullBool
	ElasticsearchDynamicNamespace sql.NullBool
	ElasticsearchIndexMode        sql.NullString
	ElasticsearchIndexTemplate    sql.NullString
	ElasticsearchPrivileges       sql.NullString
	ElasticsearchSourceMode       sql.NullString
	Hidden                        sql.NullBool
	IlmPolicy                     sql.NullString
	Release                       sql.NullString
	Title                         string
	Type                          sql.NullString
}

func (q *Queries) InsertDataStreams(ctx context.Context, arg InsertDataStreamsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStreams,
		arg.PackagesID,
		arg.DirName,
		arg.Dataset,
		arg.DatasetIsPrefix,
		arg.Deprecated,
		arg.ElasticsearchDynamicDataset,
		arg.ElasticsearchDynamicNamespace,
		arg.ElasticsearchIndexMode,
		arg.ElasticsearchIndexTemplate,
		arg.ElasticsearchPrivileges,
		arg.ElasticsearchSourceMode,
		arg.Hidden,
		arg.IlmPolicy,
		arg.Release,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFields = `-- name: InsertFields :one
INSERT INTO fields (
  analyzer,
  copy_to,
  date_format,
  default_metric,
  description,
  dimension,
  doc_values,
  dynamic,
  enabled,
  example,
  expected_values,
  external,
  ignore_above,
  ignore_malformed,
  include_in_parent,
  include_in_root,
  "index",
  inference_id,
  metric_type,
  metrics,
  name,
  normalize,
  normalizer,
  null_value,
  object_type,
  object_type_mapping_type,
  path,
  pattern,
  runtime,
  scaling_factor,
  search_analyzer,
  store,
  subobjects,
  type,
  unit,
  value
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertFieldsParams struct {
	Analyzer              sql.NullString
	CopyTo                sql.NullString
	DateFormat            sql.NullString
	DefaultMetric         sql.NullString
	Description           sql.NullString
	Dimension             sql.NullBool
	DocValues             sql.NullBool
	Dynamic               sql.NullString
	Enabled               sql.NullBool
	Example               sql.NullString
	ExpectedValues        sql.NullString
	External              sql.NullString
	IgnoreAbove           sql.NullInt64
	IgnoreMalformed       sql.NullBool
	IncludeInParent       sql.NullBool
	IncludeInRoot         sql.NullBool
	Index                 sql.NullBool
	InferenceID           sql.NullString
	MetricType            sql.NullString
	Metrics               sql.NullString
	Name                  string
	Normalize             sql.NullString
	Normalizer            sql.NullString
	NullValue             sql.NullString
	ObjectType            sql.NullString
	ObjectTypeMappingType sql.NullString
	Path                  sql.NullString
	Pattern               sql.NullString
	Runtime               sql.NullString
	ScalingFactor         sql.NullInt64
	SearchAnalyzer        sql.NullString
	Store                 sql.NullBool
	Subobjects            sql.NullBool
	Type                  sql.NullString
	Unit                  sql.NullString
	Value                 sql.NullString
}

func (q *Queries) InsertFields(ctx context.Context, arg InsertFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFields,
		arg.Analyzer,
		arg.CopyTo,
		arg.DateFormat,
		arg.DefaultMetric,
		arg.Description,
		arg.Dimension,
		arg.DocValues,
		arg.Dynamic,
		arg.Enabled,
		arg.Example,
		arg.ExpectedValues,
		arg.External,
		arg.IgnoreAbove,
		arg.IgnoreMalformed,
		arg.IncludeInParent,
		arg.IncludeInRoot,
		arg.Index,
		arg.InferenceID,
		arg.MetricType,
		arg.Metrics,
		arg.Name,
		arg.Normalize,
		arg.Normalizer,
		arg.NullValue,
		arg.ObjectType,
		arg.ObjectTypeMappingType,
		arg.Path,
		arg.Pattern,
		arg.Runtime,
		arg.ScalingFactor,
		arg.SearchAnalyzer,
		arg.Store,
		arg.Subobjects,
		arg.Type,
		arg.Unit,
		arg.Value,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestPipelines = `-- name: InsertIngestPipelines :one
INSERT INTO ingest_pipelines (
  data_streams_id,
  file_name,
  description
) VALUES (
  ?,
  ?,
  ?
) RETURNING id
`

type InsertIngestPipelinesParams struct {
	DataStreamsID int64
	FileName      string
	Description   sql.NullString
}

func (q *Queries) InsertIngestPipelines(ctx context.Context, arg InsertIngestPipelinesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestPipelines, arg.DataStreamsID, arg.FileName, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestProcessors = `-- name: InsertIngestProcessors :one
INSERT INTO ingest_processors (
  ingest_pipelines_id,
  json_pointer,
  ordinal,
  type,
  attributes
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertIngestProcessorsParams struct {
	IngestPipelinesID int64
	JsonPointer       string
	Ordinal           int64
	Type              string
	Attributes        sql.NullString
}

func (q *Queries) InsertIngestProcessors(ctx context.Context, arg InsertIngestProcessorsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestProcessors,
		arg.IngestPipelinesID,
		arg.JsonPointer,
		arg.Ordinal,
		arg.Type,
		arg.Attributes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageCategories = `-- name: InsertPackageCategories :one
INSERT INTO package_categories (
  package_id,
  category
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageCategoriesParams struct {
	PackageID int64
	Category  string
}

func (q *Queries) InsertPackageCategories(ctx context.Context, arg InsertPackageCategoriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageCategories, arg.PackageID, arg.Category)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageFields = `-- name: InsertPackageFields :one
INSERT INTO package_fields (
  package_id,
  field_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageFieldsParams struct {
	PackageID int64
	FieldID   int64
}

func (q *Queries) InsertPackageFields(ctx context.Context, arg InsertPackageFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageFields, arg.PackageID, arg.FieldID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageIcons = `-- name: InsertPackageIcons :one
INSERT INTO package_icons (
  packages_id,
  dark_mode,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackageIconsParams struct {
	PackagesID int64
	DarkMode   sql.NullBool
	Size       sql.NullString
	Src        string
	Title      sql.NullString
	Type       sql.NullString
}

func (q *Queries) InsertPackageIcons(ctx context.Context, arg InsertPackageIconsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageIcons,
		arg.PackagesID,
		arg.DarkMode,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageScreenshots = `-- name: InsertPackageScreenshots :one
INSERT INTO package_screenshots (
  packages_id,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackageScreenshotsParams struct {
	PackagesID int64
	Size       sql.NullString
	Src        string
	Title      string
	Type       sql.NullString
}

func (q *Queries) InsertPackageScreenshots(ctx context.Context, arg InsertPackageScreenshotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageScreenshots,
		arg.PackagesID,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageVars = `-- name: InsertPackageVars :one
INSERT INTO package_vars (
  package_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageVarsParams struct {
	PackageID int64
	VarID     int64
}

func (q *Queries) InsertPackageVars(ctx context.Context, arg InsertPackageVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageVars, arg.PackageID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackages = `-- name: InsertPackages :one
INSERT INTO packages (
  dir_name,
  deprecated,
  description,
  format_version,
  name,
  owner_github,
  owner_type,
  source_license,
  title,
  type,
  version
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackagesParams struct {
	DirName       string
	Deprecated    sql.NullString
	Description   string
	FormatVersion string
	Name          string
	OwnerGithub   string
	OwnerType     string
	SourceLicense sql.NullString
	Title         string
	Type          string
	Version       string
}

func (q *Queries) InsertPackages(ctx context.Context, arg InsertPackagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackages,
		arg.DirName,
		arg.Deprecated,
		arg.Description,
		arg.FormatVersion,
		arg.Name,
		arg.OwnerGithub,
		arg.OwnerType,
		arg.SourceLicense,
		arg.Title,
		arg.Type,
		arg.Version,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateCategories = `-- name: InsertPolicyTemplateCategories :one
INSERT INTO policy_template_categories (
  policy_template_id,
  category
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateCategoriesParams struct {
	PolicyTemplateID int64
	Category         string
}

func (q *Queries) InsertPolicyTemplateCategories(ctx context.Context, arg InsertPolicyTemplateCategoriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateCategories, arg.PolicyTemplateID, arg.Category)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputVars = `-- name: InsertPolicyTemplateInputVars :one
INSERT INTO policy_template_input_vars (
  policy_template_input_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateInputVarsParams struct {
	PolicyTemplateInputID int64
	VarID                 int64
}

func (q *Queries) InsertPolicyTemplateInputVars(ctx context.Context, arg InsertPolicyTemplateInputVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInputVars, arg.PolicyTemplateInputID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputs = `-- name: InsertPolicyTemplateInputs :one
INSERT INTO policy_template_inputs (
  policy_templates_id,
  deployment_modes,
  deprecated,
  description,
  hide_in_var_group_options,
  input_group,
  multi,
  template_path,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateInputsParams struct {
	PolicyTemplatesID     int64
	DeploymentModes       sql.NullString
	Deprecated            sql.NullString
	Description           string
	HideInVarGroupOptions sql.NullString
	InputGroup            sql.NullString
	Multi                 sql.NullBool
	TemplatePath          sql.NullString
	Title                 string
	Type                  string
}

func (q *Queries) InsertPolicyTemplateInputs(ctx context.Context, arg InsertPolicyTemplateInputsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInputs,
		arg.PolicyTemplatesID,
		arg.DeploymentModes,
		arg.Deprecated,
		arg.Description,
		arg.HideInVarGroupOptions,
		arg.InputGroup,
		arg.Multi,
		arg.TemplatePath,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateVars = `-- name: InsertPolicyTemplateVars :one
INSERT INTO policy_template_vars (
  policy_template_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateVarsParams struct {
	PolicyTemplateID int64
	VarID            int64
}

func (q *Queries) InsertPolicyTemplateVars(ctx context.Context, arg InsertPolicyTemplateVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateVars, arg.PolicyTemplateID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplates = `-- name: InsertPolicyTemplates :one
INSERT INTO policy_templates (
  packages_id,
  configuration_links,
  data_streams,
  deployment_modes,
  deprecated,
  description,
  fips_compatible,
  multiple,
  name,
  title
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplatesParams struct {
	PackagesID         int64
	ConfigurationLinks sql.NullString
	DataStreams        sql.NullString
	DeploymentModes    sql.NullString
	Deprecated         sql.NullString
	Description        string
	FipsCompatible     sql.NullBool
	Multiple           sql.NullBool
	Name               string
	Title              string
}

func (q *Queries) InsertPolicyTemplates(ctx context.Context, arg InsertPolicyTemplatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplates,
		arg.PackagesID,
		arg.ConfigurationLinks,
		arg.DataStreams,
		arg.DeploymentModes,
		arg.Deprecated,
		arg.Description,
		arg.FipsCompatible,
		arg.Multiple,
		arg.Name,
		arg.Title,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRoutingRules = `-- name: InsertRoutingRules :one
INSERT INTO routing_rules (
  data_streams_id,
  "if",
  namespace,
  target_dataset
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertRoutingRulesParams struct {
	DataStreamsID int64
	If            string
	Namespace     sql.NullString
	TargetDataset sql.NullString
}

func (q *Queries) InsertRoutingRules(ctx context.Context, arg InsertRoutingRulesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRoutingRules,
		arg.DataStreamsID,
		arg.If,
		arg.Namespace,
		arg.TargetDataset,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreamVars = `-- name: InsertStreamVars :one
INSERT INTO stream_vars (
  stream_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertStreamVarsParams struct {
	StreamID int64
	VarID    int64
}

func (q *Queries) InsertStreamVars(ctx context.Context, arg InsertStreamVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStreamVars, arg.StreamID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreams = `-- name: InsertStreams :one
INSERT INTO streams (
  data_streams_id,
  description,
  enabled,
  input,
  template_path,
  title
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertStreamsParams struct {
	DataStreamsID int64
	Description   string
	Enabled       sql.NullBool
	Input         string
	TemplatePath  sql.NullString
	Title         string
}

func (q *Queries) InsertStreams(ctx context.Context, arg InsertStreamsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStreams,
		arg.DataStreamsID,
		arg.Description,
		arg.Enabled,
		arg.Input,
		arg.TemplatePath,
		arg.Title,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTags = `-- name: InsertTags :one
INSERT INTO tags (
  packages_id,
  asset_ids,
  asset_types,
  text
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertTagsParams struct {
	PackagesID int64
	AssetIds   sql.NullString
	AssetTypes sql.NullString
	Text       sql.NullString
}

func (q *Queries) InsertTags(ctx context.Context, arg InsertTagsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTags,
		arg.PackagesID,
		arg.AssetIds,
		arg.AssetTypes,
		arg.Text,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransforms = `-- name: InsertTransforms :one
INSERT INTO transforms (
  packages_id,
  dir_name,
  meta,
  description,
  dest,
  frequency,
  latest,
  pivot,
  retention_policy,
  settings,
  source,
  sync
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertTransformsParams struct {
	PackagesID      int64
	DirName         string
	Meta            sql.NullString
	Description     sql.NullString
	Dest            sql.NullString
	Frequency       sql.NullString
	Latest          sql.NullString
	Pivot           sql.NullString
	RetentionPolicy sql.NullString
	Settings        sql.NullString
	Source          sql.NullString
	Sync            sql.NullString
}

func (q *Queries) InsertTransforms(ctx context.Context, arg InsertTransformsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransforms,
		arg.PackagesID,
		arg.DirName,
		arg.Meta,
		arg.Description,
		arg.Dest,
		arg.Frequency,
		arg.Latest,
		arg.Pivot,
		arg.RetentionPolicy,
		arg.Settings,
		arg.Source,
		arg.Sync,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertVars = `-- name: InsertVars :one
INSERT INTO vars (
  "default",
  description,
  hide_in_deployment_modes,
  max_duration,
  min_duration,
  multi,
  name,
  options,
  required,
  secret,
  show_user,
  title,
  type,
  url_allowed_schemes
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertVarsParams struct {
	Default               sql.NullString
	Description           sql.NullString
	HideInDeploymentModes sql.NullString
	MaxDuration           sql.NullString
	MinDuration           sql.NullString
	Multi                 sql.NullBool
	Name                  string
	Options               sql.NullString
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	Title                 sql.NullString
	Type                  string
	UrlAllowedSchemes     sql.NullString
}

func (q *Queries) InsertVars(ctx context.Context, arg InsertVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertVars,
		arg.Default,
		arg.Description,
		arg.HideInDeploymentModes,
		arg.MaxDuration,
		arg.MinDuration,
		arg.Multi,
		arg.Name,
		arg.Options,
		arg.Required,
		arg.Secret,
		arg.ShowUser,
		arg.Title,
		arg.Type,
		arg.UrlAllowedSchemes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
