// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package pkgsql

import (
	"context"
	"database/sql"
)

const insertBuildManifests = `-- name: InsertBuildManifests :one
INSERT INTO build_manifests (
  packages_id,
  file_path,
  file_line,
  file_column,
  dependencies_ecs_import_mappings,
  dependencies_ecs_reference
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertBuildManifestsParams struct {
	PackagesID                    int64
	FilePath                      sql.NullString
	FileLine                      sql.NullInt64
	FileColumn                    sql.NullInt64
	DependenciesEcsImportMappings sql.NullBool
	DependenciesEcsReference      string
}

func (q *Queries) InsertBuildManifests(ctx context.Context, arg InsertBuildManifestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBuildManifests,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.DependenciesEcsImportMappings,
		arg.DependenciesEcsReference,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelogEntries = `-- name: InsertChangelogEntries :one
INSERT INTO changelog_entries (
  changelogs_id,
  description,
  link,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertChangelogEntriesParams struct {
	ChangelogsID int64
	Description  string
	Link         string
	Type         string
}

func (q *Queries) InsertChangelogEntries(ctx context.Context, arg InsertChangelogEntriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelogEntries,
		arg.ChangelogsID,
		arg.Description,
		arg.Link,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelogs = `-- name: InsertChangelogs :one
INSERT INTO changelogs (
  packages_id,
  file_path,
  file_line,
  file_column,
  version,
  date
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertChangelogsParams struct {
	PackagesID int64
	FilePath   sql.NullString
	FileLine   sql.NullInt64
	FileColumn sql.NullInt64
	Version    string
	Date       sql.NullString
}

func (q *Queries) InsertChangelogs(ctx context.Context, arg InsertChangelogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelogs,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Version,
		arg.Date,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreamFields = `-- name: InsertDataStreamFields :one
INSERT INTO data_stream_fields (
  field_id,
  data_stream_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertDataStreamFieldsParams struct {
	FieldID      int64
	DataStreamID int64
}

func (q *Queries) InsertDataStreamFields(ctx context.Context, arg InsertDataStreamFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStreamFields, arg.FieldID, arg.DataStreamID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreams = `-- name: InsertDataStreams :one
INSERT INTO data_streams (
  packages_id,
  dir_name,
  file_path,
  file_line,
  file_column,
  dataset,
  dataset_is_prefix,
  deprecated_description,
  deprecated_replaced_by_data_stream,
  deprecated_replaced_by_input,
  deprecated_replaced_by_package,
  deprecated_replaced_by_policy_template,
  deprecated_replaced_by_variable,
  deprecated_since,
  elasticsearch_dynamic_dataset,
  elasticsearch_dynamic_namespace,
  elasticsearch_index_mode,
  elasticsearch_index_template,
  elasticsearch_privileges,
  elasticsearch_source_mode,
  hidden,
  ilm_policy,
  "release",
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertDataStreamsParams struct {
	PackagesID                         int64
	DirName                            string
	FilePath                           sql.NullString
	FileLine                           sql.NullInt64
	FileColumn                         sql.NullInt64
	Dataset                            sql.NullString
	DatasetIsPrefix                    sql.NullBool
	DeprecatedDescription              sql.NullString
	DeprecatedReplacedByDataStream     sql.NullString
	DeprecatedReplacedByInput          sql.NullString
	DeprecatedReplacedByPackage        sql.NullString
	DeprecatedReplacedByPolicyTemplate sql.NullString
	DeprecatedReplacedByVariable       sql.NullString
	DeprecatedSince                    sql.NullString
	ElasticsearchDynamicDataset        sql.NullBool
	ElasticsearchDynamicNamespace      sql.NullBool
	ElasticsearchIndexMode             sql.NullString
	ElasticsearchIndexTemplate         interface{}
	ElasticsearchPrivileges            interface{}
	ElasticsearchSourceMode            sql.NullString
	Hidden                             sql.NullBool
	IlmPolicy                          sql.NullString
	Release                            sql.NullString
	Title                              string
	Type                               sql.NullString
}

func (q *Queries) InsertDataStreams(ctx context.Context, arg InsertDataStreamsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStreams,
		arg.PackagesID,
		arg.DirName,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Dataset,
		arg.DatasetIsPrefix,
		arg.DeprecatedDescription,
		arg.DeprecatedReplacedByDataStream,
		arg.DeprecatedReplacedByInput,
		arg.DeprecatedReplacedByPackage,
		arg.DeprecatedReplacedByPolicyTemplate,
		arg.DeprecatedReplacedByVariable,
		arg.DeprecatedSince,
		arg.ElasticsearchDynamicDataset,
		arg.ElasticsearchDynamicNamespace,
		arg.ElasticsearchIndexMode,
		arg.ElasticsearchIndexTemplate,
		arg.ElasticsearchPrivileges,
		arg.ElasticsearchSourceMode,
		arg.Hidden,
		arg.IlmPolicy,
		arg.Release,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDiscoveryFields = `-- name: InsertDiscoveryFields :one
INSERT INTO discovery_fields (
  packages_id,
  name
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertDiscoveryFieldsParams struct {
	PackagesID int64
	Name       string
}

func (q *Queries) InsertDiscoveryFields(ctx context.Context, arg InsertDiscoveryFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDiscoveryFields, arg.PackagesID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFields = `-- name: InsertFields :one
INSERT INTO fields (
  file_path,
  file_line,
  file_column,
  analyzer,
  copy_to,
  date_format,
  default_metric,
  description,
  dimension,
  doc_values,
  dynamic,
  enabled,
  example,
  expected_values,
  external,
  ignore_above,
  ignore_malformed,
  include_in_parent,
  include_in_root,
  "index",
  inference_id,
  metric_type,
  metrics,
  multi_fields,
  name,
  normalize,
  normalizer,
  null_value,
  object_type,
  object_type_mapping_type,
  path,
  pattern,
  runtime,
  scaling_factor,
  search_analyzer,
  store,
  subobjects,
  type,
  unit,
  value,
  json_pointer
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertFieldsParams struct {
	FilePath              sql.NullString
	FileLine              sql.NullInt64
	FileColumn            sql.NullInt64
	Analyzer              sql.NullString
	CopyTo                sql.NullString
	DateFormat            sql.NullString
	DefaultMetric         interface{}
	Description           sql.NullString
	Dimension             sql.NullBool
	DocValues             sql.NullBool
	Dynamic               interface{}
	Enabled               sql.NullBool
	Example               interface{}
	ExpectedValues        interface{}
	External              sql.NullString
	IgnoreAbove           sql.NullInt64
	IgnoreMalformed       sql.NullBool
	IncludeInParent       sql.NullBool
	IncludeInRoot         sql.NullBool
	Index                 sql.NullBool
	InferenceID           sql.NullString
	MetricType            sql.NullString
	Metrics               interface{}
	MultiFields           interface{}
	Name                  string
	Normalize             interface{}
	Normalizer            sql.NullString
	NullValue             interface{}
	ObjectType            sql.NullString
	ObjectTypeMappingType sql.NullString
	Path                  sql.NullString
	Pattern               sql.NullString
	Runtime               interface{}
	ScalingFactor         sql.NullInt64
	SearchAnalyzer        sql.NullString
	Store                 sql.NullBool
	Subobjects            sql.NullBool
	Type                  sql.NullString
	Unit                  sql.NullString
	Value                 sql.NullString
	JsonPointer           sql.NullString
}

func (q *Queries) InsertFields(ctx context.Context, arg InsertFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFields,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Analyzer,
		arg.CopyTo,
		arg.DateFormat,
		arg.DefaultMetric,
		arg.Description,
		arg.Dimension,
		arg.DocValues,
		arg.Dynamic,
		arg.Enabled,
		arg.Example,
		arg.ExpectedValues,
		arg.External,
		arg.IgnoreAbove,
		arg.IgnoreMalformed,
		arg.IncludeInParent,
		arg.IncludeInRoot,
		arg.Index,
		arg.InferenceID,
		arg.MetricType,
		arg.Metrics,
		arg.MultiFields,
		arg.Name,
		arg.Normalize,
		arg.Normalizer,
		arg.NullValue,
		arg.ObjectType,
		arg.ObjectTypeMappingType,
		arg.Path,
		arg.Pattern,
		arg.Runtime,
		arg.ScalingFactor,
		arg.SearchAnalyzer,
		arg.Store,
		arg.Subobjects,
		arg.Type,
		arg.Unit,
		arg.Value,
		arg.JsonPointer,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImages = `-- name: InsertImages :one
INSERT INTO images (
  src,
  width,
  height,
  byte_size,
  sha256,
  packages_id
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertImagesParams struct {
	Src        string
	Width      sql.NullInt64
	Height     sql.NullInt64
	ByteSize   int64
	Sha256     string
	PackagesID int64
}

func (q *Queries) InsertImages(ctx context.Context, arg InsertImagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertImages,
		arg.Src,
		arg.Width,
		arg.Height,
		arg.ByteSize,
		arg.Sha256,
		arg.PackagesID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestPipelines = `-- name: InsertIngestPipelines :one
INSERT INTO ingest_pipelines (
  data_streams_id,
  file_name,
  file_path,
  file_line,
  file_column,
  description
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertIngestPipelinesParams struct {
	DataStreamsID int64
	FileName      string
	FilePath      sql.NullString
	FileLine      sql.NullInt64
	FileColumn    sql.NullInt64
	Description   sql.NullString
}

func (q *Queries) InsertIngestPipelines(ctx context.Context, arg InsertIngestPipelinesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestPipelines,
		arg.DataStreamsID,
		arg.FileName,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestProcessors = `-- name: InsertIngestProcessors :one
INSERT INTO ingest_processors (
  ingest_pipelines_id,
  type,
  attributes,
  json_pointer,
  ordinal
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertIngestProcessorsParams struct {
	IngestPipelinesID int64
	Type              string
	Attributes        interface{}
	JsonPointer       string
	Ordinal           int64
}

func (q *Queries) InsertIngestProcessors(ctx context.Context, arg InsertIngestProcessorsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestProcessors,
		arg.IngestPipelinesID,
		arg.Type,
		arg.Attributes,
		arg.JsonPointer,
		arg.Ordinal,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageCategories = `-- name: InsertPackageCategories :one
INSERT INTO package_categories (
  package_id,
  category
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageCategoriesParams struct {
	PackageID int64
	Category  string
}

func (q *Queries) InsertPackageCategories(ctx context.Context, arg InsertPackageCategoriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageCategories, arg.PackageID, arg.Category)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageFields = `-- name: InsertPackageFields :one
INSERT INTO package_fields (
  package_id,
  field_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageFieldsParams struct {
	PackageID int64
	FieldID   int64
}

func (q *Queries) InsertPackageFields(ctx context.Context, arg InsertPackageFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageFields, arg.PackageID, arg.FieldID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageIcons = `-- name: InsertPackageIcons :one
INSERT INTO package_icons (
  packages_id,
  dark_mode,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackageIconsParams struct {
	PackagesID int64
	DarkMode   sql.NullBool
	Size       sql.NullString
	Src        string
	Title      sql.NullString
	Type       sql.NullString
}

func (q *Queries) InsertPackageIcons(ctx context.Context, arg InsertPackageIconsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageIcons,
		arg.PackagesID,
		arg.DarkMode,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageScreenshots = `-- name: InsertPackageScreenshots :one
INSERT INTO package_screenshots (
  packages_id,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackageScreenshotsParams struct {
	PackagesID int64
	Size       sql.NullString
	Src        string
	Title      string
	Type       sql.NullString
}

func (q *Queries) InsertPackageScreenshots(ctx context.Context, arg InsertPackageScreenshotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageScreenshots,
		arg.PackagesID,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageVars = `-- name: InsertPackageVars :one
INSERT INTO package_vars (
  package_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPackageVarsParams struct {
	PackageID int64
	VarID     int64
}

func (q *Queries) InsertPackageVars(ctx context.Context, arg InsertPackageVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackageVars, arg.PackageID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackages = `-- name: InsertPackages :one
INSERT INTO packages (
  elasticsearch_privileges_cluster,
  policy_templates_behavior,
  dir_name,
  conditions_kibana_version,
  conditions_elastic_subscription,
  agent_privileges_root,
  file_path,
  file_line,
  file_column,
  deprecated_description,
  deprecated_replaced_by_data_stream,
  deprecated_replaced_by_input,
  deprecated_replaced_by_package,
  deprecated_replaced_by_policy_template,
  deprecated_replaced_by_variable,
  deprecated_since,
  description,
  format_version,
  name,
  owner_github,
  owner_type,
  source_license,
  title,
  type,
  version
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPackagesParams struct {
	ElasticsearchPrivilegesCluster     interface{}
	PolicyTemplatesBehavior            sql.NullString
	DirName                            string
	ConditionsKibanaVersion            sql.NullString
	ConditionsElasticSubscription      sql.NullString
	AgentPrivilegesRoot                sql.NullBool
	FilePath                           sql.NullString
	FileLine                           sql.NullInt64
	FileColumn                         sql.NullInt64
	DeprecatedDescription              sql.NullString
	DeprecatedReplacedByDataStream     sql.NullString
	DeprecatedReplacedByInput          sql.NullString
	DeprecatedReplacedByPackage        sql.NullString
	DeprecatedReplacedByPolicyTemplate sql.NullString
	DeprecatedReplacedByVariable       sql.NullString
	DeprecatedSince                    sql.NullString
	Description                        string
	FormatVersion                      string
	Name                               string
	OwnerGithub                        string
	OwnerType                          string
	SourceLicense                      sql.NullString
	Title                              string
	Type                               string
	Version                            string
}

func (q *Queries) InsertPackages(ctx context.Context, arg InsertPackagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackages,
		arg.ElasticsearchPrivilegesCluster,
		arg.PolicyTemplatesBehavior,
		arg.DirName,
		arg.ConditionsKibanaVersion,
		arg.ConditionsElasticSubscription,
		arg.AgentPrivilegesRoot,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.DeprecatedDescription,
		arg.DeprecatedReplacedByDataStream,
		arg.DeprecatedReplacedByInput,
		arg.DeprecatedReplacedByPackage,
		arg.DeprecatedReplacedByPolicyTemplate,
		arg.DeprecatedReplacedByVariable,
		arg.DeprecatedSince,
		arg.Description,
		arg.FormatVersion,
		arg.Name,
		arg.OwnerGithub,
		arg.OwnerType,
		arg.SourceLicense,
		arg.Title,
		arg.Type,
		arg.Version,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateCategories = `-- name: InsertPolicyTemplateCategories :one
INSERT INTO policy_template_categories (
  category,
  policy_template_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateCategoriesParams struct {
	Category         string
	PolicyTemplateID int64
}

func (q *Queries) InsertPolicyTemplateCategories(ctx context.Context, arg InsertPolicyTemplateCategoriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateCategories, arg.Category, arg.PolicyTemplateID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateIcons = `-- name: InsertPolicyTemplateIcons :one
INSERT INTO policy_template_icons (
  policy_templates_id,
  dark_mode,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateIconsParams struct {
	PolicyTemplatesID int64
	DarkMode          sql.NullBool
	Size              sql.NullString
	Src               string
	Title             sql.NullString
	Type              sql.NullString
}

func (q *Queries) InsertPolicyTemplateIcons(ctx context.Context, arg InsertPolicyTemplateIconsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateIcons,
		arg.PolicyTemplatesID,
		arg.DarkMode,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputVars = `-- name: InsertPolicyTemplateInputVars :one
INSERT INTO policy_template_input_vars (
  var_id,
  policy_template_input_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateInputVarsParams struct {
	VarID                 int64
	PolicyTemplateInputID int64
}

func (q *Queries) InsertPolicyTemplateInputVars(ctx context.Context, arg InsertPolicyTemplateInputVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInputVars, arg.VarID, arg.PolicyTemplateInputID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputs = `-- name: InsertPolicyTemplateInputs :one
INSERT INTO policy_template_inputs (
  policy_templates_id,
  deployment_modes,
  deprecated_description,
  deprecated_replaced_by_data_stream,
  deprecated_replaced_by_input,
  deprecated_replaced_by_package,
  deprecated_replaced_by_policy_template,
  deprecated_replaced_by_variable,
  deprecated_since,
  description,
  hide_in_var_group_options,
  input_group,
  multi,
  template_path,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateInputsParams struct {
	PolicyTemplatesID                  int64
	DeploymentModes                    interface{}
	DeprecatedDescription              sql.NullString
	DeprecatedReplacedByDataStream     sql.NullString
	DeprecatedReplacedByInput          sql.NullString
	DeprecatedReplacedByPackage        sql.NullString
	DeprecatedReplacedByPolicyTemplate sql.NullString
	DeprecatedReplacedByVariable       sql.NullString
	DeprecatedSince                    sql.NullString
	Description                        string
	HideInVarGroupOptions              interface{}
	InputGroup                         sql.NullString
	Multi                              sql.NullBool
	TemplatePath                       sql.NullString
	Title                              string
	Type                               string
}

func (q *Queries) InsertPolicyTemplateInputs(ctx context.Context, arg InsertPolicyTemplateInputsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInputs,
		arg.PolicyTemplatesID,
		arg.DeploymentModes,
		arg.DeprecatedDescription,
		arg.DeprecatedReplacedByDataStream,
		arg.DeprecatedReplacedByInput,
		arg.DeprecatedReplacedByPackage,
		arg.DeprecatedReplacedByPolicyTemplate,
		arg.DeprecatedReplacedByVariable,
		arg.DeprecatedSince,
		arg.Description,
		arg.HideInVarGroupOptions,
		arg.InputGroup,
		arg.Multi,
		arg.TemplatePath,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateScreenshots = `-- name: InsertPolicyTemplateScreenshots :one
INSERT INTO policy_template_screenshots (
  policy_templates_id,
  size,
  src,
  title,
  type
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateScreenshotsParams struct {
	PolicyTemplatesID int64
	Size              sql.NullString
	Src               string
	Title             string
	Type              sql.NullString
}

func (q *Queries) InsertPolicyTemplateScreenshots(ctx context.Context, arg InsertPolicyTemplateScreenshotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateScreenshots,
		arg.PolicyTemplatesID,
		arg.Size,
		arg.Src,
		arg.Title,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateVars = `-- name: InsertPolicyTemplateVars :one
INSERT INTO policy_template_vars (
  policy_template_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplateVarsParams struct {
	PolicyTemplateID int64
	VarID            int64
}

func (q *Queries) InsertPolicyTemplateVars(ctx context.Context, arg InsertPolicyTemplateVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateVars, arg.PolicyTemplateID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplates = `-- name: InsertPolicyTemplates :one
INSERT INTO policy_templates (
  packages_id,
  configuration_links,
  data_streams,
  deployment_modes_agentless_division,
  deployment_modes_agentless_enabled,
  deployment_modes_agentless_is_default,
  deployment_modes_agentless_organization,
  deployment_modes_agentless_resources_requests_cpu,
  deployment_modes_agentless_resources_requests_memory,
  deployment_modes_agentless_team,
  deployment_modes_default_enabled,
  deprecated_description,
  deprecated_replaced_by_data_stream,
  deprecated_replaced_by_input,
  deprecated_replaced_by_package,
  deprecated_replaced_by_policy_template,
  deprecated_replaced_by_variable,
  deprecated_since,
  description,
  fips_compatible,
  multiple,
  name,
  title
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertPolicyTemplatesParams struct {
	PackagesID                                      int64
	ConfigurationLinks                              interface{}
	DataStreams                                     interface{}
	DeploymentModesAgentlessDivision                sql.NullString
	DeploymentModesAgentlessEnabled                 sql.NullBool
	DeploymentModesAgentlessIsDefault               sql.NullBool
	DeploymentModesAgentlessOrganization            sql.NullString
	DeploymentModesAgentlessResourcesRequestsCpu    sql.NullString
	DeploymentModesAgentlessResourcesRequestsMemory sql.NullString
	DeploymentModesAgentlessTeam                    sql.NullString
	DeploymentModesDefaultEnabled                   sql.NullBool
	DeprecatedDescription                           sql.NullString
	DeprecatedReplacedByDataStream                  sql.NullString
	DeprecatedReplacedByInput                       sql.NullString
	DeprecatedReplacedByPackage                     sql.NullString
	DeprecatedReplacedByPolicyTemplate              sql.NullString
	DeprecatedReplacedByVariable                    sql.NullString
	DeprecatedSince                                 sql.NullString
	Description                                     string
	FipsCompatible                                  sql.NullBool
	Multiple                                        sql.NullBool
	Name                                            string
	Title                                           string
}

func (q *Queries) InsertPolicyTemplates(ctx context.Context, arg InsertPolicyTemplatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplates,
		arg.PackagesID,
		arg.ConfigurationLinks,
		arg.DataStreams,
		arg.DeploymentModesAgentlessDivision,
		arg.DeploymentModesAgentlessEnabled,
		arg.DeploymentModesAgentlessIsDefault,
		arg.DeploymentModesAgentlessOrganization,
		arg.DeploymentModesAgentlessResourcesRequestsCpu,
		arg.DeploymentModesAgentlessResourcesRequestsMemory,
		arg.DeploymentModesAgentlessTeam,
		arg.DeploymentModesDefaultEnabled,
		arg.DeprecatedDescription,
		arg.DeprecatedReplacedByDataStream,
		arg.DeprecatedReplacedByInput,
		arg.DeprecatedReplacedByPackage,
		arg.DeprecatedReplacedByPolicyTemplate,
		arg.DeprecatedReplacedByVariable,
		arg.DeprecatedSince,
		arg.Description,
		arg.FipsCompatible,
		arg.Multiple,
		arg.Name,
		arg.Title,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRoutingRules = `-- name: InsertRoutingRules :one
INSERT INTO routing_rules (
  data_streams_id,
  "if",
  namespace,
  target_dataset
) VALUES (
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertRoutingRulesParams struct {
	DataStreamsID int64
	If            string
	Namespace     interface{}
	TargetDataset interface{}
}

func (q *Queries) InsertRoutingRules(ctx context.Context, arg InsertRoutingRulesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRoutingRules,
		arg.DataStreamsID,
		arg.If,
		arg.Namespace,
		arg.TargetDataset,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSampleEvents = `-- name: InsertSampleEvents :one
INSERT INTO sample_events (
  event,
  data_streams_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertSampleEventsParams struct {
	Event         interface{}
	DataStreamsID int64
}

func (q *Queries) InsertSampleEvents(ctx context.Context, arg InsertSampleEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSampleEvents, arg.Event, arg.DataStreamsID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreamVars = `-- name: InsertStreamVars :one
INSERT INTO stream_vars (
  stream_id,
  var_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertStreamVarsParams struct {
	StreamID int64
	VarID    int64
}

func (q *Queries) InsertStreamVars(ctx context.Context, arg InsertStreamVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStreamVars, arg.StreamID, arg.VarID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreams = `-- name: InsertStreams :one
INSERT INTO streams (
  data_streams_id,
  description,
  enabled,
  input,
  template_path,
  title
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertStreamsParams struct {
	DataStreamsID int64
	Description   string
	Enabled       sql.NullBool
	Input         string
	TemplatePath  sql.NullString
	Title         string
}

func (q *Queries) InsertStreams(ctx context.Context, arg InsertStreamsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStreams,
		arg.DataStreamsID,
		arg.Description,
		arg.Enabled,
		arg.Input,
		arg.TemplatePath,
		arg.Title,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTags = `-- name: InsertTags :one
INSERT INTO tags (
  packages_id,
  file_path,
  file_line,
  file_column,
  asset_ids,
  asset_types,
  text
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertTagsParams struct {
	PackagesID int64
	FilePath   sql.NullString
	FileLine   sql.NullInt64
	FileColumn sql.NullInt64
	AssetIds   interface{}
	AssetTypes interface{}
	Text       sql.NullString
}

func (q *Queries) InsertTags(ctx context.Context, arg InsertTagsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTags,
		arg.PackagesID,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.AssetIds,
		arg.AssetTypes,
		arg.Text,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransformFields = `-- name: InsertTransformFields :one
INSERT INTO transform_fields (
  transform_id,
  field_id
) VALUES (
  ?,
  ?
) RETURNING id
`

type InsertTransformFieldsParams struct {
	TransformID int64
	FieldID     int64
}

func (q *Queries) InsertTransformFields(ctx context.Context, arg InsertTransformFieldsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransformFields, arg.TransformID, arg.FieldID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransforms = `-- name: InsertTransforms :one
INSERT INTO transforms (
  packages_id,
  dir_name,
  manifest_start,
  manifest_destination_index_template,
  file_path,
  file_line,
  file_column,
  meta,
  description,
  dest,
  frequency,
  latest,
  pivot,
  retention_policy,
  settings,
  source,
  sync
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertTransformsParams struct {
	PackagesID                       int64
	DirName                          string
	ManifestStart                    sql.NullBool
	ManifestDestinationIndexTemplate interface{}
	FilePath                         sql.NullString
	FileLine                         sql.NullInt64
	FileColumn                       sql.NullInt64
	Meta                             interface{}
	Description                      sql.NullString
	Dest                             interface{}
	Frequency                        sql.NullString
	Latest                           interface{}
	Pivot                            interface{}
	RetentionPolicy                  interface{}
	Settings                         interface{}
	Source                           interface{}
	Sync                             interface{}
}

func (q *Queries) InsertTransforms(ctx context.Context, arg InsertTransformsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransforms,
		arg.PackagesID,
		arg.DirName,
		arg.ManifestStart,
		arg.ManifestDestinationIndexTemplate,
		arg.FilePath,
		arg.FileLine,
		arg.FileColumn,
		arg.Meta,
		arg.Description,
		arg.Dest,
		arg.Frequency,
		arg.Latest,
		arg.Pivot,
		arg.RetentionPolicy,
		arg.Settings,
		arg.Source,
		arg.Sync,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertVars = `-- name: InsertVars :one
INSERT INTO vars (
  "default",
  description,
  hide_in_deployment_modes,
  max_duration,
  min_duration,
  multi,
  name,
  options,
  required,
  secret,
  show_user,
  title,
  type,
  url_allowed_schemes
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id
`

type InsertVarsParams struct {
	Default               interface{}
	Description           sql.NullString
	HideInDeploymentModes interface{}
	MaxDuration           sql.NullString
	MinDuration           sql.NullString
	Multi                 sql.NullBool
	Name                  string
	Options               interface{}
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	Title                 sql.NullString
	Type                  string
	UrlAllowedSchemes     interface{}
}

func (q *Queries) InsertVars(ctx context.Context, arg InsertVarsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertVars,
		arg.Default,
		arg.Description,
		arg.HideInDeploymentModes,
		arg.MaxDuration,
		arg.MinDuration,
		arg.Multi,
		arg.Name,
		arg.Options,
		arg.Required,
		arg.Secret,
		arg.ShowUser,
		arg.Title,
		arg.Type,
		arg.UrlAllowedSchemes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
